#!/usr/bin/env python3

#################################################
#     Siesta Tool Box - Suite                   #
# Developed by Dr. Carlos M. O. Bastos          #
#      bastoscmo.github.io                      #
#################################################

VERSION = "1.0.0"

import os
import sys
import argparse
from stb.core import structure_io
from stb.core.bsse import make_ghost_variant, strip_config_extra_include
from stb.core.siesta_log import report_quality_diagnostics
from stb.core.cli import color_text, show_intro, print_dual, print_section, print_table, capture_library_noise
from stb.core.pseudopotentials import copy_pseudo
from stb.core.adsorption_sites import SPIN_POLARIZED_BLOCK, DIPOLE_CORRECTION_BLOCK, VDW_CORRECTION_BLOCK
from stb.adsorb_analysis import read_site_table

REPORT_FILE = "adsorption_bsse_report.txt"
CONFIG_EXTRA_FILE = "config_extra.fdf"

FIXED_CELL_BLOCK = (
    "# Auto-generated by stb-adsorb -- keeps the cell fixed (see the example's\n"
    "# README.md for why).\n"
    "MD.VariableCell false\n"
)

# BSSE ghost-fragment references (bsse_slab/, bsse_adsorbate/) need
# single-point SCF: the counterpoise correction is only meaningful if every
# fragment is evaluated at the EXACT SAME geometry -- here, the site's own
# RELAXED geometry (read from its finished siesta.XV), so re-relaxing here
# would silently invalidate it -- same single-point-enforcement idea as
# hubbardu.py's SINGLE_POINT_BLOCK, and the same BSSE_SINGLE_POINT_BLOCK
# adsorb.py used to define before this stage was split out.
BSSE_SINGLE_POINT_BLOCK = FIXED_CELL_BLOCK + (
    "MD.TypeOfRun       CG\n"
    "MD.Steps           0\n"
)


def read_site_theory_flags(site_dir):
    """Returns (spin_polarized, dipole_corrected, vdw_corrected): whether the
    site's own config_extra.fdf (written by stb-adsorb's
    write_reference_folder, see core/adsorption_sites.py) forced spin
    polarization, the slab dipole correction, and/or the DFT-D3 dispersion
    correction for THIS site. A counterpoise correction is only meaningful
    if every fragment is evaluated at the exact same level of theory as
    E_site, not just the same geometry -- real, user-reported bug: the
    ghost fragments used to always fall back to config_extra.fdf's own
    BSSE_SINGLE_POINT_BLOCK (no Spin/dipole line at all), so an open-shell
    adsorbate's ghost fragment was silently solved spin-restricted while
    E_site was spin-polarized, adding a spurious ~1 eV spin-restriction
    penalty that swamped the genuine (~0.01-0.2 eV) BSSE correction and even
    flipped the corrected E_ads to look MORE bound than the raw value --
    physically impossible for a real counterpoise correction. `vdw_corrected`
    closes the identical gap for DFT-D3 (forced unconditionally on every
    stb-adsorb folder, see adsorb.py's own force_vdw=True call sites) --
    without it, a ghost fragment would be missing the pairwise dispersion
    terms E_site actually includes, the same "different level of theory"
    bug class in a new guise. Reading the site's own config_extra.fdf
    (rather than re-deriving this from CLI flags) is robust regardless of
    which stb-adsorb version/flags produced that site. Returns
    (False, False, False) if the site has no config_extra.fdf at all (e.g.
    a hand-built site folder).
    """
    path = os.path.join(site_dir, CONFIG_EXTRA_FILE)
    if not os.path.isfile(path):
        return False, False, False
    with open(path) as f:
        text = f.read()
    return "Spin" in text, "Slab.DipoleCorrection" in text, "DFTD3" in text


def write_bsse_folders(bsse_dir, site_fdf, n_substrate, calc_text, pp_path):
    """Writes the two ghost-fragment references a Boys-Bernardi counterpoise
    (BSSE) correction of this site's adsorption energy needs: '<bsse_dir>/
    bsse_slab/' (real slab + ghost adsorbate, same geometry as the site) and
    '<bsse_dir>/bsse_adsorbate/' (ghost slab + real adsorbate, same
    geometry) -- stb-adsorbAnalysis then computes E_ads(BSSE) = E_site -
    E_bsse_slab - E_bsse_adsorbate. `bsse_dir` is a folder under the run's
    own parallel 'bsse/<site_label>/' tree, NOT nested inside
    'sites/<site_label>/' -- keeps each site's own folder to just its real
    physical calculation, with every BSSE counterpoise reference collected
    under one separate root instead. Same --calc template as the site
    itself (same cell/k-grid), but with config_extra.fdf forcing
    single-point SCF on top of the fixed cell (BSSE_SINGLE_POINT_BLOCK) --
    `site_fdf` must already be the site's RELAXED geometry (see
    read_relaxed_site_fdf) for the correction to mean anything -- moved
    here unchanged from adsorb.py, whose caller used to pass the
    pre-relaxation initial guess instead (the bug this stage fixes).

    Also inherits the site's own level of theory (spin polarization, slab
    dipole correction, DFT-D3 dispersion) via read_site_theory_flags(pp_path)
    -- pp_path is always the site's own directory here (see main()) -- so
    the ghost fragments are solved with the exact same Spin/
    Slab.DipoleCorrection/DFTD3 setting as E_site itself, not just the same
    geometry. Returns (spin_polarized, dipole_corrected, vdw_corrected) so
    the caller can report it.
    """
    n_total = len(site_fdf.atoms)
    slab_variant = make_ghost_variant(site_fdf, n_substrate, n_total)  # ghost the adsorbate part
    ads_variant = make_ghost_variant(site_fdf, 0, n_substrate)         # ghost the slab part

    spin_polarized, dipole_corrected, vdw_corrected = read_site_theory_flags(pp_path)
    config_extra_content = BSSE_SINGLE_POINT_BLOCK
    if spin_polarized:
        config_extra_content += SPIN_POLARIZED_BLOCK
    if dipole_corrected:
        config_extra_content += DIPOLE_CORRECTION_BLOCK
    if vdw_corrected:
        config_extra_content += VDW_CORRECTION_BLOCK

    for sub_dir, variant in [("bsse_slab", slab_variant), ("bsse_adsorbate", ads_variant)]:
        out_dir = os.path.join(bsse_dir, sub_dir)
        os.makedirs(out_dir, exist_ok=True)
        structure_io.write_fdf(variant, os.path.join(out_dir, "structure.fdf"))
        with open(os.path.join(out_dir, CONFIG_EXTRA_FILE), "w") as f:
            f.write(config_extra_content)
        with open(os.path.join(out_dir, "calc.fdf"), "w") as f:
            f.write(structure_io.prepend_include(calc_text, CONFIG_EXTRA_FILE))
        present_labels = sorted({symbol for symbol, _ in variant.atoms})
        for label in present_labels:
            real_symbol = label[:-len("_ghost")] if label.endswith("_ghost") else label
            copy_pseudo(pp_path, real_symbol, out_dir, dest_label=label)

    return spin_polarized, dipole_corrected, vdw_corrected


def read_relaxed_site_fdf(site_dir):
    """Returns the RELAXED FdfStructure for `site_dir` -- the actual final
    geometry SIESTA converged to (read from its finished 'siesta.XV'), not
    the pre-relaxation initial guess stb-adsorb wrote to 'structure.fdf'.
    Returns None if no '.XV' is present yet (SIESTA hasn't been run in this
    folder, or hasn't reached its first written geometry).

    Thin wrapper around core/structure_io.py::read_relaxed_or_input --
    extracted there once stb-neb's own directory-input support became a
    third consumer of "prefer a finished .XV over structure.fdf" (same
    extract-on-further-use policy as the rest of core/). BSSE only ever
    wants the genuinely relaxed geometry (unlike stb-neb, which falls back
    to the unrelaxed guess with a warning), so the "not relaxed yet" case
    is folded into a plain None here instead of the shared function's
    (structure, used_relaxed) tuple. Raises ValueError if the '.XV' atom
    count doesn't match 'structure.fdf' (a mismatched/stale folder), same
    as before -- reported and skipped by the caller instead of silently
    misreading garbage.
    """
    relaxed, used_relaxed = structure_io.read_relaxed_or_input(site_dir)
    return relaxed if used_relaxed else None


def read_original_calc_text(site_calc_fdf_path):
    """Strips the '%include config_extra.fdf' sidecar line
    structure_io.prepend_include added when stb-adsorb first wrote this
    site's own calc.fdf, recovering the original --calc template text --
    needed here so write_bsse_folders can prepend its OWN (different)
    config_extra.fdf (BSSE_SINGLE_POINT_BLOCK instead of FIXED_CELL_BLOCK)
    without doubling the include line. Thin wrapper around
    core.bsse.strip_config_extra_include (shared with
    stackingfault_bsse.py) that also does the file read.
    """
    with open(site_calc_fdf_path) as f:
        text = f.read()
    return strip_config_extra_include(text, CONFIG_EXTRA_FILE)


def main():
    parser = argparse.ArgumentParser(
        description=f"""{color_text("Stage 2 of the Adsorption workflow: generates the BSSE "
        "(counterpoise) ghost-fragment folders at each site's RELAXED geometry, once stb-adsorb's "
        "own sites/site_*/ have finished running in SIESTA.", 'bold')}""",
        formatter_class=argparse.RawTextHelpFormatter,
        epilog="Usage examples:\n"
               "  %(prog)s\n"
               "  %(prog)s --dir adsorption_run --file calc.out\n"
    )

    parser.add_argument("--dir", type=str, default="adsorption_run",
                         help="Root directory containing 'clean_slab/' and 'sites/' (default: "
                              "adsorption_run -- stb-adsorb's own default --output-dir).")
    parser.add_argument("--file", type=str, default="calc.out",
                         help="SIESTA output filename inside each site folder (default: calc.out).")
    parser.add_argument("--force-tolerance", type=float, default=0.05,
                         help="Residual atomic force in eV/Ang (default: 0.05) above which a "
                              "site's relaxation is flagged as possibly incomplete -- advisory "
                              "only, never blocks BSSE folder generation.")
    parser.add_argument("--save-report", action="store_true",
                         help=f"Also persist the report to {REPORT_FILE}. Off by default.")
    parser.add_argument("-v", "--version", action="version", version=f"stb-adsorbBsse {VERSION}")
    parser.add_argument("--no-intro", dest="intro", action="store_false", help="Do not show the introduction")

    args = parser.parse_args()

    if args.intro:
        show_intro([
            "Siesta ToolBox Suite",
            "A comprehensive toolkit for SIESTA DFT simulations",
            f"Version {VERSION} | University of Brasilia - 2026",
            "Developed by Dr. Carlos M. O. Bastos"
        ])

    library_warnings = []  # collected via capture_library_noise, reported in [4]

    sites_root = os.path.join(args.dir, "sites")
    bsse_root = os.path.join(args.dir, "bsse")
    clean_slab_fdf_path = os.path.join(args.dir, "clean_slab", "structure.fdf")

    if not os.path.isdir(sites_root):
        print(color_text(f"[ERROR] '{sites_root}' not found. Did you run stb-adsorb?", 'red'))
        sys.exit(1)
    if not os.path.isfile(clean_slab_fdf_path):
        print(color_text(f"[ERROR] '{clean_slab_fdf_path}' not found. Did you run stb-adsorb?", 'red'))
        sys.exit(1)

    report_path = REPORT_FILE if args.save_report else None
    f_out = open(report_path, "w") if report_path else None

    print_dual(color_text("===== ADSORPTION BSSE (POST-RELAXATION) REPORT =====", 'magenta'), f_out)

    # --- [0] RUN METADATA. ---
    print_section("[0] RUN METADATA", f_out)
    print_dual(f"  Directory       : {args.dir}", f_out)
    print_dual(f"  Output file     : {args.file}", f_out)
    print_dual(f"  Save report     : {'yes -> ' + report_path if args.save_report else 'no'}", f_out)
    print_dual(color_text(
        "\n  [WHY THIS STAGE EXISTS] A Boys-Bernardi counterpoise (BSSE) correction is only "
        "valid if every fragment is evaluated at the SAME geometry as the real, relaxed site -- "
        "not the pre-relaxation initial guess. That relaxed geometry only exists once SIESTA has "
        "actually finished relaxing 'sites/site_*/', so BSSE folders can't be written at prep "
        "time (stb-adsorb) any more; this stage reads each site's own finished 'siesta.XV' "
        "instead. Full explanation: examples/4.8-adsorption/README.md.", 'cyan'), f_out)

    n_substrate = len(structure_io.read_fdf(clean_slab_fdf_path).atoms)

    site_table = read_site_table(sites_root)
    site_dirs = sorted(
        d for d in os.listdir(sites_root)
        if os.path.isdir(os.path.join(sites_root, d)) and d.startswith("site_")
    )
    if not site_dirs:
        print_dual(color_text(f"[ERROR] No 'site_*' folders found in '{sites_root}'.", 'red'), f_out)
        if f_out:
            f_out.close()
        sys.exit(1)

    # --- [1] SITE SCAN: which sites are relaxed and ready for BSSE. ---
    print_section("[1] SITE SCAN", f_out)
    ready, not_relaxed, mismatched = [], [], []
    rows = []
    for label in site_dirs:
        site_dir = os.path.join(sites_root, label)
        try:
            with capture_library_noise(library_warnings, f"sisl (site {label} .XV read)"):
                relaxed_fdf = read_relaxed_site_fdf(site_dir)
        except ValueError as e:
            mismatched.append(label)
            rows.append(([label, "SKIP (atom count mismatch)"], 'red'))
            print_dual(color_text(f"  [ERROR] {label}: {e}", 'red'), f_out)
            continue
        if relaxed_fdf is None:
            not_relaxed.append(label)
            rows.append(([label, "SKIP (no .XV yet -- not relaxed)"], 'yellow'))
            continue
        ready.append((label, site_dir, relaxed_fdf))
        rows.append(([label, "ready"], 'green'))
        out_path = os.path.join(site_dir, args.file)
        report_quality_diagnostics(label, out_path, args.force_tolerance, f_out)

    print_table(["Site", "Status"], rows, f_out)
    print_dual(f"\n  Site folders found : {len(site_dirs)}", f_out)
    print_dual(f"  Ready (relaxed)    : {len(ready)}", f_out)
    print_dual(f"  Not yet relaxed    : {len(not_relaxed)}"
                + (f" ({', '.join(not_relaxed)})" if not_relaxed else ""), f_out)
    if mismatched:
        print_dual(color_text(
            f"  Mismatched/stale   : {len(mismatched)} ({', '.join(mismatched)})", 'red'), f_out)

    if not ready:
        print_dual(color_text(
            "\n[ERROR] No site is ready yet -- run SIESTA in 'sites/site_*/' first.", 'red'), f_out)
        if f_out:
            f_out.close()
        sys.exit(1)

    # --- [2] WRITING BSSE FOLDERS: ghost-fragment pair per ready site, at
    # its own relaxed geometry. ---
    print_section("[2] WRITING BSSE FOLDERS", f_out)
    written = []
    for label, site_dir, relaxed_fdf in ready:
        calc_text = read_original_calc_text(os.path.join(site_dir, "calc.fdf"))
        bsse_dir = os.path.join(bsse_root, label)
        # The site's own folder already has every real pseudopotential file
        # this site needs (copied there by stb-adsorb) -- reused directly
        # as the pseudopotential source for the ghost variants too, so this
        # stage never needs its own -p/--pseudo-dir flag.
        spin_polarized, dipole_corrected, vdw_corrected = write_bsse_folders(
            bsse_dir, relaxed_fdf, n_substrate, calc_text, site_dir)
        written.append(label)
        print_dual(f"  {color_text('[OK]', 'green')} {bsse_dir}/bsse_slab/, {bsse_dir}/bsse_adsorbate/ "
                    f"(relaxed geometry, spin: {'yes' if spin_polarized else 'no'}, "
                    f"dipole: {'yes' if dipole_corrected else 'no'}, "
                    f"vdw: {'yes' if vdw_corrected else 'no'} -- inherited from the site)", f_out)

    # --- [3] SUMMARY & NEXT STEPS. ---
    print_section("[3] SUMMARY & NEXT STEPS", f_out)
    print_dual(f"  BSSE folder pair(s) written : {len(written)} of {len(site_dirs)} site(s)", f_out)
    if not_relaxed or mismatched:
        print_dual(color_text(
            f"  {len(not_relaxed) + len(mismatched)} site(s) skipped -- re-run stb-adsorbBsse "
            "once they've finished relaxing (already-written folders are left untouched).",
            'yellow'), f_out)
    print_dual(f"  Run SIESTA in every 'bsse/site_*/bsse_slab/' and 'bsse/site_*/bsse_adsorbate/' "
                "folder above, then use stb-adsorbAnalysis for the BSSE-corrected adsorption "
                "energy.", f_out)
    if report_path:
        print_dual(f"  Report: {report_path}", f_out)

    # --- [4] LIBRARY WARNINGS: always last. ---
    print_section("[4] LIBRARY WARNINGS", f_out)
    if library_warnings:
        print_dual(color_text(
            "Messages emitted by external libraries (sisl) during this run -- collected here "
            "instead of interleaved with the report above; harmless in almost every case, but "
            "worth a look if a section above looks suspicious.", 'cyan'), f_out)
        for entry in library_warnings:
            print_dual(entry, f_out)
    else:
        print_dual("No library warnings.", f_out)

    if f_out:
        f_out.close()

    print(f"\n{color_text('Success:', 'green')} {len(written)} of {len(site_dirs)} site(s) got "
          "BSSE folders written at their relaxed geometry.")
    if report_path:
        print(f"Full report: {report_path}")


if __name__ == "__main__":
    main()
