#!/usr/bin/env python3

#################################################
#     Siesta Tool Box - Suite                   #
# Developed by Dr. Carlos M. O. Bastos          #
#      bastoscmo.github.io                      #
#################################################

"""Stage 1 of the Charge Density Difference workflow: given a COMBINED
structure (a bilayer, a molecule on a slab, or any other N-fragment
system, N >= 2) and a fragment split, writes N+1 SIESTA input folders --
one 'combined/' folder with every atom real (no ghosting, the full
system as given), and one 'fragment1/', 'fragment2/', ... folder per
fragment (or 'slab/'+'adsorbate/' when reusing an stb-adsorb site's own
fragment_manifest.json). All N+1 folders share the identical cell/
MeshCutoff/level of theory, forced by this tool itself -- the combined
folder is no longer something the user has to configure/maintain
themselves in parallel, which used to be the single most dangerous
silent failure mode of this tool (a mismatched MeshCutoff between the
combined system's own calculation and the fragments').

Every fragment folder gets its own REAL atoms plus every OTHER fragment's
atoms as ghost species (see core/bsse.py::make_ghost_variant) --
unconditional, no opt-out -- so every calculation that feeds Delta rho =
rho_combined - sum(rho_fragment_i) shares the exact same basis set (same
number of atomic orbitals). Without this, a plain "real atoms only"
fragment has fewer basis functions than the combined system, and that
basis-set difference contaminates the density difference the same way it
would contaminate a counterpoise-uncorrected interaction energy. The
combined folder itself never needs ghosting -- it already has every atom.

Every one of the N+1 folders also gets, unconditionally, via
config_extra.fdf (never edited into the user's own --calc template): a
fixed cell (not relaxed), a single-point evaluation (no relaxation of
cell OR positions), the SAME explicit MeshCutoff on all of them (so every
.RHO ends up on an identical real-space grid), and SaveRho true (so
SIESTA actually writes a .RHO). See core/adsorption_sites.py's
FIXED_CELL_BLOCK/SINGLE_POINT_BLOCK/SPIN_POLARIZED_BLOCK/
DIPOLE_CORRECTION_BLOCK/VDW_CORRECTION_BLOCK for the reused blocks.
"""

VERSION = "1.1.0"

import os
import sys
import json
import argparse
import tempfile
import subprocess
from datetime import datetime

import numpy as np
import ase.io as ase_io
from pymatgen.io.ase import AseAtomsAdaptor

from stb.core import structure_io
from stb.core import adsorption_sites
from stb.core.bsse import make_ghost_variant
from stb.core.cli import color_text, show_intro, print_dual, print_section, print_table
from stb.core.pseudopotentials import copy_pseudo, resolve_pseudo_source, BANKS
from stb.core import citations

DEFAULT_MESH_CUTOFF_RY = 400.0
# How "hollow" a ghost atom looks in --view: the fraction of its circle
# ase-gui fills with the real element's color, via the same partial
# -occupancy convention ase.gui.view.View.draw() already uses for
# disordered crystallographic sites (an occupancy summing to < 1.0 draws a
# mostly-white circle plus a small colored wedge) -- see
# structure_to_view_atoms's own docstring for why this, not the dummy 'X'
# element, is used to mark a ghost atom.
GHOST_OCCUPANCY_FRACTION = 0.15

REPORT_FILE = "chargediff_prep_report.txt"
BIB_FILE = "references.bib"
CONFIG_EXTRA_FILE = "config_extra.fdf"
CHARGEDIFF_MANIFEST_FILE = "chargediff_manifest.json"

MESH_CUTOFF_BLOCK_TMPL = (
    "# Auto-generated by stb-chargediffPrep -- forces the same real-space grid\n"
    "# resolution as the combined system, so every fragment's .RHO ends up on\n"
    "# an identical grid and can be subtracted point-by-point (see\n"
    "# stb-chargediffPrep's own module docstring for why this is mandatory).\n"
    "MeshCutoff          {value}\n"
)
SAVE_RHO_BLOCK = (
    "# Auto-generated by stb-chargediffPrep -- SIESTA must write the .RHO file\n"
    "# for stb-chargediffAnalysis to read.\n"
    "SaveRho             true\n"
)


def read_combined_theory_flags(combined_dir):
    """Returns (spin_polarized, dipole_corrected, vdw_corrected) read from
    the combined system's own config_extra.fdf under `combined_dir`, or
    (False, False, False) if it has none -- same "duplicated per workflow,
    read the sidecar rather than re-deriving from CLI flags" convention as
    adsorb_bsse.py's read_site_theory_flags/her_refs.py/oer_refs.py.
    """
    path = os.path.join(combined_dir, CONFIG_EXTRA_FILE)
    if not os.path.isfile(path):
        return False, False, False
    with open(path) as f:
        text = f.read()
    return "Spin" in text, "Slab.DipoleCorrection" in text, "DFTD3" in text


def label_fragments_n(structure, groups, suffixes):
    """Generalizes core/adsorption_sites.py::label_fragments from a single
    2-way index cut to an arbitrary list of `groups` (each a list of atom
    indices into structure.atoms, in file order -- contiguous for a
    --fragment-sizes split, arbitrary for a --fragment-species split).
    Every atom gets its label suffixed by `suffixes[i]` for whichever
    group it belongs to. Kept local to this tool (not core/) since it's
    the sole consumer today of an N-way split -- extract-on-second-use,
    same policy as the rest of the project (compare her_refs.py's own
    local index-range make_ghost_variant).
    """
    label_for_index = {}
    for group, suffix in zip(groups, suffixes):
        for i in group:
            label_for_index[i] = suffix

    species_meta = dict(structure.species_meta)
    new_atoms = []
    for i, (symbol, pos) in enumerate(structure.atoms):
        label = f"{symbol}{label_for_index[i]}"
        if label not in species_meta:
            used_ids = {str(info["id"]) for info in species_meta.values()}
            next_id = 1
            while str(next_id) in used_ids:
                next_id += 1
            species_meta[label] = {"id": str(next_id), "Z": species_meta[symbol]["Z"]}
        new_atoms.append((label, pos))

    species = list(dict.fromkeys(sym for sym, _ in new_atoms))
    return structure_io.FdfStructure(
        lattice=structure.lattice,
        lattice_constant=structure.lattice_constant,
        species=species,
        species_meta=species_meta,
        atoms=new_atoms,
        coord_format=structure.coord_format,
        raw_lines=[],
    )


def parse_fragment_sizes(spec, n_atoms_total):
    """Parses '--fragment-sizes "n1,n2,...,nK"' into a list of K index
    groups, contiguous in file order (group 0 = first n1 atoms, group 1 =
    next n2, ...). Raises ValueError with a human-readable reason on a
    malformed spec, fewer than 2 groups, a non-positive size, or a sum
    that doesn't exactly match the structure's own atom count -- no
    guessing, matching this suite's general error-handling convention.
    """
    try:
        sizes = [int(x) for x in spec.split(",")]
    except ValueError:
        raise ValueError(f"--fragment-sizes must be a comma-separated list of integers, got: {spec!r}")
    if len(sizes) < 2:
        raise ValueError("--fragment-sizes needs at least 2 fragments (K >= 2), separated by commas.")
    if any(size <= 0 for size in sizes):
        raise ValueError("--fragment-sizes: every fragment size must be a positive integer.")
    if sum(sizes) != n_atoms_total:
        raise ValueError(
            f"--fragment-sizes sums to {sum(sizes)} atom(s) but the combined structure has "
            f"{n_atoms_total} -- the sizes must add up exactly (no atom left over/missing)."
        )
    groups = []
    start = 0
    for size in sizes:
        groups.append(list(range(start, start + size)))
        start += size
    return groups


def parse_fragment_species(spec, structure):
    """Parses '--fragment-species "El_a,El_b;El_c;..."' (';'-separated
    groups, ','-separated element symbols within a group) into a list of
    index groups, by REAL element (structure_io.real_element, robust to
    any label suffix already on the combined structure) rather than atom
    order -- works regardless of where each fragment's atoms sit in the
    file, unlike --fragment-sizes. Raises ValueError if fewer than 2
    groups are given, a species is assigned to more than one group, a
    species present in the structure is missing from every group, or a
    named species isn't present in the structure at all -- this mode
    cannot disambiguate two fragments sharing an element (see this tool's
    --help for the documented limitation), so an unambiguous full
    assignment is required, never guessed.
    """
    groups_species = [
        [sym.strip() for sym in group.split(",") if sym.strip()]
        for group in spec.split(";")
    ]
    groups_species = [g for g in groups_species if g]
    if len(groups_species) < 2:
        raise ValueError("--fragment-species needs at least 2 fragments (groups separated by ';').")

    real_symbol_by_index = [
        structure_io.real_element(symbol, structure.species_meta) for symbol, _ in structure.atoms
    ]
    present_species = set(real_symbol_by_index)

    seen = set()
    for group_species in groups_species:
        for sp in group_species:
            if sp in seen:
                raise ValueError(f"--fragment-species: species '{sp}' appears in more than one group.")
            seen.add(sp)

    unknown = seen - present_species
    if unknown:
        raise ValueError(
            f"--fragment-species: species not present in the combined structure: "
            f"{', '.join(sorted(unknown))}."
        )
    missing = present_species - seen
    if missing:
        raise ValueError(
            f"--fragment-species: the combined structure has species not assigned to any "
            f"fragment: {', '.join(sorted(missing))}. Every species must be assigned to exactly "
            "one group -- if two fragments physically share a species, use --fragment-sizes or "
            "--fragment-manifest instead (see --help)."
        )

    groups = [
        [i for i, sym in enumerate(real_symbol_by_index) if sym in group_species]
        for group_species in groups_species
    ]
    empty = [i + 1 for i, g in enumerate(groups) if not g]
    if empty:
        raise ValueError(f"--fragment-species: fragment(s) {empty} ended up with no atoms.")
    return groups


def formula_string(fdf_structure):
    """Human-readable formula (e.g. 'B16C32N16'), aggregating every species
    LABEL back to its real element (structure_io.real_element, robust to
    any fragment/ghost suffix already present) -- used for the verbose
    combined-structure/fragment reporting below.
    """
    counts = structure_io.atom_counts(fdf_structure)
    element_counts = {}
    for label, n in counts.items():
        if n <= 0:
            continue
        el = structure_io.real_element(label, fdf_structure.species_meta)
        element_counts[el] = element_counts.get(el, 0) + n
    return "".join(f"{el}{n if n > 1 else ''}" for el, n in sorted(element_counts.items()))


def species_breakdown(fdf_structure, labels):
    """Returns a sorted '<real_element> x<count> (label)' list for the given
    species `labels` of `fdf_structure` -- the per-fragment real/ghosted
    atom breakdown used for the verbose [3] FRAGMENT DEFINITION report."""
    counts = structure_io.atom_counts(fdf_structure)
    rows = []
    for label in sorted(labels):
        n = counts.get(label, 0)
        if n <= 0:
            continue
        el = structure_io.real_element(label, fdf_structure.species_meta)
        rows.append(f"{el} x{n} ({label})")
    return rows


def structure_to_view_atoms(fdf_structure, hollow_fraction=GHOST_OCCUPANCY_FRACTION):
    """Converts a (possibly ghosted) FdfStructure into a plain ASE Atoms
    object for --view, via structure_io.strip_fragment_labels (maps every
    label -- real or '_ghost' -- back to its real element by Z, preserving
    atom order) -- same conversion as before, but every atom whose
    ORIGINAL label ended in '_ghost' is additionally marked to render as a
    mostly-hollow circle in ase-gui.

    There is no public per-atom radius/fill override in ase.visualize.view()
    (it serializes Atoms to a trajectory file and opens ase-gui in a
    separate subprocess -- confirmed by reading ase/visualize/viewers.py;
    no styling hook survives that path), and the obvious alternative (the
    dummy 'X' element, Z=0) would replace the ghost's real element/size/
    color entirely with a small generic red marker. Instead, this reuses
    ase-gui's own NATIVE partial-occupancy convention (normally meant for
    disordered crystallographic sites, e.g. a fractional-occupancy CIF):
    an atom whose occupancies sum to < 1.0 is drawn as a mostly-white/empty
    circle with a small colored wedge, instead of the default fully
    solid-filled circle.

    ASE itself is inconsistent about which per-atom key this convention is
    keyed by, confirmed by reading both call sites: the INTERACTIVE Tk
    viewer (ase/gui/view.py's View.draw(), what ase.visualize.view() opens
    and what this suite's --view actually uses) reads
    `atoms.arrays['spacegroup_kinds']`, while ASE's own static PNG/EPS/POV
    writer (ase/io/utils.py's make_patch_list, used by e.g.
    `ase.io.write(path, atoms, format='png')`) reads `atoms.get_tags()`
    instead for the exact same `atoms.info['occupancy']` lookup -- so both
    are set here to render correctly regardless of which ASE code path
    ends up handling a given view. A real atom (occupancy 1.0, the default
    when its key is simply absent) renders exactly as before, fully solid
    -- so this is safe to apply uniformly to the combined structure too
    (no atom there ends in '_ghost', so every atom stays fully solid,
    unaffected).
    """
    is_ghost = [label.endswith("_ghost") for label, _ in fdf_structure.atoms]
    stripped = structure_io.strip_fragment_labels(fdf_structure)
    pmg_structure = structure_io.to_pymatgen(stripped)
    atoms = AseAtomsAdaptor.get_atoms(pmg_structure)

    if any(is_ghost):
        symbols = atoms.get_chemical_symbols()
        kinds = np.arange(len(atoms))
        atoms.arrays['spacegroup_kinds'] = kinds
        atoms.set_tags(kinds)
        atoms.info['occupancy'] = {
            str(i): {symbols[i]: (hollow_fraction if ghost else 1.0)}
            for i, ghost in enumerate(is_ghost)
        }
    return atoms


def view_fragments_animated(frames):
    """Opens ONE ase-gui window showing `frames` (a list of ASE Atoms,
    combined structure first, then each fragment) as sequential, navigable
    movie frames, with any ghost atom marked by structure_to_view_atoms
    rendering as a mostly-hollow circle.

    Deliberately bypasses core/ase_view.py's shared view_structure_interactive
    (ase.visualize.view()'s default 'ase' backend) -- confirmed by direct
    testing that this backend always pipes the structure to the ase-gui
    subprocess via ASE's own .traj (ULM binary) format, and THAT format
    silently drops any custom entry in atoms.arrays (e.g.
    'spacegroup_kinds') on the read-back side, even though it faithfully
    preserves atoms.info (e.g. 'occupancy'). Since ase-gui's own hollow
    -circle rendering (ase/gui/view.py's View.draw()) looks up
    atoms.arrays['spacegroup_kinds'] first and falls back to a normal,
    fully-solid circle on a bare KeyError, every ghost atom was silently
    rendered identically to a real one -- the exact "ghosts aren't
    differentiated" bug this works around, root-caused by writing each
    frame to a temporary CIF file instead (confirmed directly:
    'spacegroup_kinds'/'occupancy' round-trip correctly through CIF --
    unsurprising, since that's the actual format this ase-gui convention
    was designed for, crystallographic disorder) and launching 'ase gui'
    directly on that list of file paths -- ase-gui already treats multiple
    file arguments as sequential frames of one session, so no other
    change is needed for the "combined, then every fragment" movie.
    """
    with tempfile.TemporaryDirectory(prefix="stb-chargediff-view-") as tmpdir:
        paths = []
        for i, atoms in enumerate(frames):
            path = os.path.join(tmpdir, f"frame_{i:02d}.cif")
            ase_io.write(path, atoms)
            paths.append(path)
        try:
            subprocess.run([sys.executable, "-m", "ase", "gui"] + paths, check=True)
        except FileNotFoundError:
            print(color_text("[FAIL] Could not launch 'ase gui' -- is ASE installed?", 'red'))
        except subprocess.CalledProcessError as e:
            print(color_text(f"[FAIL] ase gui exited with an error: {e}", 'red'))


def write_chargediff_manifest(out_dir, fdf_structure, folder_names, suffixes, combined_folder="combined"):
    """Writes '<out_dir>/chargediff_manifest.json': the single source of
    truth stb-chargediffAnalysis (Stage 2) reads to find out, from just
    `--dir <out_dir>`, which subfolder is the combined system and which
    are the fragments -- no labels/paths need to be typed by hand. Always
    written (both --fragment-manifest/--fragment-sizes/--fragment-species
    modes), unlike core/adsorption_sites.py's own fragment_manifest.json
    (hardcoded to exactly 2 fragments: slab/adsorbate, and not written by
    this tool at all -- that one is stb-adsorb's own, only ever READ here
    via --fragment-manifest).

    `combined_folder`/`folder_names` are the literal subfolder names
    Stage 1 just wrote (e.g. 'combined' + ['fragment1', 'fragment2'], or
    'combined' + ['slab', 'adsorbate']); `suffixes` are the matching
    species-label suffixes on `fdf_structure` (the labeled, pre-ghosting
    structure) used to compute each fragment's own species/atom-count
    breakdown, purely for a human-readable record -- Stage 2 itself only
    needs 'combined_folder'/'fragment_folders' to locate each folder's own
    '*.RHO' (and the combined folder's own '*.XV'/structure.fdf for
    --cube), not this species breakdown.
    """
    counts = structure_io.atom_counts(fdf_structure)
    fragments = []
    for name, suffix in zip(folder_names, suffixes):
        species_labels = {}
        for label in fdf_structure.species:
            if label.endswith(suffix):
                info = fdf_structure.species_meta[label]
                species_labels[label] = {"id": info["id"], "Z": info["Z"], "count": counts.get(label, 0)}
        fragments.append({
            "folder": name,
            "label_suffix": suffix,
            "species_labels": species_labels,
            "n_atoms": sum(v["count"] for v in species_labels.values()),
        })
    manifest = {
        "schema": "chargediff_manifest_v2",
        "combined_folder": combined_folder,
        "fragment_folders": list(folder_names),
        "fragments": fragments,
    }
    with open(os.path.join(out_dir, CHARGEDIFF_MANIFEST_FILE), "w") as f:
        json.dump(manifest, f, indent=2)


def write_fragment_folder(out_dir, fdf_structure, calc_text, pp_path, mesh_cutoff_value,
                          spin_polarized, dipole_corrected, vdw_corrected, strip_ghost_only):
    """Writes one fragment's structure.fdf + config_extra.fdf + calc.fdf +
    copied pseudopotentials. `fdf_structure` must already be the fragment's
    REAL atoms plus every other fragment's atoms as ghosts (see
    make_ghost_variant, applied by the caller). config_extra.fdf always
    (unconditionally) forces the fixed cell, a single-point evaluation (no
    relaxation of cell OR positions -- adsorption_sites.SINGLE_POINT_BLOCK,
    same constant reused by neb.py/stackingfault.py/her_refs.py/oer_refs.py),
    the resolved MeshCutoff, and SaveRho true; the Spin/dipole/vdW blocks
    are added only when the combined system's own level of theory
    (inherited or --force-*-overridden) calls for them.

    `strip_ghost_only` controls how each present species label is resolved
    back to a real pseudopotential file under `pp_path`: True (reusing an
    stb-adsorb fragment_manifest.json, no explicit --pseudo-dir override)
    means `pp_path` is that site's own directory, which already holds
    pseudopotentials named after its own per-fragment labels (e.g.
    'C_slab.psml') -- only the literal '_ghost' suffix needs stripping,
    same convention as adsorb_bsse.py's own write_bsse_folders. False (a
    --fragment-sizes/--fragment-species split, or any case with an
    explicit --pseudo-dir/bank) means `pp_path` holds bare-element-named
    pseudopotentials (e.g. 'C.psml') -- the full real element must be
    recovered via structure_io.real_element (robust to any stack of
    suffixes).

    Returns a dict of every file actually written/attempted, for the
    caller's own verbose report: {'structure', 'config_extra', 'calc',
    'pseudo_labels'} (the last being every species label a pseudopotential
    copy was attempted for -- copy_pseudo itself warns, without raising,
    on a genuinely missing source file).
    """
    os.makedirs(out_dir, exist_ok=True)
    structure_path = os.path.join(out_dir, "structure.fdf")
    structure_io.write_fdf(fdf_structure, structure_path)

    config_extra = (
        adsorption_sites.FIXED_CELL_BLOCK
        + adsorption_sites.SINGLE_POINT_BLOCK
        + MESH_CUTOFF_BLOCK_TMPL.format(value=mesh_cutoff_value)
        + SAVE_RHO_BLOCK
    )
    if spin_polarized:
        config_extra += adsorption_sites.SPIN_POLARIZED_BLOCK
    if dipole_corrected:
        config_extra += adsorption_sites.DIPOLE_CORRECTION_BLOCK
    if vdw_corrected:
        config_extra += adsorption_sites.VDW_CORRECTION_BLOCK
    config_extra_path = os.path.join(out_dir, CONFIG_EXTRA_FILE)
    with open(config_extra_path, "w") as f:
        f.write(config_extra)

    calc_path = os.path.join(out_dir, "calc.fdf")
    with open(calc_path, "w") as f:
        f.write(structure_io.prepend_include(calc_text, CONFIG_EXTRA_FILE))

    pseudo_labels = []
    for label in fdf_structure.species:
        if strip_ghost_only:
            source_label = label[:-len("_ghost")] if label.endswith("_ghost") else label
        else:
            source_label = structure_io.real_element(label, fdf_structure.species_meta)
        copy_pseudo(pp_path, source_label, out_dir, dest_label=label)
        pseudo_labels.append(label)

    return {
        "structure": structure_path,
        "config_extra": config_extra_path,
        "calc": calc_path,
        "pseudo_labels": pseudo_labels,
    }


def main():
    parser = argparse.ArgumentParser(
        description=f"""{color_text("Stage 1 of the Charge Density Difference workflow: writes a "
        "'combined/' SIESTA input folder (every atom real, no ghosting) plus one fragment folder "
        "per fragment of an N-fragment system (bilayer, molecule-on-slab, etc.) -- ALL of them "
        "sharing the identical cell/mesh/level of theory, forced by this tool itself. Every "
        "fragment folder ALWAYS includes every other fragment as ghost atoms (no opt-out) so "
        "every calculation shares the same basis set.", 'bold')}""",
        formatter_class=argparse.RawTextHelpFormatter,
        epilog="Usage examples:\n"
               "  %(prog)s --fragment-sizes \"12,12\"\n"
               "  %(prog)s --structure bilayer/structure.fdf --fragment-species \"C;B,N\" -p dojo\n"
               "  %(prog)s --structure adsorption_run/sites/site_1/structure.fdf "
               "--fragment-manifest adsorption_run/sites/site_1/fragment_manifest.json\n"
    )

    parser.add_argument("-s", "--structure", default="structure.fdf",
                         help="Path to the combined system's own .fdf structure file -- taken "
                              "directly as the REAL, authoritative geometry to be split into "
                              "fragments (structure_io.read_fdf, no directory scanning, no "
                              "automatic preference for a relaxed '*.XV' that might sit alongside "
                              "it -- point this at whichever file you consider the real geometry, "
                              "e.g. a fresh structure.fdf written from a converged '*.XV' via "
                              "stb-translate). Default: 'structure.fdf'.")

    frag_group = parser.add_mutually_exclusive_group(required=True)
    frag_group.add_argument("--fragment-manifest", metavar="PATH",
                             help="Reuse an existing fragment_manifest.json (written by stb-adsorb) "
                                  "to recover its slab/adsorbate split -- exactly 2 fragments. Pass "
                                  "an empty value ('') to default to 'fragment_manifest.json' next "
                                  "to --structure itself.")
    frag_group.add_argument("--fragment-sizes", metavar="N1,N2,...,NK",
                             help="General split by ATOM COUNT: comma-separated atom counts, in "
                                  "the order fragments appear in the structure file (fragment 1 = "
                                  "first N1 atoms, fragment 2 = next N2, ...). Must sum to the "
                                  "combined structure's total atom count. K >= 2.")
    frag_group.add_argument("--fragment-species", metavar="El_a,El_b;El_c;...",
                             help="General split by CHEMICAL SPECIES, independent of atom order: "
                                  "';'-separated groups, each a comma-separated list of element "
                                  "symbols belonging to that fragment (e.g. 'C;B,N' for a "
                                  "graphene/h-BN heterostructure). Every species present in the "
                                  "structure must appear in exactly one group. LIMITATION: cannot "
                                  "be used when two fragments physically share a species (e.g. "
                                  "MoS2 on WS2, sulfur in both layers) -- use --fragment-sizes or "
                                  "--fragment-manifest instead in that case.")

    parser.add_argument("--calc", default="calc.fdf",
                         help="SIESTA input template (.fdf) used for every fragment folder -- same "
                              "basis/SCF/k-grid as the combined system (default: 'calc.fdf').")
    parser.add_argument("--mesh-cutoff", type=float, default=DEFAULT_MESH_CUTOFF_RY, metavar="RY",
                         help=f"Explicit MeshCutoff (Ry) to force in every fragment folder -- the "
                              f"SAME value on all of them, never auto-detected from --calc/the "
                              f"combined system's own calc.fdf (a per-run SIESTA default can "
                              f"silently differ between calculations with different atoms/"
                              f"pseudopotentials, which would corrupt the point-by-point "
                              f"subtraction). Default: {DEFAULT_MESH_CUTOFF_RY:g} Ry -- raise it "
                              "for a finer grid (recommended for a production CDD map) or type a "
                              "different value here.")
    parser.add_argument("-p", "--pseudo-dir", type=str, default="",
                         help=f"Pseudopotentials source: a bundled bank ({', '.join(BANKS)}) or a "
                              "folder path (same convention as stb-adsorb/stb-her/stb-hubbardu). "
                              "Default: reuse the directory --structure lives in, which already "
                              "has every pseudopotential the combined calculation needed.")

    parser.add_argument("--force-spin", dest="force_spin", action="store_true", default=None,
                         help="Force spin-polarized SCF in every fragment folder (default: "
                              "inherited from the combined system's own config_extra.fdf, if any).")
    parser.add_argument("--no-force-spin", dest="force_spin", action="store_false",
                         help="Force spin-restricted SCF, overriding the combined system's own "
                              "setting.")
    parser.add_argument("--force-dipole", dest="force_dipole", action="store_true", default=None,
                         help="Force the slab dipole correction (default: inherited from the "
                              "combined system's own config_extra.fdf, if any).")
    parser.add_argument("--no-force-dipole", dest="force_dipole", action="store_false",
                         help="Disable the slab dipole correction, overriding the combined "
                              "system's own setting.")
    parser.add_argument("--force-vdw", dest="force_vdw", action="store_true", default=None,
                         help="Force the DFT-D3 dispersion correction (default: inherited from "
                              "the combined system's own config_extra.fdf, if any).")
    parser.add_argument("--no-force-vdw", dest="force_vdw", action="store_false",
                         help="Disable the DFT-D3 dispersion correction, overriding the combined "
                              "system's own setting.")

    parser.add_argument("--output-dir", default="chargediff_run",
                         help="Root directory to write the fragment folders into (default: "
                              "chargediff_run).")
    parser.add_argument("--view", action="store_true",
                         help="After writing them, open ONE ASE interactive 3D viewer window with "
                              "the combined structure followed by every fragment as navigable "
                              "movie frames -- ghost atoms render as mostly-hollow circles (see "
                              "structure_to_view_atoms's docstring). Needs a display. Off by "
                              "default.")
    parser.add_argument("--save-report", action="store_true",
                         help=f"Also persist the full run report to {REPORT_FILE}. Off by default.")
    parser.add_argument("--no-intro", dest="intro", action="store_false", help="Do not show the introduction")
    parser.add_argument("-v", "--version", action="version", version=f"stb-chargediffPrep {VERSION}")

    args = parser.parse_args()

    if args.intro:
        show_intro([
            "Siesta ToolBox Suite - Charge Density Difference (Prep)",
            "Writes one ghosted SIESTA fragment folder per N-fragment split",
            f"Version {VERSION} | University of Brasilia - 2026",
            "Developed by Dr. Carlos M. O. Bastos"
        ])

    os.makedirs(args.output_dir, exist_ok=True)
    report_path = os.path.join(args.output_dir, REPORT_FILE) if args.save_report else None
    f_out = open(report_path, "w") if report_path else None

    print_dual(color_text("===== CHARGE DENSITY DIFFERENCE -- STAGE 1: PREP =====", 'magenta'), f_out)

    print_section("[0] RUN METADATA", f_out)
    print_dual(f"  Structure file  : {args.structure}", f_out)
    print_dual(f"  Calc template   : {args.calc}", f_out)
    print_dual(f"  Output dir      : {args.output_dir}", f_out)
    print_dual(f"  View fragments  : {'yes (ASE)' if args.view else 'no'}", f_out)

    if not os.path.exists(args.calc):
        print_dual(color_text(f"[ERROR] Calc file '{args.calc}' not found.", 'red'), f_out)
        if f_out:
            f_out.close()
        sys.exit(1)
    with open(args.calc) as f:
        calc_text = f.read()
    calc_text, _include_status, _old_include_name = structure_io.fix_structure_include(calc_text)

    # The directory --structure lives in -- used only as a fallback/default
    # for the sibling-file conventions below (fragment_manifest.json,
    # config_extra.fdf, pseudopotentials); --structure itself is always
    # read directly, never re-derived from this directory.
    combined_dir = os.path.dirname(os.path.abspath(args.structure)) or "."

    if args.pseudo_dir:
        try:
            pseudo_source = resolve_pseudo_source(args.pseudo_dir)
        except ValueError as e:
            print_dual(color_text(f"[ERROR] {e}", 'red'), f_out)
            if f_out:
                f_out.close()
            sys.exit(1)
        print_dual(f"  Pseudo source   : {pseudo_source} (from --pseudo-dir '{args.pseudo_dir}')", f_out)
    else:
        pseudo_source = None
        print_dual(f"  Pseudo source   : (default) reusing '{combined_dir}'", f_out)

    try:
        structure = structure_io.read_fdf(args.structure)
    except (FileNotFoundError, ValueError) as e:
        print_dual(color_text(f"[ERROR] {e}", 'red'), f_out)
        if f_out:
            f_out.close()
        sys.exit(1)

    # --- [1] COMBINED STRUCTURE. ---
    print_section("[1] COMBINED STRUCTURE", f_out)
    cell_volume = abs(float(np.linalg.det(structure.lattice)))
    print_dual(f"  Formula         : {formula_string(structure)}", f_out)
    print_dual(f"  Total atoms     : {len(structure.atoms)}", f_out)
    print_dual(f"  Species         : {', '.join(structure.species)}", f_out)
    print_dual(f"  Cell volume     : {cell_volume:.4f} Ang^3", f_out)
    print_dual("  Lattice vectors (Ang):", f_out)
    for vec in structure.lattice:
        print_dual(f"    {vec[0]:14.8f} {vec[1]:14.8f} {vec[2]:14.8f}", f_out)

    # --- [2] FRAGMENT DEFINITION. ---
    print_section("[2] FRAGMENT DEFINITION", f_out)
    manifest_mode = args.fragment_manifest is not None
    try:
        if manifest_mode:
            manifest_path = args.fragment_manifest or os.path.join(combined_dir, "fragment_manifest.json")
            if not os.path.isfile(manifest_path):
                raise ValueError(f"fragment manifest '{manifest_path}' not found.")
            with open(manifest_path) as f:
                manifest = json.load(f)
            slab_labels, ads_labels = adsorption_sites.validate_fragment_manifest(manifest, structure)
            labeled_structure = structure
            label_sets = [slab_labels, ads_labels]
            folder_names = ["slab", "adsorbate"]
            suffixes = [manifest["slab_suffix"], manifest["adsorbate_suffix"]]
        else:
            if args.fragment_sizes:
                groups = parse_fragment_sizes(args.fragment_sizes, len(structure.atoms))
            else:
                groups = parse_fragment_species(args.fragment_species, structure)
            suffixes = [f"_frag{i + 1}" for i in range(len(groups))]
            labeled_structure = label_fragments_n(structure, groups, suffixes)
            label_sets = [
                {label for label in labeled_structure.species if label.endswith(sfx)}
                for sfx in suffixes
            ]
            folder_names = [f"fragment{i + 1}" for i in range(len(groups))]
    except ValueError as e:
        print_dual(color_text(f"[ERROR] {e}", 'red'), f_out)
        if f_out:
            f_out.close()
        sys.exit(1)

    # Always written (both fragment-manifest and fragment-sizes/-species
    # modes) -- the single source of truth stb-chargediffAnalysis reads to
    # auto-discover the combined/fragment subfolders from just --dir, no
    # labels/paths typed by hand.
    write_chargediff_manifest(args.output_dir, labeled_structure, folder_names, suffixes)

    # Pseudopotential source resolution: an explicit --pseudo-dir/bank always
    # means bare-element-named files (real_element resolution); the default
    # (no --pseudo-dir) reuses the structure file's own directory, which for
    # --fragment-manifest is an stb-adsorb site directory holding per
    # -fragment-labeled files instead (only the '_ghost' suffix needs
    # stripping there) -- see write_fragment_folder's own docstring.
    strip_ghost_only = manifest_mode and pseudo_source is None
    pp_path = pseudo_source or combined_dir

    n_fragments = len(label_sets)
    print_dual(f"  Fragments       : {n_fragments}", f_out)
    for name, labels in zip(folder_names, label_sets):
        real_rows = species_breakdown(labeled_structure, labels)
        print_dual(f"  {name}: {sum(structure_io.atom_counts(labeled_structure).get(l, 0) for l in labels)} "
                   f"real atom(s) -- {', '.join(real_rows) if real_rows else '(none)'}", f_out)

    # --- [3] MESH CUTOFF / LEVEL OF THEORY. ---
    print_section("[3] MESH CUTOFF / LEVEL OF THEORY", f_out)
    mesh_cutoff_value = f"{args.mesh_cutoff:g} Ry"
    print_dual(f"  MeshCutoff (forced identically on every fragment): {mesh_cutoff_value}"
               + (" (default)" if args.mesh_cutoff == DEFAULT_MESH_CUTOFF_RY else " (user-specified)"),
               f_out)

    spin0, dipole0, vdw0 = read_combined_theory_flags(combined_dir)
    spin_polarized = args.force_spin if args.force_spin is not None else spin0
    dipole_corrected = args.force_dipole if args.force_dipole is not None else dipole0
    vdw_corrected = args.force_vdw if args.force_vdw is not None else vdw0
    print_dual(f"  Spin polarized  : {'yes' if spin_polarized else 'no'}"
               + ("" if args.force_spin is not None else " (inherited)"), f_out)
    print_dual(f"  Dipole correction: {'yes' if dipole_corrected else 'no'}"
               + ("" if args.force_dipole is not None else " (inherited)"), f_out)
    print_dual(f"  DFT-D3 vdW      : {'yes' if vdw_corrected else 'no'}"
               + ("" if args.force_vdw is not None else " (inherited)"), f_out)

    # --- [4] WRITING COMBINED + FRAGMENT FOLDERS. ---
    print_section("[4] WRITING COMBINED + FRAGMENT FOLDERS", f_out)
    written = []

    combined_out_dir = os.path.join(args.output_dir, "combined")
    combined_files = write_fragment_folder(
        combined_out_dir, structure, calc_text, pp_path, mesh_cutoff_value,
        spin_polarized, dipole_corrected, vdw_corrected, strip_ghost_only)
    written.append(combined_out_dir)
    print_dual(f"  {color_text('[OK]', 'green')} {combined_out_dir}/ "
               f"(full system, {len(structure.atoms)} real atom(s), no ghosting)", f_out)
    print_dual(f"       structure.fdf, config_extra.fdf, calc.fdf written", f_out)
    print_dual(f"       Pseudopotentials attempted for: {', '.join(combined_files['pseudo_labels'])}", f_out)

    fragment_structures = []
    for i, (name, own_labels) in enumerate(zip(folder_names, label_sets)):
        other_labels = set().union(*(label_sets[k] for k in range(n_fragments) if k != i))
        fragment_structure = make_ghost_variant(labeled_structure, other_labels)
        fragment_structures.append((name, fragment_structure))
        out_dir = os.path.join(args.output_dir, name)
        files = write_fragment_folder(out_dir, fragment_structure, calc_text, pp_path, mesh_cutoff_value,
                                      spin_polarized, dipole_corrected, vdw_corrected, strip_ghost_only)
        written.append(out_dir)
        ghost_rows = species_breakdown(labeled_structure, other_labels)
        print_dual(f"  {color_text('[OK]', 'green')} {out_dir}/ "
                   f"({len(own_labels)} real species label(s), "
                   f"{n_fragments - 1} other fragment(s) ghosted)", f_out)
        print_dual(f"       structure.fdf, config_extra.fdf, calc.fdf written", f_out)
        print_dual(f"       Ghosted: {', '.join(ghost_rows) if ghost_rows else '(none)'}", f_out)
        print_dual(f"       Pseudopotentials attempted for: {', '.join(files['pseudo_labels'])}", f_out)

    # --- [5] STRUCTURE VIEWER. ---
    if args.view:
        print_section("[5] STRUCTURE VIEWER (ASE)", f_out)
        frame_names = ["combined"] + folder_names
        print_dual(f"  Opening one ASE viewer window with {len(frame_names)} frame(s) -- "
                   f"{', '.join(frame_names)}, in that order (use the GUI's frame slider/keys "
                   "to step through them). Ghost atoms render as mostly-hollow circles (ase-gui's "
                   "own partial-occupancy convention) -- real atoms are unaffected.", f_out)
        view_frames = [structure_to_view_atoms(structure)]
        view_frames += [structure_to_view_atoms(fragment_structure)
                        for _, fragment_structure in fragment_structures]
        view_fragments_animated(view_frames)

    # --- [6] REFERENCES. ---
    print_section("[6] REFERENCES", f_out)
    bib_entries = [citations.SIESTA, citations.SIESTA_RECENT]
    citations.write_bib_file(os.path.join(args.output_dir, BIB_FILE), bib_entries)
    print_dual(color_text(
        f"[OK] Citations written to '{os.path.join(args.output_dir, BIB_FILE)}'.", 'green'), f_out)

    # --- [7] SUMMARY & NEXT STEPS. ---
    print_section("[7] SUMMARY & NEXT STEPS", f_out)
    print_dual(f"  Folder(s) written: {len(written)} (1 combined + {n_fragments} fragment(s))", f_out)
    for out_dir in written:
        print_dual(f"    {out_dir}/", f_out)
    print_dual(f"  All {len(written)} folders share the identical cell, MeshCutoff "
               f"({mesh_cutoff_value}), and level of theory -- run SIESTA in every one of them, "
               "then run stb-chargediffAnalysis to compute and plot Delta rho.", f_out)
    if report_path:
        print_dual(f"  Report: {report_path}", f_out)

    if f_out:
        f_out.close()

    print(f"\n{color_text('Success:', 'green')} {len(written)} folder(s) written under "
          f"'{args.output_dir}' (1 combined + {n_fragments} fragment(s)).")
    if report_path:
        print(f"Full report: {report_path}")


if __name__ == "__main__":
    main()
