#!/usr/bin/env python3

#################################################
#     Siesta Tool Box - Suite                   #
# Developed by Dr. Carlos M. O. Bastos          #
#      bastoscmo.github.io                      #
#################################################

VERSION = "1.10.0"

import os
import re
import sys
import argparse
from collections import Counter
from datetime import datetime
from stb.core import structure_io, siesta_log
from stb.core.cli import COLORS, color_text, show_intro, print_dual, print_section
from stb.convergence import substitute_numeric_tag, substitute_kgrid_tag

_FOLDER_RE = re.compile(r'^convergence_([a-zA-Z]+)_([\d.]+)$')
REPORT_FILE = "convergence_report.txt"

# Whether accuracy improves as the swept value increases. True for
# meshcutoff (finer real-space grid). False for energyshift (smaller shift ->
# more diffuse, more complete PAO basis) and kgrid (smaller density -> denser
# k-mesh) -- both converge towards zero, the opposite direction from
# meshcutoff. Getting this wrong makes the plateau scan below walk away from
# convergence instead of towards it for 2 of the 3 sweepable parameters.
INCREASING_IMPROVES_ACCURACY = {
    "meshcutoff": True,
    "energyshift": False,
    "kgrid": False,
}


def parse_convergence_folder_name(folder_name):
    """Parses 'convergence_meshcutoff_250.0000' into ('meshcutoff', 250.0),
    matching the naming convention stb-convergence writes.
    """
    match = _FOLDER_RE.match(folder_name)
    if not match:
        return None, None
    return match.group(1), float(match.group(2))


def write_curve_plot(dat_path, parameter_name, rows):
    """Writes <dat_path> plus a companion .gplot next to it (value vs.
    E/atom), same <name>.dat + <name>.gplot convention as phonons_pos.py's
    write_thermal_plots -- previously this tool only wrote the .dat half.
    """
    with open(dat_path, 'w') as f:
        f.write(f"# Convergence curve | Parameter: {parameter_name}\n")
        f.write("# 1:Value 2:Energy(eV) 3:Energy_per_atom(eV) 4:Abs_Delta_E_per_atom(eV) 5:SCF_converged\n")
        for value, energy, e_per_atom, delta, scf_converged, _max_force in rows:
            f.write(f"{value:.6f}  {energy:.6f}  {e_per_atom:.6f}  {(delta or 0.0):.6f}  {int(scf_converged)}\n")

    base = os.path.splitext(dat_path)[0]
    base_name = os.path.basename(base)
    gplot_path = f"{base}.gplot"
    dat_name = os.path.basename(dat_path)
    with open(gplot_path, 'w') as f:
        f.writelines([
            '# --- STB Plot Configuration ---\n',
            '# Generated by stb-convergenceAnalysis\n',
            'set terminal pdfcairo enhanced color font "Arial,14" size 7,5\n',
            f'set output "{base_name}.pdf"\n\n',
            f'set title "Convergence: {parameter_name}"\n',
            f'set xlabel "{parameter_name}"\n',
            'set ylabel "Energy per atom (eV)"\n',
            'set grid\n',
            (f'plot "{dat_name}" using 1:3 with linespoints lw 2 pt 7 '
             f'lc rgb "#2255cc" title "E/atom"\n'),
        ])
    return gplot_path


def main():
    parser = argparse.ArgumentParser(
        description=f"""{color_text("Analyzes a stb-convergence sweep and reports where the total energy converges.", 'bold')}""",
        formatter_class=argparse.RawTextHelpFormatter,
        epilog="Usage examples:\n"
               "  %(prog)s --dir convergence_runs --file calc.out --tolerance 0.001\n"
               "  %(prog)s --dir convergence_runs --apply calc.fdf\n"
    )

    parser.add_argument("--dir", type=str, default="convergence_runs",
                        help="Directory containing the 'convergence_*' run folders (default: convergence_runs).")
    parser.add_argument("--file", type=str, default="calc.out",
                        help="SIESTA output filename inside each run folder (default: calc.out).")
    parser.add_argument("--tolerance", type=float, default=0.001,
                        help="Convergence tolerance in eV/atom (default: 0.001).")
    parser.add_argument("-o", "--output", type=str, default="convergence_curve.dat",
                        help="Output curve data file name (default: convergence_curve.dat).")
    parser.add_argument("--apply", type=str, default=None, metavar="CALC_FDF",
                        help="If a converged value is found, write it into this calc.fdf in place "
                             "(same tag substitution stb-convergence itself uses).")
    parser.add_argument("--vacuum-gap", type=float, default=10.0,
                        help="--apply with a kgrid sweep only: vacuum-axis detection threshold in "
                             "Angstrom, same meaning as stb-kgrid's --vacuum-gap (default: 10.0).")
    parser.add_argument("--save-report", action="store_true",
                        help=f"Also persist the report to {REPORT_FILE}. Off by default.")
    parser.add_argument("-v", "--version", action="version", version=f"stb-convergenceAnalysis {VERSION}")
    parser.add_argument("--no-intro", dest="intro", action="store_false", help="Do not show the introduction")

    args = parser.parse_args()

    if args.intro:
        show_intro([
            "Siesta ToolBox Suite",
            "A comprehensive toolkit for SIESTA DFT simulations",
            f"Version {VERSION} | University of Brasilia - 2025",
            "Developed by Dr. Carlos M. O. Bastos"
        ])

    print("\n" + color_text("Analyze a convergence-test sweep:", 'bold'))
    print("-" * 60)

    if not os.path.isdir(args.dir):
        print(color_text(f"Error: Directory '{args.dir}' not found.", 'red'))
        sys.exit(1)

    folders = sorted(
        f for f in os.listdir(args.dir)
        if os.path.isdir(os.path.join(args.dir, f)) and f.startswith("convergence_")
    )
    if not folders:
        print(color_text(f"Error: No 'convergence_*' folders found in '{args.dir}'.", 'red'))
        sys.exit(1)

    # Peek every folder name (no file reads yet) to lock the swept parameter
    # up front, so a stray folder from a different sweep -- e.g. leftover
    # meshcutoff_* runs sitting in the same default convergence_runs/ dir as
    # a later kgrid_* sweep -- gets skipped instead of silently merged into
    # this curve. Locked to the *majority* parameter, not just the first one
    # in (alphabetical) folder-listing order -- "kgrid" sorts before
    # "meshcutoff", so picking "first seen" would let a single stray kgrid_*
    # folder silently outvote a real 4-point meshcutoff_* sweep sitting right
    # next to it.
    parsed_folders = [(f, *parse_convergence_folder_name(f)) for f in folders]
    param_counts = Counter(p for _, p, _ in parsed_folders if p is not None)
    parameter_name = param_counts.most_common(1)[0][0] if param_counts else None
    # Counter.most_common breaks a tied count by insertion order (i.e. by
    # alphabetical folder name), which would quietly reintroduce the same
    # "wrong parameter wins" failure this majority vote exists to prevent --
    # just narrowed to the case of an exact tie. Surface it instead of
    # picking silently.
    tied_params = sorted(p for p, c in param_counts.items() if c == param_counts.most_common(1)[0][1]) \
        if param_counts else []

    data = []  # (value, energy, n_atoms, scf_converged, max_force)
    first_structure = None
    n_mismatched = 0
    n_skipped = 0

    report_path = REPORT_FILE if args.save_report else None
    f_out = open(report_path, "w") if report_path else None

    print_dual(f"{color_text('===== CONVERGENCE TEST REPORT =====', 'magenta')}", f_out)

    print_section('[0] RUN METADATA', f_out)
    print_dual(f"Date/time  : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", f_out)
    print_dual(f"Directory  : {args.dir}", f_out)
    print_dual(f"Output file: {args.file}", f_out)
    print_dual(f"Tolerance  : {args.tolerance} eV/atom", f_out)
    if len(tied_params) > 1:
        print_dual(color_text(
            f"[WARNING] Ambiguous parameter mix: {', '.join(tied_params)} are equally "
            f"represented in '{args.dir}'; picked '{parameter_name}' arbitrarily. "
            "Use a separate --dir per sweep to avoid this.", 'yellow'), f_out)

    print_section('[1] READING FOLDERS', f_out)
    for folder, param, value in parsed_folders:
        if param is None:
            continue

        if param != parameter_name:
            n_mismatched += 1
            print_dual(f"   -> {folder:<30} : {color_text('SKIP', 'yellow')} "
                        f"(different parameter: '{param}', expected '{parameter_name}')", f_out)
            continue

        folder_path = os.path.join(args.dir, folder)
        struct_path = os.path.join(folder_path, "structure.fdf")
        out_path = os.path.join(folder_path, args.file)

        if not os.path.exists(struct_path) or not os.path.exists(out_path):
            n_skipped += 1
            print_dual(f"   -> {folder:<30} : {color_text('SKIP', 'yellow')} "
                        f"(missing structure.fdf or {args.file})", f_out)
            continue

        energy = siesta_log.get_free_energy(out_path)
        if energy is None:
            n_skipped += 1
            print_dual(f"   -> {folder:<30} : {color_text('SKIP', 'yellow')} (could not parse energy)", f_out)
            continue

        structure = structure_io.read_fdf(struct_path)
        n_atoms = len(structure.atoms)
        first_structure = first_structure or structure

        scf_converged, _iterations = siesta_log.get_scf_convergence(out_path)
        max_force = siesta_log.get_max_force(out_path)

        data.append((value, energy, n_atoms, scf_converged, max_force))
        status = color_text('OK', 'green') if scf_converged else color_text('OK (SCF not confirmed converged)', 'yellow')
        print_dual(f"   -> {folder:<30} : {status}", f_out)

    if not data:
        print_dual(color_text("\nError: No valid data found in convergence folders.", 'red'), f_out)
        if f_out:
            f_out.close()
        sys.exit(1)

    data.sort(key=lambda d: d[0])

    print_dual(f"\n  Parameter : {parameter_name}", f_out)
    print_dual(f"  Runs found: {len(data)} (skipped: {n_skipped} unreadable, "
                f"{n_mismatched} different-parameter)", f_out)

    print_section('[2] SWEEP TABLE', f_out)
    header = (f"{'Value':<12} {'Energy(eV)':<16} {'E/atom(eV)':<14} {'|Delta E/atom|':<16} "
              f"{'SCF':<6} {'MaxForce(eV/Ang)':<16}")
    print_dual(header, f_out)
    print_dual("-" * len(header), f_out)

    rows = []
    prev_e_per_atom = None
    for value, energy, n_atoms, scf_converged, max_force in data:
        e_per_atom = energy / n_atoms
        delta = None if prev_e_per_atom is None else abs(e_per_atom - prev_e_per_atom)
        rows.append((value, energy, e_per_atom, delta, scf_converged, max_force))

        delta_str = f"{delta:.6f}" if delta is not None else "--"
        scf_str = "OK" if scf_converged else color_text("WARN", 'yellow')
        force_str = f"{max_force:.6f}" if max_force is not None else "--"
        print_dual(f"{value:<12.4f} {energy:<16.6f} {e_per_atom:<14.6f} {delta_str:<16} "
                    f"{scf_str:<6} {force_str:<16}", f_out)

        prev_e_per_atom = e_per_atom

    print_dual("-" * len(header), f_out)

    # Accuracy improves in different directions for different parameters
    # (see INCREASING_IMPROVES_ACCURACY): scan from cheap towards
    # accurate, not blindly by ascending value, so the "beyond this point
    # nothing changes" logic below walks towards the converged limit
    # instead of away from it.
    increasing_is_accurate = INCREASING_IMPROVES_ACCURACY.get(parameter_name, True)
    scan_source = rows if increasing_is_accurate else list(reversed(rows))
    scan_points = []
    prev_e_per_atom = None
    for value, _energy, e_per_atom, _delta, scf_converged, _max_force in scan_source:
        delta = None if prev_e_per_atom is None else abs(e_per_atom - prev_e_per_atom)
        scan_points.append((value, delta, scf_converged))
        prev_e_per_atom = e_per_atom

    # A single small delta can be a coincidence rather than a real
    # plateau (e.g. odd/even k-grid parity effects, or two SCF-unconverged
    # points landing close by chance), so only accept a point as
    # converged if it and every subsequent (more accurate-ward) step both
    # have a converged SCF cycle and stay within tolerance.
    converged_value = None
    n_scf_warnings = sum(1 for _, _, _, scf_converged, _ in data if not scf_converged)
    for i in range(1, len(scan_points)):
        tail = scan_points[i:]
        if all(d is not None and d < args.tolerance and scf_ok for _, d, scf_ok in tail):
            converged_value = scan_points[i][0]
            break

    print_section('[3] CONVERGENCE RESULT', f_out)
    print_dual(f"Increasing {parameter_name} improves accuracy: {increasing_is_accurate}", f_out)
    if n_scf_warnings:
        print_dual(color_text(
            f"[WARNING] {n_scf_warnings} run(s) never confirmed SCF convergence; "
            "their energy was excluded from the converged-point search.", 'yellow'), f_out)

    direction_hint = "or higher" if increasing_is_accurate else "or lower"
    if converged_value is not None:
        print_dual(f"{color_text('Converged at:', 'green')} {parameter_name} = {converged_value:.4f} "
                    f"({direction_hint} is also fine, |Delta E/atom| < {args.tolerance} eV)", f_out)
    else:
        print_dual(color_text(
            f"[WARNING] No point met the {args.tolerance} eV/atom tolerance; "
            "consider extending --min/--max.", 'yellow'), f_out)

    gplot_path = write_curve_plot(args.output, parameter_name, rows)
    print_dual(f"\n{color_text('[Saved]', 'cyan')} Curve data -> {args.output}, {gplot_path} "
                f"(cd {os.path.dirname(args.output) or '.'} && gnuplot {os.path.basename(gplot_path)})", f_out)
    if report_path:
        print_dual(f"{color_text('[Saved]', 'cyan')} Report     -> {report_path}", f_out)

    if args.apply:
        print_section('[4] APPLY', f_out)
        if converged_value is None:
            print_dual(color_text("Skipped: no converged value to apply.", 'yellow'), f_out)
        else:
            try:
                with open(args.apply, 'r') as f:
                    calc_text = f.read()
            except OSError as e:
                print_dual(color_text(f"[ERROR] Could not read '{args.apply}': {e}", 'red'), f_out)
            else:
                try:
                    if parameter_name == "kgrid":
                        new_calc, divisions = substitute_kgrid_tag(
                            calc_text, first_structure, converged_value, args.vacuum_gap)
                        detail = f"grid {divisions[0]} {divisions[1]} {divisions[2]}"
                    else:
                        new_calc = substitute_numeric_tag(calc_text, parameter_name, converged_value)
                        detail = f"{converged_value:.4f} Ry"
                except ValueError as e:
                    print_dual(color_text(f"[ERROR] {e}", 'red'), f_out)
                else:
                    try:
                        with open(args.apply, 'w') as f:
                            f.write(new_calc)
                    except OSError as e:
                        print_dual(color_text(f"[ERROR] Could not write '{args.apply}': {e}", 'red'), f_out)
                    else:
                        print_dual(f"{color_text('[Applied]', 'green')} {parameter_name} = "
                                    f"{converged_value:.4f} ({detail}) -> {args.apply}", f_out)

    if f_out:
        f_out.close()


if __name__ == "__main__":
    main()
