#!/usr/bin/env python

#################################################
#     Siesta Tool Box - Suite                   #
# Developed by Dr. Carlos M. O. Bastos          #
#      bastoscmo.github.io                      #
#################################################

VERSION = "1.22.0"

import os
import sys
import argparse
import numpy as np
import time

from stb.core.deps import require_sisl, read_sisl_geometry_xv_or_fdf
sisl = require_sisl()

# ANSI Colors for terminal
from stb.core.cli import COLORS, color_text, show_intro

# A cut plane whose two in-plane lattice vectors deviate from 90 degrees by more than
# this is flagged -- gnuplot's `pm3d map` interpolation assumes a roughly rectangular
# grid in the two plotted axes, and a skewed cell (e.g. hexagonal, common for 2D
# materials) can render visibly distorted even though the data file's own coordinates
# are correct.
NON_ORTHOGONAL_WARN_DEG = 1.0


def check_planar_orthogonality(lattice, axis_idx):
    """Returns the angle (degrees) between the two in-plane lattice vectors
    of the cut plane perpendicular to `axis_idx` -- 90 for a rectangular
    cut, something else for a skewed one (e.g. hexagonal cells).
    """
    in_plane = [i for i in range(3) if i != axis_idx]
    v1, v2 = lattice[in_plane[0]], lattice[in_plane[1]]
    cos_angle = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
    return float(np.degrees(np.arccos(np.clip(cos_angle, -1.0, 1.0))))


def write_gnuplot_script(data_filename, output_filename, mode, quantity_label,
                         is_signed, axis_idx=2, pos_val=0.0, plane_angle_deg=90.0,
                         cb_range=None, contour=False):
    """
    Generates a .gplot script using the specific templates provided.
    - 3D: Based on '3dplot.gplot'
    - Slice: Based on 'plot.gplot'
    - Profile: a plain 2D line plot of the planar average

    cb_range, if given, is a (cb_min, cb_max) tuple written as an explicit
    'set cbrange' -- for a signed quantity (spin density, --rho2 difference)
    this should be symmetric around zero so the diverging palette's white
    midpoint actually lands on zero (gnuplot's autorange centers white at
    (data_min+data_max)/2, not necessarily 0, for asymmetric data).
    """
    gplot_name = output_filename.rsplit('.', 1)[0] + ".gplot"
    pdf_name = output_filename.rsplit('.', 1)[0] + ".pdf"

    axis_labels = ['X', 'Y', 'Z']
    fixed_axis = axis_labels[axis_idx]

    fileout = []
    fileout.append('# --- STB Plot Configuration ---\n')
    fileout.append('# Generated by plotdensity.py\n')
    if mode != 'profile' and abs(plane_angle_deg - 90.0) > NON_ORTHOGONAL_WARN_DEG:
        fileout.append(
            f'# NOTE: the cut plane is skewed ({plane_angle_deg:.1f} deg between its two\n'
            '# in-plane lattice vectors, not 90) -- pm3d map assumes a roughly rectangular\n'
            '# grid in the two plotted axes, so this may render visibly distorted even\n'
            "# though the data file's own X/Y/Z coordinates are correct. Consider plotting\n"
            '# the data file directly in a tool that triangulates irregular points (e.g.\n'
            '# matplotlib tricontourf, VESTA) if this looks wrong.\n'
        )

    # --- TEMPLATE: PROFILE (planar-averaged 1D line) ---
    if mode == 'profile':
        fileout.append('set terminal pdfcairo enhanced color font "Arial,14" size 7,5\n')
        fileout.append(f'set output "{pdf_name}"\n')
        fileout.append('\n')

        fileout.append(f'set title "Planar-averaged {quantity_label} along {fixed_axis}"\n')
        fileout.append(f'set xlabel "{fixed_axis} (Angstrom)"\n')
        fileout.append(f'set ylabel "{quantity_label} (e/Ang^3)"\n')
        fileout.append('set grid\n')
        if is_signed:
            fileout.append('set arrow from graph 0,first 0 to graph 1,first 0 nohead lc rgb "gray" dt 2\n')
        fileout.append(f'plot "{data_filename}" using 1:2 with lines lw 2 lc rgb "#cc5522" title "{quantity_label}"\n')

    # --- TEMPLATE: SLICE (Based on plot.gplot) ---
    elif mode == 'slice':
        # Output setup
        fileout.append(f'set terminal pdfcairo enhanced color font "Arial,14" size 6,5\n')
        fileout.append(f'set output "{pdf_name}"\n')
        fileout.append('\n')

        # Logic to choose columns for 2D Map (X vs Y, X vs Z, Y vs Z)
        if axis_idx == 2:   # Fixed Z -> Plot X(1) vs Y(2)
            cols = "1:2:4"
            xl, yl = "X (Angstrom)", "Y (Angstrom)"
        elif axis_idx == 1: # Fixed Y -> Plot X(1) vs Z(3)
            cols = "1:3:4"
            xl, yl = "X (Angstrom)", "Z (Angstrom)"
        elif axis_idx == 0: # Fixed X -> Plot Y(2) vs Z(3)
            cols = "2:3:4"
            xl, yl = "Y (Angstrom)", "Z (Angstrom)"

        fileout.append(f'set title "{quantity_label} Slice ({fixed_axis}={pos_val:.2f} A)"\n')
        fileout.append(f'set xlabel "{xl}"\n')
        fileout.append(f'set ylabel "{yl}"\n')
        fileout.append(f'set cblabel "{quantity_label} (e/Ang^3)"\n')

        # Style from plot.gplot
        fileout.append('set size ratio -1\n')
        fileout.append('set tics out nomirror\n')
        fileout.append('set pm3d map\n')
        fileout.append('set pm3d interpolate 10,10  # Smoothing\n')

        if is_signed:
            fileout.append('# Palette: Blue -> White -> Red (diverging, for a signed quantity)\n')
            fileout.append('set palette defined (0 "#000099", 1 "#2255cc", 2 "#ffffff", 3 "#cc5522", 4 "#990000")\n')
        else:
            fileout.append('# Palette: White -> Yellow -> Red (sequential, for a non-negative quantity)\n')
            fileout.append('set palette defined (0 "#ffffff", 1 "#ffeda0", 2 "#feb24c", 3 "#f03b20", 4 "#bd0026")\n')

        if cb_range is not None:
            fileout.append(f'set cbrange [{cb_range[0]:.6g}:{cb_range[1]:.6g}]\n')

        if contour:
            fileout.append('# Contour overlay\n')
            fileout.append('set contour base\n')
            fileout.append('set cntrparam levels 10\n')
            fileout.append('unset clabel\n')

        fileout.append(f'splot "{data_filename}" using {cols} with pm3d\n')

    # --- TEMPLATE: 3D (Based on 3dplot.gplot) ---
    else:
        # Output setup (PDF as requested)
        fileout.append(f'set terminal pdfcairo enhanced color font "Arial,12" size 8,6\n')
        fileout.append(f'set output "{pdf_name}"\n')
        fileout.append('\n')

        fileout.append(f'set title "3D {quantity_label} (Point Cloud)"\n')
        fileout.append('set xlabel "X (Angstrom)"\n')
        fileout.append('set ylabel "Y (Angstrom)"\n')
        fileout.append('set zlabel "Z (Angstrom)"\n')

        # Styles from 3dplot.gplot
        fileout.append('set view 60, 120, 1, 1\n')
        fileout.append('set size ratio -1\n')
        fileout.append('set ticslevel 0\n')

        # Depthorder and Fill
        fileout.append('set pm3d depthorder\n')
        fileout.append('set style fill solid 1.0 noborder\n')

        # Palette: Vibrant Spectrum
        fileout.append('set palette defined (0 "#2c7bb6", 1 "#00a6ca", 2 "#00ccbc", 3 "#90eb9d", 4 "#ffff8c", 5 "#f9d057", 6 "#f29e2e", 7 "#e76818", 8 "#d7191c")\n')

        if cb_range is not None:
            fileout.append(f'set cbrange [{cb_range[0]:.6g}:{cb_range[1]:.6g}]\n')

        # Note: 'pm3d' requires grid structure. 'points' works for volume clouds.
        # We use 'points' here to visualize the density cloud.
        fileout.append(f'splot "{data_filename}" using 1:2:3:4 with points palette pt 7 ps 0.4 title "{quantity_label}"\n')

    with open(gplot_name, 'w') as f:
        f.writelines(fileout)

    print(f"[INFO] Gnuplot script saved to '{color_text(gplot_name, 'green')}'")
    print(f"[INFO] To plot: {color_text(f'gnuplot {gplot_name}', 'cyan')}")

def integrated_charge(grid_data, lattice):
    """Sum of grid values times the voxel volume -- the total integrated
    quantity over the cell: electron count for a total charge density,
    net moment for a spin density, net transferred charge for a --rho2
    difference. A quick sanity check against the expected valence electron
    count, independent of any plotting/slicing choice.
    """
    cell_volume = abs(np.linalg.det(lattice))
    voxel_volume = cell_volume / grid_data.size
    return float(grid_data.sum() * voxel_volume)


def write_profile_data_file(grid_data, lattice, axis, output_file):
    """Writes the planar average of grid_data over the two axes perpendicular
    to `axis`, as a function of position along `axis` -- a 1D density/spin
    profile useful for slabs, interfaces, and superlattices. Returns the
    (min, max) of the profile values.
    """
    print(f"[INFO] Mode: Planar-Averaged Profile")
    avg_axes = tuple(a for a in (0, 1, 2) if a != axis)
    profile = grid_data.mean(axis=avg_axes)
    n = profile.shape[0]
    axis_len = np.linalg.norm(lattice[axis])
    positions = (np.arange(n) / n) * axis_len

    with open(output_file, 'w') as f:
        f.write(f"# Generated by STB. Format: Position(Ang) Planar_Averaged_Value\n")
        for pos, val in zip(positions, profile):
            f.write(f"{pos:.6f} {val:.6e}\n")

    return float(profile.min()), float(profile.max())


def write_data_file(grid_data, lattice, origin, output_file, mode='3d', slice_idx=0, axis=2,
                    iso_min=None):
    """
    Writes grid data. For 'slice' mode, ensures block format for PM3D.
    Returns the (min, max) of the values actually written, so the caller can
    build a matching colorbar range.
    """
    nx, ny, nz = grid_data.shape
    start_time = time.time()

    # --- 3D MODE ---
    if mode == '3d':
        print(f"[INFO] Mode: Full 3D Volume Export")
        print(f"[INFO] Processing {nx*ny*nz} grid points...")

        # Use vectorized operations for speed
        ix, iy, iz = np.meshgrid(range(nx), range(ny), range(nz), indexing='ij')

        # Coordinates
        frac_coords = np.vstack([ix.flatten()/nx, iy.flatten()/ny, iz.flatten()/nz]).T
        values_flat = grid_data.flatten()

        if iso_min is not None:
            n_before = len(values_flat)
            mask = np.abs(values_flat) >= iso_min
            frac_coords = frac_coords[mask]
            values_flat = values_flat[mask]
            n_after = len(values_flat)
            pct = (100.0 * n_after / n_before) if n_before else 0.0
            print(f"[INFO] --iso-min {iso_min}: kept {n_after}/{n_before} points ({pct:.1f}%)")
            if n_after == 0:
                print(color_text(
                    "[ERROR] No points survived --iso-min -- the threshold is higher than "
                    "every |value| in this grid.", 'red'))
                sys.exit(1)

        real_coords = origin + np.dot(frac_coords, lattice)
        data_to_save = np.column_stack([real_coords, values_flat])

        # Simple export for point cloud
        header_txt = "X Y Z Charge_Density"
        np.savetxt(output_file, data_to_save, fmt='%.6f %.6f %.6f %.6e', header=header_txt)

        vmin, vmax = float(values_flat.min()), float(values_flat.max())

    # --- 2D MAP MODE (Slice) ---
    elif mode == 'slice':
        axis_names = ['X', 'Y', 'Z']
        print(f"[INFO] Mode: 2D Map (Slice)")
        print(f"[INFO] Mapping plane perpendicular to {axis_names[axis]} axis at Index {slice_idx}")

        # Slice plane values, taken directly (cheap) to build a matching colorbar range
        if axis == 2:
            slice_arr = grid_data[:, :, slice_idx]
        elif axis == 1:
            slice_arr = grid_data[:, slice_idx, :]
        else:
            slice_arr = grid_data[slice_idx, :, :]
        vmin, vmax = float(slice_arr.min()), float(slice_arr.max())

        with open(output_file, 'w') as f:
            f.write(f"# Generated by STB. Format: X Y Z Charge_Density\n")

            # Select iteration ranges based on which axis is fixed
            if axis == 2:   # Cut along Z (XY Plane)
                u_range, v_range = range(nx), range(ny)
                i_fixed = slice_idx
            elif axis == 1: # Cut along Y (XZ Plane)
                u_range, v_range = range(nx), range(nz)
                i_fixed = slice_idx
            elif axis == 0: # Cut along X (YZ Plane)
                u_range, v_range = range(ny), range(nz)
                i_fixed = slice_idx

            # Nested loop to create PM3D blocks (Blank line separation)
            for i in u_range:
                for j in v_range:
                    if axis == 2: ix, iy, iz = i, j, i_fixed
                    elif axis == 1: ix, iy, iz = i, i_fixed, j
                    elif axis == 0: ix, iy, iz = i_fixed, i, j

                    frac_coords = np.array([ix/nx, iy/ny, iz/nz])
                    real_pos = origin + np.dot(frac_coords, lattice)
                    val = grid_data[ix, iy, iz]

                    f.write(f"{real_pos[0]:.6f} {real_pos[1]:.6f} {real_pos[2]:.6f} {val:.6e}\n")

                f.write("\n") # Blank line for PM3D structure

    elapsed = time.time() - start_time
    print(f"[INFO] Write completed in {elapsed:.2f} seconds.")
    return vmin, vmax


def read_component(sile, component_index, source_desc):
    """Reads one grid component (0=charge/total, 1=spin) via sisl, giving a
    clean error instead of sisl's own bare IndexError when --spin is
    requested on a non-spin-polarized .RHO (which only has component 0).
    """
    try:
        return sile.read_grid(index=component_index)
    except IndexError:
        if component_index == 0:
            raise
        print(color_text(
            f"[ERROR] --spin requested but {source_desc} has no spin component -- "
            "this doesn't look like a spin-polarized calculation.", 'red'))
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description=f"""{color_text("Converts a SIESTA charge-density grid (.RHO) to Gnuplot 2D maps, 3D point clouds, or planar-averaged 1D profiles.", 'bold')}
By default plots the total charge density. --spin plots the spin density
(up-down) instead, if the .RHO file is spin-polarized. --rho2 subtracts a
second .RHO file's density from the first (Delta rho = rho1 - rho2), the
standard way to visualize charge transfer/bonding (e.g. adsorbate+substrate
vs. isolated fragments) -- both files must be on the same grid. --iso-min
filters low-|density| points out of a --3d export, since an unfiltered
production-size grid can produce a multi-GB file dominated by
near-zero vacuum/interstitial points. --profile writes the planar average
along the chosen axis instead of a map (useful for slabs/interfaces). --cube
additionally writes a standard Gaussian cube file (needs a <label>.XV or
<label>.fdf for the geometry) for real isosurface rendering in VESTA/VMD/
Avogadro. --vmin/--vmax fix the colorbar range manually, e.g. to compare
several slices on the same scale.""",
        epilog="Example usage:\n"
               "  %(prog)s --label siesta\n"
               "  %(prog)s --label siesta --3d --iso-min 0.01\n"
               "  %(prog)s --label siesta --spin\n"
               "  %(prog)s --label adsorbed --rho2 isolated.RHO\n"
               "  %(prog)s --label siesta --profile --axis 2\n"
               "  %(prog)s --label siesta --cube\n",
        formatter_class=argparse.RawTextHelpFormatter
    )

    parser.add_argument("-l", "--label", required=True, help="System Label (looks for .RHO file)")
    parser.add_argument("-o", "--output", default=None,
                        help="Output data filename (default: <label>_density.dat)")
    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument("--3d", action="store_true", dest="full_3d", help="Export full 3D volume")
    mode_group.add_argument("--profile", action="store_true",
                        help="Write the planar average of the density along --axis as a 1D "
                             "profile (average taken over the other two axes) instead of a "
                             "2D/3D map -- useful for slabs, interfaces, and superlattices")
    parser.add_argument("-a", "--axis", type=int, default=2, choices=[0,1,2],
                        help="For a slice/profile: the axis normal to the cut plane (slice) or "
                             "the axis the profile varies along (profile) (0=X, 1=Y, 2=Z)")
    parser.add_argument("-p", "--pos", type=float, help="Position (Angstrom) of the 2D cut (ignored in --profile mode)")
    parser.add_argument("--spin", action="store_true",
                        help="Plot the spin density (up-down) instead of the total charge "
                             "density -- only available for spin-polarized .RHO files")
    parser.add_argument("--rho2", metavar="FILE", default=None,
                        help="A second .RHO file to subtract from the first (Delta rho = "
                             "rho1 - rho2), e.g. to visualize charge transfer upon adsorption "
                             "or defect formation. Must be on the same grid (same shape) as "
                             "<label>.RHO.")
    parser.add_argument("--iso-min", type=float, default=None, metavar="RHO",
                        help="For --3d: only export points with |density| >= this threshold "
                             "(e/Ang^3) -- keeps the point cloud a manageable size and "
                             "visually meaningful instead of dominated by near-zero points")
    parser.add_argument("--cube", action="store_true",
                        help="Also write the full 3D grid as a Gaussian .cube file (needs "
                             "<label>.XV or <label>.fdf for the geometry) -- for real 3D "
                             "isosurface rendering in VESTA/VMD/Avogadro, which handle "
                             "volumetric data better than a gnuplot point cloud")
    parser.add_argument("--vmin", type=float, default=None,
                        help="Fix the colorbar/palette lower bound manually (e/Ang^3), e.g. "
                             "to compare several slices on the same scale")
    parser.add_argument("--vmax", type=float, default=None,
                        help="Fix the colorbar/palette upper bound manually (e/Ang^3)")
    parser.add_argument("--contour", action="store_true",
                        help="Overlay contour lines on a 2D slice map (ignored for --3d/--profile)")

    parser.add_argument("--no-intro", dest="intro", action="store_false", help="Do not show the introduction")
    parser.add_argument("-v", "--version", action="version", version=f"stb-density {VERSION}")

    args = parser.parse_args()
    filename = f"{args.label}.RHO"
    output = args.output if args.output else f"{args.label}_density.dat"

    if args.intro:
        show_intro([
            "Siesta ToolBox Suite - Density Plotter",
            "Exports RHO to Gnuplot (2D Maps & 3D Clouds)",
            f"Version {VERSION} | University of Brasilia - 2025",
            "Developed by Dr. Carlos M. O. Bastos"
        ])

    print("\n" + color_text("DENSITY PLOTTER:", 'bold'))
    print("-" * 60)

    if not os.path.exists(filename):
        print(f"{COLORS['red']}[ERROR] File '{filename}' not found.{COLORS['reset']}")
        sys.exit(1)

    component_index = 1 if args.spin else 0

    print(f"[INFO] Reading: {color_text(filename, 'cyan')}")
    try:
        sile = sisl.get_sile(filename)
        grid_obj = read_component(sile, component_index, filename)
    except Exception as e:
        print(f"{COLORS['red']}[FATAL] {e}{COLORS['reset']}")
        sys.exit(1)

    grid_data = grid_obj.grid
    lattice = grid_obj.lattice.cell
    origin = grid_obj.origin
    nx, ny, nz = grid_data.shape

    print(f"[INFO] Grid: {nx}x{ny}x{nz}")

    is_signed = args.spin
    quantity_label = "Spin Density" if args.spin else "Charge Density"

    if args.rho2:
        if not os.path.exists(args.rho2):
            print(f"{COLORS['red']}[ERROR] File '{args.rho2}' not found.{COLORS['reset']}")
            sys.exit(1)
        print(f"[INFO] Reading second grid for difference: {color_text(args.rho2, 'cyan')}")
        try:
            sile2 = sisl.get_sile(args.rho2)
            grid_obj2 = read_component(sile2, component_index, args.rho2)
        except Exception as e:
            print(f"{COLORS['red']}[FATAL] {e}{COLORS['reset']}")
            sys.exit(1)

        if grid_obj2.grid.shape != grid_data.shape:
            print(color_text(
                f"[ERROR] Grid shape mismatch: {filename} is {grid_data.shape} but "
                f"{args.rho2} is {grid_obj2.grid.shape} -- both files must be on the same "
                "grid to take a difference.", 'red'))
            sys.exit(1)

        grid_data = grid_data - grid_obj2.grid
        quantity_label = f"Delta {quantity_label}"
        is_signed = True

    total_charge = integrated_charge(grid_data, lattice)
    print(f"[INFO] Integrated {quantity_label}: {color_text(f'{total_charge:.4f} e', 'cyan')} "
          "over the cell (sanity check against the expected valence electron count)")

    if args.profile:
        mode = 'profile'
    elif args.full_3d:
        mode = '3d'
    else:
        mode = 'slice'

    if args.contour and mode != 'slice':
        print(color_text(
            "[WARNING] --contour only applies to the default 2D slice mode -- ignoring.",
            'yellow'))

    if args.pos is not None and mode == 'profile':
        print(color_text(
            "[WARNING] --pos has no effect in --profile mode -- the profile covers the "
            "whole axis.", 'yellow'))

    slice_idx = 0
    pos_val = 0.0
    plane_angle_deg = 90.0
    data_vmin = data_vmax = None

    if mode == 'slice':
        dim_size = [nx, ny, nz][args.axis]
        if args.pos is not None:
            axis_vec = lattice[args.axis]
            axis_len = np.linalg.norm(axis_vec)
            slice_idx = int(round((args.pos / axis_len) * dim_size))
            pos_val = args.pos
        else:
            slice_idx = dim_size // 2
            pos_val = (slice_idx / dim_size) * np.linalg.norm(lattice[args.axis])
            print(f"{COLORS['yellow']}[NOTICE] Using center of axis {args.axis}: {pos_val:.2f} A{COLORS['reset']}")

        if slice_idx < 0 or slice_idx >= dim_size:
            print(f"{COLORS['red']}[ERROR] Position out of bounds.{COLORS['reset']}")
            sys.exit(1)

        plane_angle_deg = check_planar_orthogonality(lattice, args.axis)
        if abs(plane_angle_deg - 90.0) > NON_ORTHOGONAL_WARN_DEG:
            print(color_text(
                f"[WARNING] The cut plane is skewed ({plane_angle_deg:.1f} deg between its "
                "two in-plane lattice vectors, not 90) -- gnuplot's pm3d map assumes a "
                "roughly rectangular grid and may render this visibly distorted even though "
                "the data file's coordinates are correct (common for hexagonal cells).",
                'yellow'))

    if mode == 'profile':
        data_vmin, data_vmax = write_profile_data_file(grid_data, lattice, args.axis, output)
    else:
        data_vmin, data_vmax = write_data_file(grid_data, lattice, origin, output, mode, slice_idx,
                        args.axis, iso_min=args.iso_min if mode == '3d' else None)

    # Colorbar range: an explicit --vmin/--vmax always wins; otherwise a signed quantity
    # (spin density, --rho2 difference) gets a range symmetric around zero so the diverging
    # palette's white midpoint actually lands on zero (gnuplot's autorange would center white
    # at (data_min+data_max)/2 instead, which is only 0 for coincidentally symmetric data); a
    # non-negative quantity is anchored at 0 for a consistent "white = no charge" baseline.
    cb_range = None
    if mode in ('slice', '3d'):
        if args.vmin is not None or args.vmax is not None:
            cb_min = args.vmin if args.vmin is not None else data_vmin
            cb_max = args.vmax if args.vmax is not None else data_vmax
        elif is_signed:
            m = max(abs(data_vmin), abs(data_vmax))
            cb_min, cb_max = -m, m
        else:
            cb_min, cb_max = 0.0, data_vmax
        # A degenerate range (e.g. an all-zero --rho2 diff of identical files) would write
        # a meaningless "set cbrange [0:0]" -- leave it to gnuplot's own autorange instead.
        if cb_max > cb_min:
            cb_range = (cb_min, cb_max)

    contour = args.contour and mode == 'slice'
    write_gnuplot_script(output, output, mode, quantity_label, is_signed, args.axis, pos_val,
                        plane_angle_deg, cb_range=cb_range, contour=contour)

    if args.cube:
        geometry, geo_file = read_sisl_geometry_xv_or_fdf(args.label)
        if geometry is None:
            print(color_text(
                f"[ERROR] --cube requires a geometry file -- neither '{args.label}.XV' nor "
                f"'{args.label}.fdf' was found.", 'red'))
            sys.exit(1)
        if not np.allclose(geometry.cell, lattice, atol=1e-2):
            print(color_text(
                f"[ERROR] The cell in '{geo_file}' does not match the density grid's own "
                "cell -- refusing to write a cube file with mismatched geometry.", 'red'))
            sys.exit(1)
        cube_filename = output.rsplit('.', 1)[0] + ".cube"
        grid_obj.grid = grid_data
        grid_obj.set_geometry(geometry)
        grid_obj.write(cube_filename)
        print(f"[INFO] Cube file saved to '{color_text(cube_filename, 'green')}' "
              "(open in VESTA/VMD/Avogadro for real 3D isosurfaces)")

    print("\n[INFO] Complete job!")
    print("\n"+"-"*60)
    print(color_text("Density mapped. I am your density (destiny).\n\n", 'bold'))

if __name__ == "__main__":
    main()
