#!/usr/bin/env python3

#################################################
#     Siesta Tool Box - Elastic Properties      #
#     Analyzer Module (2D/3D Support)           #
#     Integrated Style Refactoring              #
#################################################

VERSION = "1.10.0" # --dimensionality (auto 3D/2D/1D detection + manual override) replaces --2d

import os
import sys
import argparse
import re
import numpy as np
from time import sleep
from datetime import datetime
from scipy.stats import linregress
from stb.core import kspace, siesta_log, structure_io, symmetry
from stb.core.cli import COLORS, color_text, show_intro, print_dual, print_section

# ==========================================
#           HELPERS & CONFIG
# ==========================================

CONV_EVA3_TO_GPA = 160.21766
CONV_EVA2_TO_NM = 16.021766
# Same physical constant as the two above (1 eV/Ang^3 = 160.21766 GPa), one
# more power of Angstrom down: a 1D wire/tube's meaningful stiffness is a
# force (energy/length), not a stress -- reported in nN since real
# nanowire/nanotube axial stiffnesses land in that range (see
# check_stability_and_report's 1D branch).
CONV_EVA1_TO_NN = 1.6021766
UNIT_LABELS = {"3d": "GPa", "2d": "N/m", "1d": "nN"}
# Which of the 6 canonical Voigt directions are even physically accessible
# per dimensionality -- the other 5 always touch a vacuum-padded axis and
# are structurally never generated by stb-elasticInputs, so reports
# shouldn't advise "run the missing ones" for directions that can't exist.
RELEVANT_DIRECTIONS = {
    "3d": {'xx', 'yy', 'zz', 'xy', 'xz', 'yz'},
    "2d": {'xx', 'yy', 'xy'},
    "1d": {'zz'},
}
REPORT_FILE = "mechanical_properties.txt"

# Voigt index (0-based, 1..6 in the usual 1-based convention) -> Cartesian
# stress-tensor (row, col). Matches this module's existing convention
# (4=yz, 5=xz, 6=xy). Single source of truth in core/symmetry.py, shared
# with its "full" (tensor-invariance) symmetry method.
VOIGT_TO_TENSOR = symmetry.VOIGT_TO_TENSOR
# Which Voigt *column* each strain_inputs.py direction populates -- applying
# a single-component strain e_k (the k-th canonical Voigt unit strain) gives
# the k-th column of C directly, via sigma = C . epsilon (Hooke's law).
DIRECTION_TO_COLUMN = {'xx': 0, 'yy': 1, 'zz': 2, 'yz': 3, 'xz': 4, 'xy': 5}
DIRECTION_LABELS = {0: 'xx', 1: 'yy', 2: 'zz', 3: 'yz', 4: 'xz', 5: 'xy'}
# Shear directions are generated as *tensor* strain (eps_yz=delta), which is
# HALF the Voigt engineering strain (gamma_yz=2*delta) -- any constant read
# out of a shear column needs this correction, not just the diagonal C44/
# C55/C66 (verified by hand-derivation and a synthetic-matrix numerical
# check before implementing: max error 3e-14 recovering a known 21-constant
# triclinic tensor, including the off-diagonal coupling terms).
SHEAR_DIRECTIONS = {'yz', 'xz', 'xy'}

# ==========================================
#           DATA MINING LOGIC
# ==========================================

def linear_fit_diagnostics(x, y, factor):
    """Full linregress result for one stress-vs-strain series, scaled by
    `factor` (same convention as calculate_slope): (slope, intercept,
    r_squared). `intercept` is the fit's predicted stress at zero strain --
    should be ~0 for a well-relaxed reference structure, the stress-side
    analogue of _fit_energy_pattern's linear-energy-term check. `r_squared`
    flags a noisy or non-linear (too-large-strain) series. Both come for
    free out of the same linregress call calculate_slope already made and
    used to discard -- see direction_fit_diagnostics below, the first
    caller that actually uses them.
    """
    if len(x) < 2: return 0.0, 0.0, 0.0
    slope, intercept, r_value, _p_value, _std_err = linregress(x, y)
    return slope * factor, intercept * factor, r_value ** 2


def calculate_slope(x, y, factor):
    slope, _intercept, _r_squared = linear_fit_diagnostics(x, y, factor)
    return slope


def _canonical_elastic_direction(direction):
    """Folds every alternate spelling of the same physical strain mode onto
    one canonical key ('x'->'xx', 'zy'->'yz', 'zx'->'xz', ...), so folders
    using different naming conventions (e.g. hand-made vs. stb-elasticInputs'
    own 'xx'/'yy'/'zz'/'xy'/'xz'/'yz') merge into the same data series
    instead of one silently shadowing/discarding the other.
    """
    d = direction.lower()
    aliases = {
        'x': 'xx', 'y': 'yy', 'z': 'zz',
        'zy': 'yz', 'zx': 'xz', 'yx': 'xy',
    }
    return aliases.get(d, d)

def _fit_column(eps_list, stress_list, conv_factor, is_shear):
    """Fits one full Voigt column (all 6 stress components against the same
    strain series) -- a single-component strain e_k gives sigma = C[:,k]
    directly (Hooke's law), so this recovers the whole column from one
    strain series' full 3x3 stress response, not just the "obvious" entry.
    """
    factor = conv_factor / 2.0 if is_shear else conv_factor
    S = np.array(stress_list)
    col = np.zeros(6)
    for row, (i, j) in enumerate(VOIGT_TO_TENSOR):
        col[row] = calculate_slope(eps_list, S[:, i, j], factor)
    return col


def compute_stiffness_matrix(data, conv_factor, symmetry_info, unit_label, f_out):
    """Builds the (unsymmetrized) 6x6 stiffness matrix from `data`
    ({direction: {'eps': [...], 'stress': [3x3 arrays]}}).

    Without symmetry_info (or wherever it doesn't apply), behaves exactly
    like the original per-direction independent fit. With symmetry_info
    ((groups, point_group, ops) from core/symmetry.py::equivalent_strain_modes),
    every mode m in a group is fit from the POOLED contribution of every
    *present* mode p in that same group, each rotated into m's frame via
    core/symmetry.py::find_mapping_operation (p==m uses the identity) --
    this uniformly covers all 3 cases:
      - only 1 mode in the group present: the others are reconstructed
        purely from that one (the DFT-cost reduction stb-elasticInputs'
        'all' default now performs).
      - 2+ modes present: each gets a MORE PRECISE pooled fit incorporating
        every equivalent measurement, not just its own -- a diagnostic
        comparing the independent (pre-pooling) values is printed first.
      - 0 modes present: genuinely missing, left as 0.

    Returns (C, filled_by_symmetry, missing_directions): `filled_by_symmetry`
    lists directions whose column came only from a symmetry-equivalent
    sibling (no direct DFT data of their own); `missing_directions` lists
    directions with no data at all, even after pooling.
    """
    C = np.zeros((6, 6))
    filled_by_symmetry = []
    missing_directions = []

    if symmetry_info is not None:
        groups, point_group, ops = symmetry_info
    else:
        groups, point_group, ops = [[m] for m in DIRECTION_TO_COLUMN], None, []

    for group in groups:
        present = [m for m in group if m in data]
        if not present:
            missing_directions.extend(group)
            continue

        if len(present) > 1:
            print_dual(f"{color_text('[DIAGNOSTIC]', 'cyan')} {present} are symmetry-equivalent "
                       f"(point group {point_group}) -- independent fits before combining:", f_out)
            for m in present:
                own_col = _fit_column(data[m]['eps'], data[m]['stress'], conv_factor,
                                       m in SHEAR_DIRECTIONS)
                print_dual(f"      {m}: {own_col[DIRECTION_TO_COLUMN[m]]:.2f} {unit_label} "
                           "(independent, pre-pooling)", f_out)

        for m in group:
            pooled_eps, pooled_stress = [], []
            for p in present:
                if p == m:
                    R, sign = np.eye(3), 1
                else:
                    R, sign = symmetry.find_mapping_operation(ops, p, m)
                if R is None:
                    continue
                pooled_eps.extend(data[p]['eps'])
                pooled_stress.extend(symmetry.transform_stress(R, sign, S) for S in data[p]['stress'])
            if not pooled_eps:
                missing_directions.append(m)
                continue
            C[:, DIRECTION_TO_COLUMN[m]] = _fit_column(
                pooled_eps, pooled_stress, conv_factor, m in SHEAR_DIRECTIONS)
            if m not in present:
                filled_by_symmetry.append(m)
            elif len(present) > 1:
                print_dual(f"{color_text('[DIAGNOSTIC]', 'cyan')}   -> {m} combined "
                           f"({len(pooled_eps)} pooled points): "
                           f"{C[DIRECTION_TO_COLUMN[m], DIRECTION_TO_COLUMN[m]]:.2f} {unit_label}", f_out)

    return C, filled_by_symmetry, missing_directions


def compute_stiffness_matrix_full(data, conv_factor, pmg_structure, symprec, angle_tolerance,
                                   unit_label, f_out):
    """The "full" symmetry method: constrains C a priori to the subspace
    allowed by the structure's point group (core/symmetry.py::
    symmetry_allowed_basis), then fits every basis coefficient in one
    least-squares solve over every measured (strain, stress) point from
    every direction actually run (core/symmetry.py::fit_stiffness_matrix).

    Unlike compute_stiffness_matrix (the "basic" method) above, this
    catches reductions like hexagonal's C11=C22 that a pairwise
    strain-TENSOR correspondence can never see (see the module docstring
    in core/symmetry.py) -- verified to reproduce the same cubic-fixture
    result as the basic method, and to additionally reduce/reconstruct
    correctly for the hexagonal 2D fixture, where the basic method finds no
    equivalence at all.

    'bi'/'hydro' data (stb-elasticInputs' 2 convenience modes outside the 6
    canonical Voigt modes) can't be expressed as one of core/symmetry.py's
    strain_tensor modes and are silently skipped here -- the same
    limitation the basic method already has (DIRECTION_TO_COLUMN has no
    entry for them either).

    Returns (C, point_group, num_independent, directions_used,
    reconstructed_directions, achieved_rank): `reconstructed_directions`
    lists directions with no data at all (mirrors "filled_by_symmetry" in
    the basic path); `achieved_rank` is how many of the `num_independent`
    constants the directions actually run determine (< num_independent
    means the fit below is underdetermined for at least some constants --
    left to the caller to decide whether that matters, since e.g. in 2D
    mode the undetermined constants are typically the out-of-plane ones
    the report never shows anyway).
    """
    basis, point_group = symmetry.symmetry_allowed_basis(pmg_structure, symprec, angle_tolerance)

    points = []
    directions_used = []
    for mode in symmetry.VOIGT_MODES:
        if mode not in data:
            continue
        directions_used.append(mode)
        for delta, S in zip(data[mode]['eps'], data[mode]['stress']):
            points.append((symmetry.strain_tensor(mode, delta), S))

    if not points:
        return np.zeros((6, 6)), point_group, len(basis), [], list(symmetry.VOIGT_MODES), 0

    # Rank check: do the directions actually run even span the symmetry
    # -allowed subspace? If not, the least-squares solve below is genuinely
    # underdetermined for some constants (numpy silently returns the
    # minimum-norm solution, which would otherwise look like a normal
    # result) -- the caller decides whether/how to warn about this.
    blocks = [np.array([Bk @ symmetry.voigt_strain_engineering(symmetry.strain_tensor(mode))
                         for Bk in basis]).T
              for mode in directions_used]
    achieved_rank = np.linalg.matrix_rank(np.vstack(blocks), tol=1e-8) if blocks else 0

    C = symmetry.fit_stiffness_matrix(basis, points, conv_factor)
    reconstructed = [m for m in symmetry.VOIGT_MODES if m not in data]
    return C, point_group, len(basis), directions_used, reconstructed, achieved_rank


def _parse_energy_folder_name(folder):
    """Parses strain_<pattern>_<magnitude> folder names written by
    stb-elasticInputs --method energy, where <pattern> is a pure Voigt mode
    ('xx') or a combined one ('xx+yy'). Returns (pattern, strain_percent),
    or (None, None) if the folder doesn't match this convention.
    """
    m = re.match(r"^strain_([a-z]+(?:\+[a-z]+)*)_(m?)(\d+\.\d+)$", folder)
    if not m:
        return None, None
    pattern, sign, val = m.group(1), m.group(2), float(m.group(3))
    return pattern, (-val if sign == 'm' else val)


def pattern_strain_tensor(pattern):
    """Unit (delta=1) strain tensor for a pure or combined ('xx+yy') Voigt
    pattern name -- same convention as
    core/symmetry.py::energy_pattern_candidates.
    """
    return sum((symmetry.strain_tensor(part) for part in pattern.split('+')), np.zeros((3, 3)))


def _fit_energy_pattern(pattern, deltas, energies, f_out):
    """Fits a quadratic (np.polyfit) to one pattern's energy-vs-strain
    series, warning (but not blocking) about the two failure modes any
    caller needs to handle the same way: too few points, or a non
    -negligible linear term (see compute_stiffness_matrix_energy's
    docstring on both). Shared by compute_stiffness_matrix_energy and
    eggbox_cross_check below, so the two never drift on this logic.

    Returns (a, b, c) -- the quadratic, linear and constant polyfit
    coefficients (c kept, unlike earlier, so write_energy_plots can draw
    the exact fitted curve f(x)=a*x^2+b*x+c against the actual absolute
    energies, not just a relative shape) -- or None if there weren't enough
    points to fit.
    """
    if len(deltas) < 3:
        print_dual(color_text(
            f"[WARNING] Pattern '{pattern}' has fewer than 3 points -- skipped (a quadratic "
            "fit needs at least 3).", 'yellow'), f_out)
        return None

    a, b, c = np.polyfit(deltas, energies, 2)
    # Linear term should be ~0 at a well-relaxed equilibrium reference; a
    # large one signals residual internal stress/forces in
    # reference_structure.fdf. Compares the two terms' actual CONTRIBUTION
    # at the largest strain magnitude run, not the raw coefficients (b
    # eV/strain vs a eV/strain^2 aren't on the same scale to begin with --
    # comparing them directly would flag every pattern, or none, regardless
    # of whether the linear term is actually significant at the strains
    # used).
    delta_scale = max(abs(d) for d in deltas)
    if abs(a) > 1e-8 and abs(b) > 0.1 * abs(a) * delta_scale:
        print_dual(color_text(
            f"[WARNING] Pattern '{pattern}': linear energy term ({b:.2e} eV) is not "
            f"negligible next to the quadratic term ({a:.2e} eV) at the strains used -- the "
            "reference structure may not be fully relaxed.", 'yellow'), f_out)
    return a, b, c


def compute_stiffness_matrix_energy(folders, file_name, pmg_structure, symprec, angle_tolerance,
                                     dimensionality, conv_factor, unit_label, f_out):
    """The energy-strain ("parabolic fit") method: fits a quadratic to
    total energy vs. strain magnitude for every strain_<pattern>_* series
    found (pure and/or combined Voigt patterns -- combined patterns are
    physically required for off-diagonal constants, see
    core/symmetry.py's energy-method module note), then solves for the
    elastic tensor in one least-squares pass constrained to the point
    group's symmetry-allowed subspace (core/symmetry.py::
    fit_stiffness_matrix_energy) -- the energy-method equivalent of
    compute_stiffness_matrix_full above.

    `conv_factor` must already be the right eV/Ang^n -> GPa/N/m/nN factor
    for the volume/area/length normalization already folded into `target`
    below (CONV_EVA3_TO_GPA for 3D, plain CONV_EVA2_TO_NM for 2D, plain
    CONV_EVA1_TO_NN for 1D -- no Lz/cross-section correction: unlike
    stress, which SIESTA reports as a volumetric quantity diluted by the
    vacuum gap, total energy is already extensive and needs no such
    correction, just the in-plane area or axial length).

    Returns (C, point_group, num_independent, directions_used,
    achieved_rank, series, fit_coeffs). `series` ({pattern: {'delta': [...],
    'energy': [...]}}) and `fit_coeffs` ({pattern: (a, b, c)}, the raw
    polyfit coefficients) are the same raw data/fit this function already
    computed internally to build C -- returned so write_energy_plots can
    write the gnuplot data+fit files without re-reading calc.out or
    re-triggering _fit_energy_pattern's warnings a second time.
    """
    basis, point_group = symmetry.symmetry_allowed_basis(pmg_structure, symprec, angle_tolerance)
    lat = pmg_structure.lattice.matrix
    if dimensionality == "2d":
        norm_factor = np.linalg.norm(np.cross(lat[0], lat[1]))  # in-plane area (Ang^2)
    elif dimensionality == "1d":
        norm_factor = np.linalg.norm(lat[2])  # axial length (Ang), wire along c
    else:
        norm_factor = pmg_structure.volume  # Ang^3

    series = {}
    for folder in folders:
        pattern, strain_pct = _parse_energy_folder_name(folder)
        if pattern is None:
            continue
        energy = siesta_log.get_free_energy(os.path.join(folder, file_name))
        if energy is None:
            continue
        series.setdefault(pattern, {'delta': [], 'energy': []})
        series[pattern]['delta'].append(strain_pct / 100.0)
        series[pattern]['energy'].append(energy)

    pattern_targets = []
    directions_used = []
    gammas = []
    fit_coeffs = {}
    for pattern, s in series.items():
        fit = _fit_energy_pattern(pattern, s['delta'], s['energy'], f_out)
        if fit is None:
            continue
        a, b, c = fit
        fit_coeffs[pattern] = (a, b, c)
        eps_unit = pattern_strain_tensor(pattern)
        gamma = symmetry.voigt_strain_engineering(eps_unit)
        target = 2 * a / norm_factor
        pattern_targets.append((eps_unit, target))
        directions_used.append(pattern)
        gammas.append(gamma)

    if not pattern_targets:
        return np.zeros((6, 6)), point_group, len(basis), [], 0, series, fit_coeffs

    blocks = [[gamma @ Bk @ gamma for Bk in basis] for gamma in gammas]
    achieved_rank = np.linalg.matrix_rank(np.array(blocks), tol=1e-8)

    C = symmetry.fit_stiffness_matrix_energy(basis, pattern_targets, conv_factor)
    return C, point_group, len(basis), directions_used, achieved_rank, series, fit_coeffs


def eggbox_cross_check(data, folders, file_name, pmg_structure, dimensionality, conv_factor, tolerance, f_out):
    """Cross-checks each diagonal elastic constant C_mm two independent
    ways from the SAME strain_<mode>_* folders stb-elasticInputs --method
    stress already generated -- no new DFT calculations: the stress-linear
    fit already in `data` (see main()), and a parabolic fit of total energy
    vs. strain re-read from the same calc.out files. In the exact continuum
    limit sigma(delta) = dE/d(delta)/V0, so for a perfectly converged
    calculation the two must agree EXACTLY -- any real disagreement signals
    numerical contamination, and SIESTA's real-space-grid "eggbox effect"
    is a prime suspect: it typically disturbs stress/forces (derivative
    -like quantities, evaluated on the discretized grid) more than total
    energy (comparatively smooth), so a discrepancy concentrated on the
    stress side is exactly the expected fingerprint.

    Limited to DIAGONAL constants (C_mm): a pure single-Voigt-component
    strain's energy curvature is structurally blind to off-diagonal terms
    (see core/symmetry.py's energy-method module note) -- getting those
    from energy would need combined patterns, i.e. new DFT runs, exactly
    what this check must avoid.

    Compares against the DIRECTION'S OWN stress fit (core/symmetry.py::
    fit_stiffness_matrix's pooling/reconstruction across symmetry
    -equivalent directions is deliberately bypassed here via _fit_column
    directly), not the final (possibly pooled/reconstructed) C_sym entry
    -- otherwise a disagreement could just mean "this direction's data
    differs from its symmetry-equivalent siblings", not "stress vs. energy
    disagree on the same data".

    Returns a list of dicts, one per direction with both stress and energy
    data available: {'mode', 'stress_value', 'energy_value', 'diff_pct',
    'flagged'}.
    """
    lat = pmg_structure.lattice.matrix
    if dimensionality == "2d":
        norm_factor = np.linalg.norm(np.cross(lat[0], lat[1]))  # in-plane area (Ang^2)
    elif dimensionality == "1d":
        norm_factor = np.linalg.norm(lat[2])  # axial length (Ang), wire along c
    else:
        norm_factor = pmg_structure.volume  # Ang^3

    energy_series = {}
    for folder in folders:
        direction, val = siesta_log.parse_strain_folder_name(folder)
        if direction is None:
            continue
        direction = _canonical_elastic_direction(direction)
        if direction not in data:
            continue  # only cross-check directions actually used by the stress fit
        energy = siesta_log.get_free_energy(os.path.join(folder, file_name))
        if energy is None:
            continue
        energy_series.setdefault(direction, {'delta': [], 'energy': []})
        energy_series[direction]['delta'].append(val / 100.0)
        energy_series[direction]['energy'].append(energy)

    results = []
    for mode in symmetry.VOIGT_MODES:
        if mode not in data or mode not in energy_series:
            continue
        fit = _fit_energy_pattern(mode, energy_series[mode]['delta'], energy_series[mode]['energy'], f_out)
        if fit is None:
            continue
        a, _b, _c = fit
        # E(delta) = (V0/2) * gamma(delta)^T C gamma(delta); for a PURE
        # mode gamma has one nonzero entry, gamma_unit_m = 2 for shear
        # (engineering strain doubles tensor shear strain, same convention
        # as SHEAR_DIRECTIONS/_fit_column elsewhere in this file) or 1 for
        # normal -- so a (the delta^2 polyfit coefficient) = (V0/2) *
        # gamma_unit_m^2 * C_mm, and C_mm = 2*a / (V0 * gamma_unit_m^2).
        # Squaring the shear factor (not just doubling it, like the stress
        # method's SHEAR_DIRECTIONS correction) is the one place this
        # differs from the stress side -- missing it here silently
        # inflated shear constants by 4x in initial testing.
        gamma_unit_m = 2.0 if mode in SHEAR_DIRECTIONS else 1.0
        energy_value = (2 * a / (norm_factor * gamma_unit_m ** 2)) * conv_factor

        own_col = _fit_column(data[mode]['eps'], data[mode]['stress'], conv_factor, mode in SHEAR_DIRECTIONS)
        stress_value = own_col[DIRECTION_TO_COLUMN[mode]]

        if abs(stress_value) > 1e-6:
            diff_pct = 100.0 * abs(stress_value - energy_value) / abs(stress_value)
        else:
            diff_pct = 0.0 if abs(energy_value) < 1e-6 else float('inf')

        results.append({
            'mode': mode,
            'stress_value': stress_value,
            'energy_value': energy_value,
            'diff_pct': diff_pct,
            'flagged': diff_pct > tolerance,
        })
    return results


def direction_fit_diagnostics(data, conv_factor, r_squared_tolerance):
    """Per-direction quality diagnostics for the stress-linear fit, using
    ONLY the direction's own diagonal stress component (e.g. 'xx' -> the
    (0,0) stress component) -- the physically relevant quantity to judge;
    the other 5 components of the same column are often ~0 by symmetry, so
    R^2/intercept there would be dominated by noise around zero rather than
    signal. Reuses linear_fit_diagnostics, whose intercept/r_squared were
    already being computed and thrown away by every _fit_column call before
    this function existed (see linear_fit_diagnostics's docstring).

    Returns a list of dicts, one per direction in `data`: {'mode', 'slope',
    'r_squared', 'residual_stress', 'flagged'}. `slope` is the fitted C_mm
    itself (already returned elsewhere as part of C, but kept here too so
    write_stress_plots can draw the exact same fit line without redoing the
    regression). `flagged` is set for either a non-negligible residual
    stress (same relative-contribution-at-max-strain criterion as
    _fit_energy_pattern's linear-term check, applied here to the
    stress-fit's intercept instead) or R^2 below `r_squared_tolerance`.
    """
    results = []
    for mode, series in data.items():
        if mode not in symmetry.VOIGT_MODES:
            continue  # 'bi'/'hydro' aren't single Voigt components -- no single diagonal to check
        i, j = VOIGT_TO_TENSOR[DIRECTION_TO_COLUMN[mode]]
        S = np.array(series['stress'])
        y = S[:, i, j]
        factor = conv_factor / 2.0 if mode in SHEAR_DIRECTIONS else conv_factor
        slope, intercept, r_squared = linear_fit_diagnostics(series['eps'], y, factor)
        if len(series['eps']) < 2:
            continue

        delta_scale = max(abs(d) for d in series['eps'])
        residual_flagged = abs(slope) > 1e-8 and abs(intercept) > 0.1 * abs(slope) * delta_scale
        r2_flagged = r_squared < r_squared_tolerance
        results.append({
            'mode': mode,
            'slope': slope,
            'r_squared': r_squared,
            'residual_stress': intercept,
            'flagged': residual_flagged or r2_flagged,
        })
    return results


def tensor_symmetry_check(C):
    """C_ij == C_ji is a thermodynamic identity (not a numerical
    convenience) -- for --symmetry-method basic, C[i,j] and C[j,i] can come
    from two DIFFERENT DFT directions' independent fits, so a large
    discrepancy is a real inconsistency signal (different residual state
    between the two reference structures, incomplete relaxation, etc.),
    otherwise silently averaged away by the C_sym = 0.5*(C+C.T)
    symmetrization every caller does anyway. Only meaningful there: --full
    (core/symmetry.py::fit_stiffness_matrix/fit_stiffness_matrix_energy)
    builds C as a linear combination of symmetry_allowed_basis matrices,
    which are already exactly symmetric by construction, so max|C-C.T|
    would always read ~0 there regardless of data quality -- callers should
    only invoke this for the basic method (see main()).

    Returns (max_diff, i, j, flagged) -- the largest |C[i,j] - C[j,i]|, its
    (0-based) position, and whether it exceeds 1% of the matrix's own
    largest entry. A relative (not absolute) threshold, since C's raw scale
    depends on the unit (~100s GPa in 3D, ~10-100s N/m in 2D) -- a fixed
    absolute cutoff would be arbitrary across the two.
    """
    diff = np.abs(C - C.T)
    idx = np.unravel_index(np.argmax(diff), diff.shape)
    max_diff = diff[idx]
    scale = np.max(np.abs(C))
    flagged = scale > 1e-6 and max_diff > 0.01 * scale
    return max_diff, idx[0], idx[1], flagged


# ==========================================
#           GNUPLOT EXPORT
#
# Same data+.gplot convention used throughout the suite (e.g.
# strain_analysis.py::write_strain_gplot/write_compare_gplot, the closest
# sibling tool -- stb-strainAnalysis's own stress-strain curve fit): a
# commented .dat file (gnuplot 'index' blocks) + a companion .gplot
# (pdfcairo terminal, the fit drawn as a gnuplot f(x)=... function rather
# than duplicated as data points). No new DFT calculations or re-fitting --
# every number here was already computed by the caller.
# ==========================================

PLOT_COLORS = ['#2255cc', '#cc5522', '#22aa55', '#aa22aa', '#aaaa22', '#22aaaa',
               '#cc2266', '#66cc22', '#2266cc', '#cc6622', '#8822cc', '#22cc88']


def write_stress_plots(plot_dir, data, fit_diagnostics, conv_factor, unit_label, f_out):
    """Writes one <mode>_fit.dat + <mode>_fit.gplot per direction actually
    measured (stress-strain linear fit: sigma = C_mm . gamma), plus a
    combined all_directions_fit.dat/.gplot overlaying every direction.
    Reuses fit_diagnostics's already-computed slope/intercept/R^2 (see
    direction_fit_diagnostics) instead of re-fitting.

    Data columns use ENGINEERING strain (gamma = 2*eps for shear modes,
    same convention Hooke's law/the reported C_mm itself use) rather than
    the raw tensor strain stb-elasticInputs applies, so the plotted slope
    matches the reported C_mm directly -- also all 6 measured stress
    components are written (not just the direction's own diagonal one),
    since a single strain series already gives a full column of C (see
    _fit_column) and someone plotting by hand may want any of them.

    Returns the list of (mode, dat_path, gplot_path) written.
    """
    fit_by_mode = {r['mode']: r for r in fit_diagnostics}
    modes = [m for m in symmetry.VOIGT_MODES if m in data and m in fit_by_mode]
    written = []

    combined_dat = os.path.join(plot_dir, "all_directions_fit.dat")
    combined_gplot = os.path.join(plot_dir, "all_directions_fit.gplot")
    combined_f = open(combined_dat, 'w')
    combined_lines = [
        '# --- STB Plot Configuration ---\n',
        '# Generated by stb-elasticAnalysis (--method stress)\n',
        'set terminal pdfcairo enhanced color font "Arial,14" size 8,6\n',
        'set output "all_directions_fit.pdf"\n\n',
        'set title "Stress-Strain Fits -- All Directions"\n',
        'set xlabel "Engineering strain (fraction)"\n',
        f'set ylabel "Stress ({unit_label})"\n',
        'set grid\n',
        'set key top left\n',
    ]
    combined_plot_parts = []

    for i, mode in enumerate(modes):
        series = data[mode]
        fit = fit_by_mode[mode]
        is_shear = mode in SHEAR_DIRECTIONS
        eng_factor = 2.0 if is_shear else 1.0
        S = np.array(series['stress'])
        diag_col = DIRECTION_TO_COLUMN[mode]

        dat_path = os.path.join(plot_dir, f"{mode}_fit.dat")
        with open(dat_path, 'w') as f:
            f.write(f"# stb-elasticAnalysis -- stress-strain data for direction '{mode}'\n")
            f.write(f"# Fit: C_{mode} = {fit['slope']:.4f} {unit_label}, "
                    f"R^2 = {fit['r_squared']:.6f}, residual stress = "
                    f"{fit['residual_stress']:.4f} {unit_label}\n")
            f.write("# columns: 1=Strain(%) 2=EngineeringStrain(frac) "
                     f"3=sigma_xx 4=sigma_yy 5=sigma_zz 6=sigma_yz 7=sigma_xz 8=sigma_xy [{unit_label}]\n")
            for eps, s in zip(series['eps'], S):
                row = [conv_factor * s[i2, j2] for (i2, j2) in VOIGT_TO_TENSOR]
                f.write(f"{eps*100:12.6f}  {eps*eng_factor:12.6f}  " +
                        "  ".join(f"{v:12.6f}" for v in row) + "\n")

        diag_data_col = 3 + diag_col  # gnuplot column number of this direction's own diagonal entry
        gplot_path = os.path.join(plot_dir, f"{mode}_fit.gplot")
        lines = [
            '# --- STB Plot Configuration ---\n',
            '# Generated by stb-elasticAnalysis (--method stress)\n',
            'set terminal pdfcairo enhanced color font "Arial,14" size 7,5\n',
            f'set output "{mode}_fit.pdf"\n\n',
            f'set title "Stress-Strain Fit: {mode.upper()} direction (C_{mode} = '
            f'{fit["slope"]:.2f} {unit_label}, R^2={fit["r_squared"]:.5f})"\n',
            'set xlabel "Engineering strain (fraction)"\n',
            f'set ylabel "sigma_{mode} ({unit_label})"\n',
            'set grid\n',
            'set key top left\n',
            f"f(x) = {fit['slope']:.8f}*x + {fit['residual_stress']:.8f}\n",
            (f'plot "{mode}_fit.dat" using 2:{diag_data_col} with points pt 7 ps 1.3 '
             f'lc rgb "{PLOT_COLORS[i % len(PLOT_COLORS)]}" title "sigma_{mode} data", \\\n'
             f'     f(x) with lines lc rgb "{PLOT_COLORS[i % len(PLOT_COLORS)]}" dt 2 '
             'title "Linear fit"\n'),
        ]
        with open(gplot_path, 'w') as f:
            f.writelines(lines)

        print_dual(f"{color_text('[Saved]', 'cyan')} {dat_path}, {gplot_path} "
                    f"(cd {plot_dir} && gnuplot {os.path.basename(gplot_path)})", f_out)
        written.append((mode, dat_path, gplot_path))

        # Combined overview: append this direction's own block to the
        # shared data file and one more overlay to the shared plot.
        if i > 0:
            combined_f.write("\n\n")
        combined_f.write(f"# index {i}: {mode} (own diagonal component)\n")
        combined_f.write("# Strain(%) EngineeringStrain(frac) sigma\n")
        for eps, s in zip(series['eps'], S):
            i2, j2 = VOIGT_TO_TENSOR[diag_col]
            combined_f.write(f"{eps*100:12.6f}  {eps*eng_factor:12.6f}  "
                              f"{conv_factor*s[i2, j2]:12.6f}\n")
        color = PLOT_COLORS[i % len(PLOT_COLORS)]
        combined_lines.append(f"f_{i}(x) = {fit['slope']:.8f}*x + {fit['residual_stress']:.8f}\n")
        combined_plot_parts.append(
            f'"all_directions_fit.dat" index {i} using 2:3 with points pt 7 ps 1.2 '
            f'lc rgb "{color}" title "{mode.upper()}"')
        combined_plot_parts.append(f'f_{i}(x) with lines lc rgb "{color}" dt 2 notitle')

    combined_f.close()
    if modes:
        combined_lines.append('plot ' + ', \\\n     '.join(combined_plot_parts) + '\n')
        with open(combined_gplot, 'w') as f:
            f.writelines(combined_lines)
        print_dual(f"{color_text('[Saved]', 'cyan')} {combined_dat}, {combined_gplot} "
                    f"(cd {plot_dir} && gnuplot {os.path.basename(combined_gplot)})", f_out)
        written.append(('all', combined_dat, combined_gplot))
    else:
        os.remove(combined_dat)

    return written


def write_energy_plots(plot_dir, series, fit_coeffs, unit_label, f_out):
    """Energy-method equivalent of write_stress_plots: one
    <pattern>_fit.dat + <pattern>_fit.gplot per pattern (pure or combined
    Voigt strain, e.g. 'xx' or 'xx+yy'), fit overlaid as a gnuplot quadratic
    function f(x)=a*x^2+b*x+c instead of a line, plus a combined overview.
    `series`/`fit_coeffs` are exactly what compute_stiffness_matrix_energy
    already computed internally -- no re-reading calc.out, no re-fitting.

    Returns the list of (pattern, dat_path, gplot_path) written.
    """
    patterns = [p for p in series if p in fit_coeffs]
    written = []

    combined_dat = os.path.join(plot_dir, "all_patterns_fit.dat")
    combined_gplot = os.path.join(plot_dir, "all_patterns_fit.gplot")
    combined_f = open(combined_dat, 'w')
    combined_lines = [
        '# --- STB Plot Configuration ---\n',
        '# Generated by stb-elasticAnalysis (--method energy)\n',
        'set terminal pdfcairo enhanced color font "Arial,14" size 8,6\n',
        'set output "all_patterns_fit.pdf"\n\n',
        'set title "Energy-Strain Fits -- All Patterns"\n',
        'set xlabel "Strain (fraction)"\n',
        'set ylabel "Total energy (eV)"\n',
        'set grid\n',
        'set key top left\n',
    ]
    combined_plot_parts = []

    for i, pattern in enumerate(patterns):
        s = series[pattern]
        a, b, c = fit_coeffs[pattern]

        dat_path = os.path.join(plot_dir, f"{pattern}_fit.dat")
        with open(dat_path, 'w') as f:
            f.write(f"# stb-elasticAnalysis -- energy-strain data for pattern '{pattern}'\n")
            f.write(f"# Fit: E(x) = {a:.6e}*x^2 + {b:.6e}*x + {c:.6f}  [eV]\n")
            f.write("# columns: 1=Strain(%) 2=Strain(frac) 3=Energy(eV)\n")
            for delta, energy in zip(s['delta'], s['energy']):
                f.write(f"{delta*100:12.6f}  {delta:12.6f}  {energy:14.8f}\n")

        gplot_path = os.path.join(plot_dir, f"{pattern}_fit.gplot")
        lines = [
            '# --- STB Plot Configuration ---\n',
            '# Generated by stb-elasticAnalysis (--method energy)\n',
            'set terminal pdfcairo enhanced color font "Arial,14" size 7,5\n',
            f'set output "{pattern}_fit.pdf"\n\n',
            f'set title "Energy-Strain Fit: {pattern} pattern"\n',
            'set xlabel "Strain (fraction)"\n',
            'set ylabel "Total energy (eV)"\n',
            'set grid\n',
            'set key top left\n',
            f"f(x) = {a:.8e}*x**2 + {b:.8e}*x + {c:.8f}\n",
            (f'plot "{pattern}_fit.dat" using 2:3 with points pt 7 ps 1.3 '
             f'lc rgb "{PLOT_COLORS[i % len(PLOT_COLORS)]}" title "{pattern} data", \\\n'
             f'     f(x) with lines lc rgb "{PLOT_COLORS[i % len(PLOT_COLORS)]}" dt 2 '
             'title "Parabolic fit"\n'),
        ]
        with open(gplot_path, 'w') as f:
            f.writelines(lines)

        print_dual(f"{color_text('[Saved]', 'cyan')} {dat_path}, {gplot_path} "
                    f"(cd {plot_dir} && gnuplot {os.path.basename(gplot_path)})", f_out)
        written.append((pattern, dat_path, gplot_path))

        if i > 0:
            combined_f.write("\n\n")
        combined_f.write(f"# index {i}: {pattern}\n")
        combined_f.write("# Strain(%) Strain(frac) Energy(eV)\n")
        for delta, energy in zip(s['delta'], s['energy']):
            combined_f.write(f"{delta*100:12.6f}  {delta:12.6f}  {energy:14.8f}\n")
        color = PLOT_COLORS[i % len(PLOT_COLORS)]
        combined_lines.append(f"f_{i}(x) = {a:.8e}*x**2 + {b:.8e}*x + {c:.8f}\n")
        combined_plot_parts.append(
            f'"all_patterns_fit.dat" index {i} using 2:3 with points pt 7 ps 1.2 '
            f'lc rgb "{color}" title "{pattern}"')
        combined_plot_parts.append(f'f_{i}(x) with lines lc rgb "{color}" dt 2 notitle')

    combined_f.close()
    if patterns:
        combined_lines.append('plot ' + ', \\\n     '.join(combined_plot_parts) + '\n')
        with open(combined_gplot, 'w') as f:
            f.writelines(combined_lines)
        print_dual(f"{color_text('[Saved]', 'cyan')} {combined_dat}, {combined_gplot} "
                    f"(cd {plot_dir} && gnuplot {os.path.basename(combined_gplot)})", f_out)
        written.append(('all', combined_dat, combined_gplot))
    else:
        os.remove(combined_dat)

    return written


# ==========================================
#           REPORTING LOGIC
# ==========================================

def check_stability_and_report(C, dimensionality, unit_label, f_out):
    """Returns `summary`, a dict of the final derived properties + verdict
    already printed here -- so callers (see the [5] SUMMARY & FILES section
    in emit_elastic_report) can recap them without recomputing.
    """
    print_section('[4] STABILITY AND PROPERTIES', f_out)

    passes = False
    summary = {}

    if dimensionality == "1d":
        # A 1D wire/tube has only ONE physically accessible constant: the
        # axial stiffness along the periodic (wire) axis -- the 2 transverse
        # directions are vacuum-padded, so no transverse stress/Poisson
        # response is even defined (see RELEVANT_DIRECTIONS). No Born
        # criteria system exists for 1D the way it does for 2D/3D; the only
        # stability requirement is the axial stiffness itself being positive.
        c33 = C[2, 2]
        print_dual(f"Axial Stiffness (C33, along periodic axis): "
                   f"{color_text(f'{c33:.4f}', 'bold')} {unit_label}", f_out)
        passes = c33 > 0
        print_dual(f"\n1D Stability Criterion:", f_out)
        print_dual(f"  C33 > 0         : {color_text('PASS', 'green') if passes else color_text('FAIL', 'red')}", f_out)
        summary = {'C33': c33}

    elif dimensionality == "2d":
        # 2D Constants Extraction
        c11, c22, c12, c66 = C[0,0], C[1,1], C[0,1], C[5,5]
        
        # In-plane Properties (2D Orthorhombic Formulas)
        denom = (c11 * c22 - c12**2)
        Ex_2d = denom / c22 if c22 > 0 else 0
        Ey_2d = denom / c11 if c11 > 0 else 0
        
        # Poisson's Ratio -- derived from 2D Hooke's law under uniaxial stress
        # (sigma_2=0 => eps_2=-(C12/C22)*eps_1, so nu_yx=-eps_2/eps_1=C12/C22;
        # by symmetry nu_xy=C12/C11). Cross-checked against the reciprocal
        # (Maxwell-Betti) relation nu_yx/Ex == nu_xy/Ey, which only holds
        # with this pairing, not the swapped one.
        nu_yx = c12 / c22 if c22 > 0 else 0  # strain in y per strain in x, stress along x (pairs with Ex)
        nu_xy = c12 / c11 if c11 > 0 else 0  # strain in x per strain in y, stress along y (pairs with Ey)

        print_dual(f"In-Plane Stiffness (Layer Modulus - Ex): {color_text(f'{Ex_2d:.2f}', 'bold')} {unit_label}", f_out)
        print_dual(f"In-Plane Stiffness (Layer Modulus - Ey): {color_text(f'{Ey_2d:.2f}', 'bold')} {unit_label}", f_out)
        print_dual(f"Poisson's Ratio (v_yx)                 : {color_text(f'{nu_yx:.3f}', 'bold')}", f_out)
        print_dual(f"Poisson's Ratio (v_xy)                 : {color_text(f'{nu_xy:.3f}', 'bold')}", f_out)
        print_dual(f"Shear Modulus (G_xy = C66)             : {color_text(f'{c66:.2f}', 'bold')} {unit_label}", f_out)
        print_dual("", f_out)

        # 2D Born Criteria
        cond1 = c11 > 0
        cond2 = c66 > 0
        cond3 = denom > 0
        passes = cond1 and cond2 and cond3
        
        print_dual(f"2D Stability Criteria (Born):", f_out)
        print_dual(f"  C11 > 0         : {color_text('PASS', 'green') if cond1 else color_text('FAIL', 'red')}", f_out)
        print_dual(f"  C66 > 0         : {color_text('PASS', 'green') if cond2 else color_text('FAIL', 'red')}", f_out)
        print_dual(f"  C11*C22 > C12^2 : {color_text('PASS', 'green') if cond3 else color_text('FAIL', 'red')}", f_out)

        summary = {
            'Ex': Ex_2d, 'Ey': Ey_2d, 'nu_yx': nu_yx, 'nu_xy': nu_xy, 'G_xy': c66,
        }

    else:
        # 3D Case (Hill Average)
        # Voigt
        B_v = (C[0,0]+C[1,1]+C[2,2] + 2*(C[0,1]+C[0,2]+C[1,2])) / 9.0
        G_v = ((C[0,0]+C[1,1]+C[2,2]) - (C[0,1]+C[0,2]+C[1,2]) + 3*(C[3,3]+C[4,4]+C[5,5])) / 15.0
        # Reuss
        try:
            S_mat = np.linalg.inv(C)
            B_r = 1.0 / ((S_mat[0,0]+S_mat[1,1]+S_mat[2,2]) + 2*(S_mat[0,1]+S_mat[0,2]+S_mat[1,2]))
            G_r = 15.0 / (4*(S_mat[0,0]+S_mat[1,1]+S_mat[2,2]) - 4*(S_mat[0,1]+S_mat[0,2]+S_mat[1,2]) + 3*(S_mat[3,3]+S_mat[4,4]+S_mat[5,5]))
        except:
            B_r, G_r = B_v, G_v
        
        # Hill
        B_h = (B_v + B_r) / 2.0
        G_h = (G_v + G_r) / 2.0
        E_h = (9 * B_h * G_h) / (3 * B_h + G_h)
        nu_h = (3 * B_h - 2 * G_h) / (2 * (3 * B_h + G_h))

        print_dual(f"Young's Modulus (E)  : {color_text(f'{E_h:.2f}', 'bold')} {unit_label}", f_out)
        print_dual(f"Bulk Modulus    (B)  : {color_text(f'{B_h:.2f}', 'bold')} {unit_label}", f_out)
        print_dual(f"Poisson's Ratio (v)  : {color_text(f'{nu_h:.3f}', 'bold')}", f_out)

        # Universal anisotropy index (Ranganathan & Ostoja-Starzewski,
        # PRL 2008) -- 0 for a perfectly isotropic elastic tensor, larger
        # for more anisotropic ones. B_v/G_v/B_r/G_r are already computed
        # above just to average into B_h/G_h; this is the same 4 numbers,
        # no new calculation, and it's the one number in this report that
        # actually says how anisotropic the material is (the Hill average
        # above is an isotropic APPROXIMATION that hides that entirely).
        A_U = None
        if G_r > 1e-9 and B_r > 1e-9:
            A_U = 5.0 * (G_v / G_r) + (B_v / B_r) - 6.0
            print_dual(f"Universal Anisotropy Index (A^U): {color_text(f'{A_U:.3f}', 'bold')} "
                       "(0 = isotropic; larger = more anisotropic)", f_out)
        else:
            print_dual(color_text(
                "[WARNING] Could not compute the universal anisotropy index (non-positive Reuss "
                "bulk/shear modulus).", 'yellow'), f_out)
        print_dual("", f_out)

        eigenvals = np.linalg.eigvals(C)
        passes = np.all(eigenvals > 0.01)

        summary = {'E': E_h, 'B': B_h, 'nu': nu_h, 'A_U': A_U}

    summary['passes'] = passes
    if passes:
        print_dual(f"\n{color_text('VERDICT:', 'bold')} {color_text('STABLE', 'green')}", f_out)
    else:
        print_dual(f"\n{color_text('VERDICT:', 'bold')} {color_text('UNSTABLE', 'red')}", f_out)

    return summary


def emit_elastic_report(args, C_sym, unit_label, filled_by_symmetry, missing_directions, f_out,
                          eggbox_results=None, fit_diagnostics=None, symmetry_check=None,
                          plot_files=None, report_path=REPORT_FILE):
    """Prints/writes the stiffness-matrix + constants + stability sections
    shared by every method (--method stress's basic/full paths and --method
    energy) -- extracted once --method energy needed to reach this same
    reporting tail from its own, separate data-mining branch in main().
    Renamed from the original _emit_elastic_report (dropped the leading
    underscore) once stb-mlelastic became a second consumer -- it only
    reads args.dimensionality/method/symmetry_method/fit_quality_tolerance/
    eggbox_tolerance/plot_dir, so any caller's argparse Namespace with those
    same attribute names works, DFT- or ML-sourced data alike; pass
    plot_files=None from a caller using its own plot format (e.g.
    stb-mlelastic's matplotlib PNGs, instead of this module's own gnuplot
    .dat/.gplot pairs) to skip the gnuplot-specific closing message.

    `eggbox_results` (see eggbox_cross_check), `fit_diagnostics` (see
    direction_fit_diagnostics) and `symmetry_check` (see
    tensor_symmetry_check) together make up section [3] NUMERICAL QUALITY
    DIAGNOSTICS -- each is independently optional (None omits that block;
    all None omits the whole section). Only ever populated for --method
    stress -- None for --method energy (not applicable) or, per block,
    when its own prerequisite wasn't available (a [WARNING] about the skip
    was already printed by the caller before reaching here) -- either way,
    never blocks the rest of the report.

    `plot_files` (see write_stress_plots/write_energy_plots) feeds the
    closing [5] SUMMARY & FILES section.

    `report_path` defaults to this module's own REPORT_FILE (elastic_
    analysis.py's own two call sites always write there unconditionally,
    unchanged behavior) -- a caller whose report is opt-in (e.g.
    stb-mlelastic's --save-report) should pass its own path, or None to
    omit the "Full report" line entirely rather than claim a file exists
    when nothing was written.
    """
    if args.dimensionality == "1d":
        # 1D REPORT -- only C33 (axial, along the periodic wire/tube axis)
        # is physically accessible (see RELEVANT_DIRECTIONS); no compliance
        # matrix or Poisson ratio, since both transverse directions are
        # vacuum-padded and have no defined stress/strain response.
        print_section('[1] 1D AXIAL STIFFNESS (' + unit_label + ')', f_out)
        print_dual(f"C33 (axial, along periodic axis) = {C_sym[2,2]:.4f} {unit_label}", f_out)

        print_section('[2] RELEVANT CONSTANTS (1D)', f_out)
        print_dual(f"{color_text('C33', 'cyan')}: {color_text(f'{C_sym[2,2]:.4f}', 'bold')} {unit_label}", f_out)

    elif args.dimensionality == "2d":
        # 2D REPORT
        print_section('[1] 2D STIFFNESS MATRIX (' + unit_label + ')', f_out)
        print_dual("      xx       yy       xy", f_out)

        indices_2d = [0, 1, 5]
        labels_2d = ["xx", "yy", "xy"]

        for r, label_r in zip(indices_2d, labels_2d):
            row_str = f"{label_r} | "
            for c in indices_2d:
                val = C_sym[r, c]
                if abs(val) < 0.01: val = 0.0
                row_str += f"{val:8.2f} "
            print_dual(row_str, f_out)

        # Compliance matrix (S = C^-1) -- just the in-plane 3x3 block
        # (xx/yy/xy), matching the 2D stiffness matrix above; gamma = S .
        # sigma is what a 2D orthotropic material's strain response to an
        # applied stress actually looks like, the inverse question from the
        # stiffness matrix.
        try:
            C_2d = C_sym[np.ix_(indices_2d, indices_2d)]
            S_2d = np.linalg.inv(C_2d)
            print_section('[1b] 2D COMPLIANCE MATRIX (m/N)', f_out)
            print_dual("      xx         yy         xy", f_out)
            for r, label_r in zip(range(3), labels_2d):
                row_str = f"{label_r} | "
                for c in range(3):
                    row_str += f"{S_2d[r, c]:10.3e} "
                print_dual(row_str, f_out)
        except np.linalg.LinAlgError:
            print_dual(color_text(
                "[WARNING] Could not invert the 2D stiffness matrix for the compliance matrix "
                "(singular).", 'yellow'), f_out)

        print_section('[2] RELEVANT CONSTANTS (2D)', f_out)
        labels_show = ["C11", "C22", "C12", "C66"]
        idx_show = [(0,0), (1,1), (0,1), (5,5)]

        buf = ""
        for l, (r, c) in zip(labels_show, idx_show):
            buf += f"{color_text(l, 'cyan')}: {color_text(f'{C_sym[r,c]:6.2f}', 'bold')} {unit_label}   "
        print_dual(buf, f_out)

    else:
        # 3D REPORT
        if abs(C_sym[2,2]) < 0.1 * abs(C_sym[0,0]) and abs(C_sym[0,0]) > 10.0:
            print_dual(f"\n{color_text('[WARNING] Material seems to be 2D (C33 << C11). Consider using --dimensionality 2d (or auto).', 'yellow')}", f_out)

        print_section('[1] 3D STIFFNESS MATRIX (' + unit_label + ')', f_out)
        header = "      " + "".join([f"{f'j={j+1}':<9}" for j in range(6)])
        print_dual(f"{header}", f_out)
        for i in range(6):
            print_dual(f"i={i+1} | " + "".join([f"{C_sym[i,j]:9.2f}" for j in range(6)]), f_out)

        # Compliance matrix (S = C^-1) -- the inverse question from the
        # stiffness matrix above (eps = S . sigma); same matrix
        # check_stability_and_report already inverts internally just to
        # get the Reuss bounds, never shown to the user until now.
        try:
            S_3d = np.linalg.inv(C_sym)
            print_section('[1b] 3D COMPLIANCE MATRIX (1/' + unit_label + ')', f_out)
            header = "      " + "".join([f"{f'j={j+1}':<11}" for j in range(6)])
            print_dual(f"{header}", f_out)
            for i in range(6):
                print_dual(f"i={i+1} | " + "".join([f"{S_3d[i,j]:10.3e} " for j in range(6)]), f_out)
        except np.linalg.LinAlgError:
            print_dual(color_text(
                "[WARNING] Could not invert the 3D stiffness matrix for the compliance matrix "
                "(singular).", 'yellow'), f_out)

        print_section('[2] MAIN CONSTANTS', f_out)
        labels = ["C11", "C22", "C33", "C44", "C55", "C66", "C12", "C13", "C23"]
        idx = [(0,0), (1,1), (2,2), (3,3), (4,4), (5,5), (0,1), (0,2), (1,2)]
        buf = ""
        for k, (l, (r, c)) in enumerate(zip(labels, idx)):
            buf += f"{l}: {C_sym[r,c]:7.1f} {unit_label}  "
            if (k+1)%3==0:
                print_dual(buf, f_out); buf=""
        if buf: print_dual(buf, f_out)

        # Normal-shear coupling constants -- only ever nonzero for
        # crystals below orthorhombic symmetry (triclinic, monoclinic,
        # some low-symmetry trigonal/tetragonal classes); shown whenever
        # any of them is numerically significant, since for higher-
        # symmetry materials they're correctly ~0 and not worth the
        # clutter.
        coupling_labels = ["C14", "C15", "C16", "C24", "C25", "C26",
                            "C34", "C35", "C36", "C45", "C46", "C56"]
        coupling_idx = [(0,3), (0,4), (0,5), (1,3), (1,4), (1,5),
                         (2,3), (2,4), (2,5), (3,4), (3,5), (4,5)]
        if any(abs(C_sym[r, c]) > 0.1 for r, c in coupling_idx):
            print_section('[2b] COUPLING CONSTANTS (normal-shear)', f_out)
            buf = ""
            for k, (l, (r, c)) in enumerate(zip(coupling_labels, coupling_idx)):
                buf += f"{l}: {C_sym[r,c]:7.1f} {unit_label}  "
                if (k+1)%3==0:
                    print_dual(buf, f_out); buf=""
            if buf: print_dual(buf, f_out)

    if filled_by_symmetry and args.method == "stress" and args.symmetry_method == "full":
        print_dual(color_text(
            f"[INFO] Direction(s) {', '.join(filled_by_symmetry)} were never run directly -- "
            "their contribution to the stiffness matrix came entirely from the point group's "
            "symmetry-allowed subspace (--symmetry-method full), fit jointly with every "
            "direction actually run.",
            'cyan'), f_out)
    elif filled_by_symmetry:
        print_dual(color_text(
            f"[INFO] Column(s) {', '.join(filled_by_symmetry)} were not computed directly -- "
            "reconstructed from a symmetry-equivalent direction (see [INFO]/[DIAGNOSTIC] lines "
            "above) via the actual point-group operation, same convention stb-elasticInputs "
            "used to skip generating them.",
            'cyan'), f_out)

    if missing_directions:
        print_dual(color_text(
            f"[INFO] No data for direction(s) {', '.join(missing_directions)} -- the "
            "stiffness-matrix column(s) they would populate (including any normal-shear "
            "coupling terms read from them) are 0 by missing data, not by symmetry. Run "
            "stb-elasticInputs with all 6 default directions (--dirs all) for a complete "
            "tensor.",
            'cyan'), f_out)

    if eggbox_results is not None or fit_diagnostics is not None or symmetry_check is not None:
        print_section('[3] NUMERICAL QUALITY DIAGNOSTICS', f_out)

    if symmetry_check is not None:
        max_diff, i, j, sym_flagged = symmetry_check
        status = color_text('WARNING', 'yellow') if sym_flagged else color_text('OK', 'green')
        print_dual(f"Tensor symmetry (C vs C^T): max |C_ij - C_ji| = {max_diff:.3f} {unit_label} "
                   f"(i={i+1}, j={j+1})  [{status}]", f_out)
        if sym_flagged:
            print_dual(color_text(
                "[WARNING] C is not close to symmetric before averaging -- C_ij and C_ji came "
                "from two independently-measured directions that disagree; the reported matrix "
                "is 0.5*(C+C^T), which silently hides this. Possible causes: the two directions' "
                "reference structures aren't equally relaxed, or one has poor SCF/force "
                "convergence.", 'yellow'), f_out)

    if fit_diagnostics is not None:
        print_dual("Direction fit quality (stress vs. strain):", f_out)
        if not fit_diagnostics:
            print_dual("  (no direction had enough points to check)", f_out)
        else:
            for r in fit_diagnostics:
                status = color_text('WARNING', 'yellow') if r['flagged'] else color_text('OK', 'green')
                print_dual(f"  {r['mode']}: R^2 = {r['r_squared']:.6f} | residual stress = "
                           f"{r['residual_stress']:7.2f} {unit_label}  [{status}]", f_out)
            if any(r['flagged'] for r in fit_diagnostics):
                print_dual(color_text(
                    f"[WARNING] Direction(s) above have R^2 below --fit-quality-tolerance "
                    f"({args.fit_quality_tolerance}) and/or a non-negligible residual stress at "
                    "zero strain -- possible noisy data, too-large --max strain (anharmonic "
                    "regime), or an incompletely relaxed reference structure.", 'yellow'), f_out)

    if eggbox_results is not None:
        print_dual("Eggbox cross-check (stress vs. energy, same data):", f_out)
        if not eggbox_results:
            print_dual("  (no direction had both stress and energy data available to compare)", f_out)
        else:
            any_flagged = False
            for r in eggbox_results:
                status = color_text('WARNING', 'yellow') if r['flagged'] else color_text('OK', 'green')
                print_dual(f"  {r['mode']}: stress = {r['stress_value']:8.2f} {unit_label} | "
                           f"energy = {r['energy_value']:8.2f} {unit_label} | "
                           f"diff = {r['diff_pct']:5.2f}%  [{status}]", f_out)
                any_flagged = any_flagged or r['flagged']
            if any_flagged:
                print_dual(color_text(
                    f"[WARNING] Direction(s) above disagree by more than {args.eggbox_tolerance:.1f}% "
                    "between the stress-linear-fit and energy-parabolic-fit of the SAME calc.out "
                    "files -- possible eggbox (real-space grid) contamination in the stress data; "
                    "consider a finer MeshCutoff or checking SCF/force convergence.", 'yellow'), f_out)
            else:
                print_dual(color_text(
                    "[INFO] All checked direction(s) agree within tolerance -- no indication of "
                    "eggbox contamination in the stress data.", 'cyan'), f_out)

    # Stability and Properties Check
    summary = check_stability_and_report(C_sym, args.dimensionality, unit_label, f_out)

    # --- [5] SUMMARY & FILES: a compact recap of the numbers already
    # printed above (no recomputation -- reuses check_stability_and_report's
    # own return value) plus where everything ended up on disk, so the
    # report is self-contained even if someone only reads the last few
    # lines. ---
    warning_count = 0
    if symmetry_check is not None and symmetry_check[3]:
        warning_count += 1
    if fit_diagnostics:
        warning_count += sum(1 for r in fit_diagnostics if r['flagged'])
    if eggbox_results:
        warning_count += sum(1 for r in eggbox_results if r['flagged'])

    print_section('[5] SUMMARY & FILES', f_out)
    if args.dimensionality == "1d":
        print_dual(f"C33={summary['C33']:.4f} {unit_label}", f_out)
    elif args.dimensionality == "2d":
        print_dual(f"Ex={summary['Ex']:.2f} {unit_label}  Ey={summary['Ey']:.2f} {unit_label}  "
                   f"v_yx={summary['nu_yx']:.3f}  v_xy={summary['nu_xy']:.3f}  "
                   f"G_xy={summary['G_xy']:.2f} {unit_label}", f_out)
    else:
        au_str = f"{summary['A_U']:.3f}" if summary['A_U'] is not None else "N/A"
        print_dual(f"E={summary['E']:.2f} {unit_label}  B={summary['B']:.2f} {unit_label}  "
                   f"v={summary['nu']:.3f}  A^U={au_str}", f_out)
    verdict = color_text('STABLE', 'green') if summary['passes'] else color_text('UNSTABLE', 'red')
    print_dual(f"Verdict: {verdict}  |  Quality warnings raised in [3]: {warning_count}", f_out)
    if report_path:
        print_dual(f"Full report : {report_path}", f_out)
    if plot_files:
        print_dual(f"Plot data   : {args.plot_dir}/ ({len(plot_files)} file pair(s) -- raw fitting "
                   "data + gnuplot scripts, see [Saved] lines above)", f_out)


# ==========================================
#                  MAIN
# ==========================================

def main():
    parser = argparse.ArgumentParser(description="Siesta Elastic Properties Analyzer (STB Suite)")
    
    # --- CHANGED: Explicit flag for filename ---
    parser.add_argument("-f", "--file", type=str, default="calc.out",
                        help="Siesta log/output filename inside strain folders (default: calc.out)")

    parser.add_argument("--method", choices=["stress", "energy"], default="stress",
                        help="Which physical quantity to fit (default: stress). 'stress': the "
                             "existing stress-strain linear fit (sigma = C . epsilon), see "
                             "--symmetry-method. 'energy': an energy-strain (parabolic) fit "
                             "(E = E0 + (V0/2) gamma^T C gamma) over the pure+combined patterns "
                             "written by stb-elasticInputs --method energy -- a physically "
                             "independent cross-check (total energy vs. the stress tensor), "
                             "since a code's total energy and stress can have different sources "
                             "of numerical error. Always uses the general symmetry-allowed-"
                             "subspace fit (--symmetry-method doesn't apply); requires "
                             "--reference-structure.")
    parser.add_argument("--dimensionality", choices=["auto", "3d", "2d", "1d"], default="auto",
                        help="Physical dimensionality of the material, controlling report units "
                             "and which constants are shown (default: auto). 'auto': detected "
                             "from --reference-structure using the same vacuum-gap convention as "
                             "stb-elasticInputs/stb-kgrid/stb-strain (see --vacuum-gap) -- 0 "
                             "vacuum-padded axes -> 3d (GPa), 1 -> 2d (N/m), 2 -> 1d (nN); falls "
                             "back to 3d with a warning if --reference-structure isn't readable, "
                             "or if the vacuum sits on an axis other than this workflow's assumed "
                             "convention (in-plane xy for 2D, wire-along-c for 1D). '3d'/'2d'/"
                             "'1d': force the mode manually and skip detection entirely.")
    parser.add_argument("--vacuum-gap", type=float, default=10.0,
                        help="Vacuum gap threshold in Ang (default: 10.0) used only by "
                             "--dimensionality auto, same convention as stb-elasticInputs/"
                             "stb-kgrid/stb-strain.")
    parser.add_argument("--symmetry-method", choices=["basic", "full"], default="basic",
                        help="How to use detected symmetry (default: basic). 'basic': exact "
                             "reconstruction/pooling only when a single point-group operation "
                             "maps one canonical strain direction exactly onto another (misses "
                             "reductions like hexagonal's C11=C22, which come from the FULL "
                             "elastic tensor's invariance, not a pairwise direction match). "
                             "'full': fits the whole stiffness matrix at once, constrained a "
                             "priori to the point group's symmetry-allowed subspace -- catches "
                             "every crystal system's correct independent-constant count "
                             "uniformly (cubic, hexagonal, trigonal, ...), at the cost of being "
                             "a global least-squares fit rather than an exact per-column one. "
                             "Requires --reference-structure to be available.")
    parser.add_argument("--reference-structure", default="reference_structure.fdf",
                        help="UNDEFORMED structure file (default: reference_structure.fdf, written "
                             "automatically by stb-elasticInputs next to the strain_*/ folders), used "
                             "only to detect symmetry for the diagnostic/pooling/reconstruction across "
                             "equivalent directions. Must be the undeformed structure, not one from "
                             "inside a strain folder -- a single-axis strain genuinely lowers the "
                             "symmetry (e.g. cubic strained along x alone is exactly tetragonal, not "
                             "'cubic with noise'), so reading symmetry from a strained structure would "
                             "silently misdetect it. Never required -- falls back to independent "
                             "per-direction fitting if unavailable.")
    parser.add_argument("--symprec", type=float, default=1e-3,
                        help="Symmetry-detection tolerance (default: 1e-3, pymatgen's own default).")
    parser.add_argument("--angle-tolerance", type=float, default=5.0,
                        help="Symmetry angle tolerance in degrees (default: 5.0, pymatgen's own "
                             "default), same use as --symprec.")
    parser.add_argument("--eggbox-tolerance", type=float, default=5.0,
                        help="Relative difference (%%, default: 5.0) above which the mandatory "
                             "eggbox cross-check (--method stress only, see section [3] of the "
                             "report) flags a direction. Every diagonal constant actually run is "
                             "computed two independent ways from the SAME calc.out files -- a "
                             "stress-linear fit and an energy-parabolic fit -- with no new DFT "
                             "calculations; a disagreement beyond this tolerance is a hint of "
                             "eggbox (or other numerical) contamination in the stress data. "
                             "Needs --reference-structure; skipped with a warning (not an error) "
                             "if it isn't available.")
    parser.add_argument("--fit-quality-tolerance", type=float, default=0.995,
                        help="R^2 (default: 0.995) below which the mandatory per-direction "
                             "stress-vs-strain fit-quality check (--method stress only, section "
                             "[3] of the report) flags a direction -- a clean linear elastic fit "
                             "should sit well above this. Also flags a non-negligible residual "
                             "stress at zero strain (same relative-contribution criterion as the "
                             "energy method's linear-term check). No new DFT calculations: reuses "
                             "the same stress-strain fit each direction's column already needed.")
    parser.add_argument("--plot-dir", default="elastic_plots",
                        help="Directory (default: elastic_plots, created automatically) to write "
                             "the raw fitting data + gnuplot scripts into -- one .dat/.gplot pair "
                             "per direction (--method stress) or pattern (--method energy), plus a "
                             "combined overview. Same data+.gplot convention as the rest of the "
                             "suite (e.g. stb-strainAnalysis). Always written, no new DFT "
                             "calculations: reuses the data/fit already computed for the report.")
    parser.add_argument("--save-report", action="store_true",
                        help=f"Also persist the report to {REPORT_FILE}. Off by default.")
    parser.add_argument("-v", "--version", action="version",
                        version=f"stb-elasticAnalysis {VERSION}")
    parser.add_argument("--no-intro", dest="intro", action="store_false", help="Do not show the introduction")
    args = parser.parse_args()

    if args.intro:
        show_intro([
            "Siesta ToolBox Suite - Elastic Analyzer",
            "Elastic Constants & Stability Calculator",
            f"Version {VERSION} | University of Brasilia - 2025",
            "Integrated Style Refactoring"
        ])

    print("\n" + color_text("ELASTIC ANALYZER:", 'bold'))
    print("-" * 60)

    # --- Setup ---
    print(f"[INFO] Target Log File: {color_text(args.file, 'yellow')}")

    # Reference structure: loaded ONCE, up front -- feeds dimensionality
    # auto-detection below, the symmetry detection further down, and
    # --method energy's reference volume/area/length. Purely best-effort:
    # any failure (most commonly, the file just isn't there) is handled by
    # each downstream consumer on its own terms (dimensionality falls back
    # to 3D; symmetry/energy either skip or hard-fail, see below).
    ref_structure_raw = None
    pmg_structure = None
    if os.path.exists(args.reference_structure):
        try:
            ref_structure_raw = structure_io.read_fdf(args.reference_structure)
            pmg_structure = structure_io.to_pymatgen(ref_structure_raw)
        except Exception:
            ref_structure_raw = None
            pmg_structure = None

    # Dimensionality: manual override, or auto-detected from the reference
    # structure's vacuum padding (same convention as stb-elasticInputs/
    # stb-kgrid/stb-strain). This workflow assumes any vacuum sits on the
    # c-axis -- in-plane xy for 2D, wire-along-c for 1D -- since every
    # downstream formula here (the 2D report's C11/C22/C12/C66 block, the
    # Lz/cross-section unit normalization, the 1D report's C33) is written
    # against that specific orientation, not an arbitrary one.
    if args.dimensionality != "auto":
        dimensionality = args.dimensionality
        print(f"{color_text('[INFO]', 'green')} Dimensionality: "
              f"{color_text(dimensionality.upper(), 'cyan')} (manual override via --dimensionality)")
    elif ref_structure_raw is not None:
        positions = np.array([pos for _, pos in ref_structure_raw.atoms])
        is_cartesian = ref_structure_raw.coord_format == 'cartesian'
        frac_coords = kspace.to_fractional(positions, ref_structure_raw.lattice, is_cartesian)
        vacuum_axes = kspace.detect_vacuum_axes(frac_coords, ref_structure_raw.lattice, args.vacuum_gap)
        vacuum_count = sum(vacuum_axes)
        print(f"{color_text('[INFO]', 'green')} Detected dimensionality: "
              f"{kspace.dimensionality_label(vacuum_axes)}")
        if vacuum_count == 3:
            print(f"{color_text('[FAIL]', 'red')} Detected a 0D (isolated molecule) structure -- "
                  "stb-elasticAnalysis's stress/energy-strain workflow doesn't apply to isolated "
                  f"molecules. Check {args.reference_structure} (see --reference-structure).")
            sys.exit(1)
        elif vacuum_count == 0:
            dimensionality = "3d"
        elif vacuum_count == 1 and vacuum_axes == [False, False, True]:
            dimensionality = "2d"
        elif vacuum_count == 2 and vacuum_axes == [True, True, False]:
            dimensionality = "1d"
        else:
            print(color_text(
                "[WARNING] Vacuum padding detected on an axis this workflow doesn't support "
                "(expects in-plane xy for 2D, or wire-along-c for 1D) -- falling back to 3D "
                "(GPa). Pass --dimensionality explicitly to override.", 'yellow'))
            dimensionality = "3d"
    else:
        print(color_text(
            f"[WARNING] --dimensionality auto requires a readable {args.reference_structure} "
            "(see --reference-structure) -- none was found. Falling back to 3D (GPa); pass "
            "--dimensionality explicitly to skip detection.", 'yellow'))
        dimensionality = "3d"

    args.dimensionality = dimensionality
    unit_label = UNIT_LABELS[dimensionality]
    mode_desc = {"3d": ("3D Bulk", 'blue'), "2d": ("2D Material", 'cyan'), "1d": ("1D Wire/Tube", 'cyan')}
    desc, desc_color = mode_desc[dimensionality]
    print(f"[INFO] Mode: {color_text(desc, desc_color)} (Units: {unit_label})")

    # --- Data Mining ---
    print(f"[INFO] Scanning for 'strain_*' folders...")
    folders = sorted([f for f in os.listdir('.') if os.path.isdir(f) and f.startswith("strain_")])
    data = {}

    Lz = 1.0
    cross_section = 1.0
    found_norm = False

    if args.method == "stress":
        # Pre-scan for the geometric normalization SIESTA's stress needs --
        # it's a volumetric quantity, diluted by however much vacuum the
        # cell has: 2D undoes that with the cell height (Lz), 1D with the
        # vacuum cross-section (Lx*Ly, the wire's transverse extent). Not
        # needed for --method energy: total energy is already extensive
        # (see compute_stiffness_matrix_energy's docstring).
        for folder in folders:
            path = os.path.join(folder, args.file)
            if not os.path.exists(path):
                continue
            if dimensionality == "2d":
                val = siesta_log.get_cell_height(path)
                if val > 1.0:
                    Lz = val
                    found_norm = True
            elif dimensionality == "1d":
                outcell = siesta_log.get_outcell(path)
                if outcell is not None:
                    Lx, Ly = np.linalg.norm(outcell[0]), np.linalg.norm(outcell[1])
                    if Lx > 0.5 and Ly > 0.5:
                        cross_section = Lx * Ly
                        found_norm = True
            if found_norm:
                break

        if dimensionality == "2d" and found_norm:
            print(f"[INFO] Normalization by Cell Height (Lz): {Lz:.2f} Ang")
        elif dimensionality == "1d" and found_norm:
            print(f"[INFO] Normalization by Vacuum Cross-Section (Lx*Ly): {cross_section:.2f} Ang^2")

        if dimensionality == "2d":
            CONV_FACTOR = Lz * CONV_EVA2_TO_NM
        elif dimensionality == "1d":
            CONV_FACTOR = cross_section * CONV_EVA1_TO_NN
        else:
            CONV_FACTOR = CONV_EVA3_TO_GPA
    else:
        CONV_FACTOR = {"2d": CONV_EVA2_TO_NM, "1d": CONV_EVA1_TO_NN, "3d": CONV_EVA3_TO_GPA}[dimensionality]

    # Symmetry detection (optional): uses the reference structure already
    # loaded above to find which strain directions are symmetry-equivalent
    # -- enables compute_stiffness_matrix's pooling/reconstruction across
    # them. Purely advisory/best-effort.
    symmetry_info = None
    if pmg_structure is not None and args.method == "stress" and args.symmetry_method == "basic":
        try:
            groups, point_group, ops = symmetry.equivalent_strain_modes(
                pmg_structure, args.symprec, args.angle_tolerance)
            symmetry_info = (groups, point_group, ops)
            print(f"{color_text('[INFO]', 'cyan')} Detected point group {point_group} -- "
                  "symmetry-equivalent directions will be pooled/reconstructed.")
        except Exception:
            pmg_structure = None

    if args.method == "stress" and args.symmetry_method == "full" and pmg_structure is None:
        print(f"{color_text('[FAIL]', 'red')} --symmetry-method full requires a readable "
              f"{args.reference_structure} (see --reference-structure) to detect the point "
              "group -- none was found.")
        sys.exit(1)

    if args.method == "energy" and pmg_structure is None:
        print(f"{color_text('[FAIL]', 'red')} --method energy requires a readable "
              f"{args.reference_structure} (see --reference-structure) to detect the point "
              "group and reference volume/area -- none was found.")
        sys.exit(1)

    report_path = REPORT_FILE if args.save_report else None
    f_out = open(report_path, "w") if report_path else None

    print_dual(f"{color_text('===== ELASTIC PROPERTIES REPORT =====', 'magenta')}", f_out)

    print_section('[0] RUN METADATA', f_out)
    print_dual(f"Date/time            : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", f_out)
    print_dual(f"Method               : {args.method}"
               + (f" (--symmetry-method {args.symmetry_method})" if args.method == "stress" else ""),
               f_out)
    mode_labels = {"3d": "3D (GPa)", "2d": "2D (N/m)", "1d": "1D (nN)"}
    print_dual(f"Mode                 : {mode_labels[args.dimensionality]}", f_out)
    print_dual(f"Target log file      : {args.file}", f_out)
    print_dual(f"Reference structure  : {args.reference_structure}"
               + (" (found)" if pmg_structure is not None else " (not found -- best-effort features skipped)"),
               f_out)
    print_dual(f"strain_* folders found: {len(folders)}", f_out)
    if args.method == "stress":
        print_dual(f"Tolerances           : eggbox={args.eggbox_tolerance:.1f}%, "
                   f"fit-quality(R^2)={args.fit_quality_tolerance}, symprec={args.symprec}, "
                   f"angle-tolerance={args.angle_tolerance} deg", f_out)
    else:
        print_dual(f"Tolerances           : symprec={args.symprec}, "
                   f"angle-tolerance={args.angle_tolerance} deg", f_out)
    print_dual(f"Plot data directory  : {args.plot_dir}/", f_out)

    if args.method == "energy":
        # --- Energy-strain (parabolic fit) path: its own folder
        # scanning/parsing (pure+combined pattern names, total energy
        # instead of stress), entirely inside compute_stiffness_matrix_energy.
        print(f"\n{color_text('READING FOLDERS (energy-strain patterns):', 'bold')}")
        C, point_group, num_independent, directions_used, achieved_rank, energy_series, fit_coeffs = \
            compute_stiffness_matrix_energy(folders, args.file, pmg_structure, args.symprec,
                                             args.angle_tolerance, args.dimensionality, CONV_FACTOR,
                                             unit_label, f_out)
        filled_by_symmetry = []
        missing_directions = []

        if not directions_used:
            print(f"{color_text('[FAIL]', 'red')} No valid strain_<pattern>_* data found "
                  f"(--method energy). Check if '{args.file}' exists and has a 'siesta: "
                  "FreeEng' line, and that folder names match stb-elasticInputs --method "
                  "energy's convention.")
            if f_out:
                f_out.close()
            sys.exit(1)

        print_dual(f"{color_text('[INFO]', 'cyan')} Point group {point_group} has "
                   f"{num_independent} independent elastic constant(s); fit used "
                   f"{len(directions_used)} strain pattern(s): {directions_used}.", f_out)
        if achieved_rank < num_independent and args.dimensionality == "3d":
            print_dual(color_text(
                f"[WARNING] Pattern(s) run ({directions_used}) only determine "
                f"{achieved_rank} of {num_independent} independent elastic constants for "
                f"point group {point_group} -- the fit is underdetermined; run more "
                "patterns from stb-elasticInputs --method energy for a fully determined "
                "tensor.", 'yellow'), f_out)

        C_sym = 0.5 * (C + C.T)

        os.makedirs(args.plot_dir, exist_ok=True)
        plot_files = write_energy_plots(args.plot_dir, energy_series, fit_coeffs, unit_label, f_out)

        emit_elastic_report(args, C_sym, unit_label, filled_by_symmetry, missing_directions, f_out,
                             plot_files=plot_files)
        if f_out:
            f_out.close()
        print("-" * 60)
        if report_path:
            print(f"[DONE] Report saved to: {color_text(report_path, 'green')}")
        print(color_text("\nScience is organized knowledge. Wisdom is organized life.", 'bold'))
        return

    loaded_count = 0
    print(f"\n{color_text('READING FOLDERS:', 'bold')}")

    for folder in folders:
        direction, val = siesta_log.parse_strain_folder_name(folder)
        if direction is None: continue
        direction = _canonical_elastic_direction(direction)
        strain = val / 100.0

        # Read the specified file
        S = siesta_log.get_stress_tensor(os.path.join(folder, args.file))

        # --- MODIFICAÇÃO: Imprimir status da pasta ---
        msg = f"   -> {folder:<25} : "
        if S is not None:
            if direction not in data: data[direction] = {'eps': [], 'stress': []}
            data[direction]['eps'].append(strain)
            data[direction]['stress'].append(S)
            loaded_count += 1
            msg += color_text("OK", 'green')
        else:
            msg += color_text("FAIL", 'red') + " (No stress data found)"

        print(msg)
        # ---------------------------------------------

    print(f"\n[OK] Loaded {loaded_count} calculations from {len(folders)} folders.")

    if not data:
        print(f"{color_text('[FAIL]', 'red')} No valid data found in strain folders.")
        print(f"       Check if '{args.file}' exists and has 'Stress tensor'.")
        if f_out:
            f_out.close()
        sys.exit(1)


    # --- C_ij Calculation ---
    # Each single-component strain series already gives a FULL column of
    # C (sigma = C . epsilon, so a pure e_k strain gives sigma = C[:,k]),
    # so reading all 6 stress-Voigt components per series (not just the
    # 1-3 "obvious" ones) recovers the full 6x6 tensor -- including the
    # normal-shear coupling terms (C14-C16/C24-C26/C34-C36/C45/C46/C56)
    # -- from data already collected, no new strain series needed. When
    # symmetry_info is available, symmetry-equivalent directions are
    # additionally pooled (2+ measured) or reconstructed (only 1
    # measured, matching stb-elasticInputs' 'all' DFT-cost reduction).
    if args.symmetry_method == "full":
        C, point_group, num_independent, directions_used, filled_by_symmetry, achieved_rank = \
            compute_stiffness_matrix_full(data, CONV_FACTOR, pmg_structure, args.symprec,
                                           args.angle_tolerance, unit_label, f_out)
        missing_directions = []
        print_dual(f"{color_text('[INFO]', 'cyan')} Point group {point_group} has "
                   f"{num_independent} independent elastic constant(s); fit used "
                   f"{len(directions_used)} of 6 canonical direction(s): "
                   f"{', '.join(directions_used) if directions_used else '(none)'}.", f_out)
        # In 2D mode the report only ever shows the in-plane constants
        # (C11/C22/C12/C66); an underdetermined out-of-plane constant
        # (C33/C44/C13, typically inaccessible anyway on a vacuum-padded
        # axis) isn't something the user can or needs to act on, so only
        # warn about it in 3D mode, where every constant is reported.
        if achieved_rank < num_independent and args.dimensionality == "3d":
            print_dual(color_text(
                f"[WARNING] Direction(s) run ({', '.join(directions_used) if directions_used else '(none)'}) "
                f"only determine {achieved_rank} of {num_independent} independent elastic "
                f"constants for point group {point_group} -- the fit is underdetermined; run "
                "more of the 6 canonical directions for a fully determined tensor.", 'yellow'), f_out)
    else:
        C, filled_by_symmetry, missing_directions = compute_stiffness_matrix(
            data, CONV_FACTOR, symmetry_info, unit_label, f_out)

    # Directions that never exist for this dimensionality (e.g. 'xx' for
    # a 1D wire, which always touches a vacuum-padded axis) aren't a
    # real "missing data" or "reconstructed by symmetry" situation --
    # filter both advisory lists down to what's actually relevant so
    # emit_elastic_report doesn't tell a nanowire user to go run 'yy'.
    relevant = RELEVANT_DIRECTIONS[args.dimensionality]
    filled_by_symmetry = [d for d in filled_by_symmetry if d in relevant]
    missing_directions = [d for d in missing_directions if d in relevant]

    C_sym = 0.5 * (C + C.T)

    # Eggbox cross-check: mandatory for --method stress (not gated
    # behind a flag -- see core/symmetry.py's energy-method module note
    # and eggbox_cross_check's own docstring for the physics). Only
    # ever skipped, with a warning, if there's no reference structure
    # to get the volume/area from -- never blocks the rest of the
    # report, same "best-effort" spirit as --symmetry-method basic's
    # symmetry detection.
    eggbox_results = None
    if pmg_structure is not None:
        eggbox_results = eggbox_cross_check(data, folders, args.file, pmg_structure, args.dimensionality,
                                             CONV_FACTOR, args.eggbox_tolerance, f_out)
    else:
        print_dual(color_text(
            "[WARNING] Eggbox cross-check skipped: no readable "
            f"{args.reference_structure} (see --reference-structure) to get the reference "
            "volume/area from.", 'yellow'), f_out)

    # Per-direction fit quality (R^2 / residual stress at zero strain):
    # mandatory alongside the eggbox check, same "free diagnostic from
    # data already collected" spirit -- see direction_fit_diagnostics.
    fit_diagnostics = direction_fit_diagnostics(data, CONV_FACTOR, args.fit_quality_tolerance)

    # Tensor symmetry (C vs C^T): only meaningful for the basic method,
    # where C[i,j]/C[j,i] can come from two independently-run
    # directions -- see tensor_symmetry_check's docstring for why
    # --symmetry-method full and --method energy are always exactly
    # symmetric by construction and would give an uninformative ~0.
    symmetry_check = tensor_symmetry_check(C) if args.symmetry_method == "basic" else None

    os.makedirs(args.plot_dir, exist_ok=True)
    plot_files = write_stress_plots(args.plot_dir, data, fit_diagnostics, CONV_FACTOR,
                                     unit_label, f_out)

    emit_elastic_report(args, C_sym, unit_label, filled_by_symmetry, missing_directions, f_out,
                         eggbox_results=eggbox_results, fit_diagnostics=fit_diagnostics,
                         symmetry_check=symmetry_check, plot_files=plot_files)

    if f_out:
        f_out.close()

    print("-" * 60)
    if report_path:
        print(f"[DONE] Report saved to: {color_text(report_path, 'green')}")
    print(color_text("\nScience is organized knowledge. Wisdom is organized life.", 'bold'))

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n{color_text('[INFO] Operation cancelled by user.', 'red')}")
        sys.exit(0)
