#!/usr/bin/env python3

#################################################
#     Siesta Tool Box - Suite                   #
# Developed by Dr. Carlos M. O. Bastos          #
#      bastoscmo.github.io                      #
#################################################

"""Stage 1 of the Hirshfeld-I (iterative) charge-partitioning workflow.
Given a combined/production structure + its own SIESTA input template,
writes EVERYTHING needed to produce the two ingredients Stage 2/3 need:

  - combined/       the full system, unmodified, but forced to a
                     single-point SaveRho-true evaluation (never a
                     relaxation) -- same "config_extra.fdf on top of the
                     user's own untouched --calc template" pattern
                     stb-chargediffPrep already uses for its own combined/
                     folder (write_fragment_folder there, write_combined_
                     folder here). Also forces 'Charge.Hirshfeld end' +
                     'Charge.Voronoi end' (mandatory, not opt-in) -- SIESTA's
                     own native Hirshfeld/Voronoi charges (readable via
                     stb-nativecharges) from this exact same SCF density,
                     so all 3 methods (simple Hirshfeld, Voronoi, and the
                     Hirshfeld-I result stb-hirshfeldAnalysis converges to)
                     are always available to cross-check from one run.
  - neutral/<species>/  one isolated-atom-in-vacuum-box folder per
                     chemical species present -- the NEUTRAL reference
                     Stage 2 (stb-hirshfeldIons) needs to decide each
                     species' ion sign.

Nothing is assumed already computed: this stage does NOT require a
pre-existing '*.RHO' anywhere. The user runs SIESTA in combined/ and every
neutral/<species>/ folder this stage writes, THEN moves on to Stage 2.

Only 2 stages (Prep/Analysis) doesn't work for the workflow as a whole,
unlike stb-chargediffPrep/Analysis: which ion to compute per species can
only be decided AFTER the neutral-atom SIESTA jobs have actually run and
been read back (see hirshfeld_ions.py's own module docstring) -- the same
"can't write the next stage's folders until this stage's SIESTA output
exists" shape as stb-oer's Stage 1 -> stb-oerIntermediates hand-off.

Every neutral/<species>/ folder gets, via config_extra.fdf (never edited
into the user's own --calc template): a fixed cell, a single-point
evaluation, Gamma-only k-sampling (a single atom in a large vacuum box
needs no k-point sampling beyond Gamma), the SAME explicit MeshCutoff as
combined/, SaveRho true, and (unconditionally, matching cohesive_energy.py's
own isolated-atom convention) spin-polarized SCF -- an isolated atom is
very often an open shell even when its combined-system environment isn't.
combined/ itself gets a fixed cell + single-point + the same explicit
MeshCutoff + SaveRho true + Charge.Hirshfeld/Voronoi end, but NOT a forced
k-grid or Spin setting -- those stay whatever --calc already has (a
periodic slab/bulk combined
system needs its own real k-mesh, unlike an isolated atom in vacuum, and
its Spin/dipole/vdW settings are already baked into --calc/its own
config_extra.fdf if any -- nothing to inherit or re-derive here, unlike
stb-chargediffPrep's fragment folders, which need those flags applied
uniformly across MULTIPLE differently-shaped derived structures).

--calc is expected to already contain '%include structure.fdf' plus
basis/XC/pseudopotential directives via IMPLICIT per-species generation
(e.g. plain 'PAO.BasisSize DZP', not an explicit %block PAO.Basis entry
per species) -- reused verbatim for combined/ (all species present) and
every neutral/<species>/ folder (one species only); an explicit
per-species basis block naming species absent from a given folder's own
ChemicalSpeciesLabel may not be accepted by SIESTA and is the caller's own
responsibility to avoid.
"""

from stb import __version__ as VERSION

import os
import re
import sys
import json
import argparse
from datetime import datetime

import numpy as np

from stb.core import structure_io
from stb.core.cli import color_text, show_intro, print_dual, print_section, print_table
from stb.core.pseudopotentials import copy_pseudo, resolve_pseudo_source, BANKS

DEFAULT_MESH_CUTOFF_RY = 400.0
DEFAULT_VACUUM_ANG = 20.0

CONFIG_EXTRA_FILE = "config_extra.fdf"
HIRSHFELD_MANIFEST_FILE = "hirshfeld_manifest.json"
REPORT_FILE = "hirshfeld_prep_report.txt"

FIXED_CELL_BLOCK = (
    "# Auto-generated by stb-hirshfeldPrep -- keeps the cell fixed.\n"
    "MD.VariableCell false\n"
)
SINGLE_POINT_BLOCK = (
    "# Auto-generated by stb-hirshfeldPrep -- a single-point density evaluation,\n"
    "# not something SIESTA should be relaxing.\n"
    "MD.TypeOfRun          CG\n"
    "MD.Steps              0\n"
)
SPIN_POLARIZED_BLOCK = (
    "# Auto-generated by stb-hirshfeldPrep -- an isolated atom is very often an\n"
    "# open shell even when its combined-system environment isn't; unconditional,\n"
    "# same convention as cohesive_energy.py's own isolated-atom calc.\n"
    "Spin                polarized\n"
)
KGRID_GAMMA_BLOCK = (
    "# Auto-generated by stb-hirshfeldPrep -- a single atom in a large vacuum\n"
    "# box needs no k-point sampling beyond Gamma.\n"
    "kgrid.MonkhorstPack   [1  1  1]\n"
)
MESH_CUTOFF_BLOCK_TMPL = (
    "# Auto-generated by stb-hirshfeldPrep -- same MeshCutoff as every other\n"
    "# folder this workflow writes/reads, so every .RHO ends up on a comparably\n"
    "# resolved real-space grid.\n"
    "MeshCutoff          {value:g} Ry\n"
)
SAVE_RHO_BLOCK = (
    "# Auto-generated by stb-hirshfeldPrep -- SIESTA must write the .RHO file\n"
    "# for stb-hirshfeldIons/Analysis to read.\n"
    "SaveRho             true\n"
)
# combined/ only -- mandatory, not opt-in: this is the one calculation whose
# native Hirshfeld/Voronoi output (stb-nativecharges) is directly comparable
# to the Hirshfeld-I result stb-hirshfeldAnalysis converges to (same
# combined system, same SCF density), so the same run should always produce
# all 3 for a free cross-check -- no reason to ever skip this.
NATIVE_CHARGES_BLOCK = (
    "# Auto-generated by stb-hirshfeldPrep -- native SIESTA Hirshfeld/Voronoi\n"
    "# charges (read via stb-nativecharges) as a free cross-check against the\n"
    "# Hirshfeld-I result stb-hirshfeldAnalysis converges to, from this SAME run.\n"
    "Charge.Hirshfeld end\n"
    "Charge.Voronoi end\n"
)

_SPIN_RE = re.compile(r'^[ \t]*Spin\s+\S+.*$', re.IGNORECASE | re.MULTILINE)


def force_spin_polarized(calc_text):
    """Forces 'Spin polarized' directly into the literal calc.fdf text
    (regex substitution on whatever Spin line --calc already has, or
    appended if it has none) -- NOT relying solely on config_extra.fdf's
    %include-prepend/first-occurrence-wins trick (SPIN_POLARIZED_BLOCK
    still ALSO forces it there, redundantly, as a second layer). An
    isolated neutral atom or ion reference is mandatorily spin-polarized
    (very often an open shell even when the combined system's own
    environment isn't) -- this makes that unambiguous in the actual file
    SIESTA reads, not just in an included override.
    """
    new_text, count = _SPIN_RE.subn('Spin                polarized', calc_text)
    if count == 0:
        new_text = new_text.rstrip('\n') + '\nSpin                polarized\n'
    return new_text


def formula_string(structure):
    """'C2O1'-style formula string from an FdfStructure's own atom counts,
    species in declaration order -- same summary style as
    chargediff_prep.py's own combined-structure report section."""
    counts = structure_io.atom_counts(structure)
    return ''.join(f"{sym}{counts[sym]}" for sym in structure.species if counts.get(sym))


def write_combined_folder(out_dir, structure, calc_text, pseudo_dir, mesh_cutoff):
    """Writes combined/: the full system exactly as given (no ghosting, no
    geometry change), forced to a fixed-cell single-point SaveRho-true
    evaluation with native Hirshfeld/Voronoi charges also enabled (mandatory,
    see NATIVE_CHARGES_BLOCK) via config_extra.fdf -- everything else
    (Spin/dipole/vdW/k-grid/basis/XC) stays whatever calc_text already has.
    Copies a pseudopotential for every species actually present.
    """
    os.makedirs(out_dir, exist_ok=True)
    structure_io.write_fdf(structure, os.path.join(out_dir, "structure.fdf"))

    config_extra = (
        FIXED_CELL_BLOCK + SINGLE_POINT_BLOCK
        + MESH_CUTOFF_BLOCK_TMPL.format(value=mesh_cutoff) + SAVE_RHO_BLOCK
        + NATIVE_CHARGES_BLOCK
    )
    with open(os.path.join(out_dir, CONFIG_EXTRA_FILE), "w") as f:
        f.write(config_extra)

    with open(os.path.join(out_dir, "calc.fdf"), "w") as f:
        f.write(structure_io.prepend_include(calc_text, CONFIG_EXTRA_FILE))

    for sym in structure_io.species_list(structure):
        copy_pseudo(pseudo_dir, sym, out_dir)


def write_species_folder(out_dir, symbol, z_num, calc_text, pseudo_dir, mesh_cutoff, vacuum):
    """Writes one neutral/<species>/ folder: structure.fdf (isolated atom
    in a vacuum box, via structure_io.write_isolated_atom_fdf) +
    config_extra.fdf + calc.fdf (calc_text with 'Spin polarized' forced
    directly into it via force_spin_polarized, THEN config_extra.fdf
    %include-prepended on top -- two independent, redundant layers forcing
    the same mandatory setting) + a copied pseudopotential.
    """
    os.makedirs(out_dir, exist_ok=True)
    structure_io.write_isolated_atom_fdf(
        symbol, z_num, os.path.join(out_dir, "structure.fdf"), vacuum)

    config_extra = (
        FIXED_CELL_BLOCK + SINGLE_POINT_BLOCK + KGRID_GAMMA_BLOCK
        + MESH_CUTOFF_BLOCK_TMPL.format(value=mesh_cutoff) + SAVE_RHO_BLOCK
        + SPIN_POLARIZED_BLOCK
    )
    with open(os.path.join(out_dir, CONFIG_EXTRA_FILE), "w") as f:
        f.write(config_extra)

    with open(os.path.join(out_dir, "calc.fdf"), "w") as f:
        f.write(structure_io.prepend_include(force_spin_polarized(calc_text), CONFIG_EXTRA_FILE))

    copy_pseudo(pseudo_dir, symbol, out_dir)


def write_hirshfeld_manifest(out_dir, combined_dir, combined_structure,
                              mesh_cutoff, vacuum, species_entries):
    """`combined_dir`/`combined_structure` point at the freshly-written
    combined/ folder (absolute paths) -- NOT a pre-existing external
    calculation. combined/'s own '*.RHO' does not exist yet at Stage-1
    write time (SIESTA hasn't run there), so it is deliberately NOT
    recorded here; Stage 2/3 locate it themselves (core.rho_io.find_one_rho
    against combined_dir) once the user has actually run SIESTA.
    """
    manifest = {
        "schema": "hirshfeld_manifest_v2",
        "combined_dir": combined_dir,
        "combined_structure": combined_structure,
        "mesh_cutoff": mesh_cutoff,
        "vacuum_box": vacuum,
        "species": species_entries,
    }
    with open(os.path.join(out_dir, HIRSHFELD_MANIFEST_FILE), "w") as f:
        json.dump(manifest, f, indent=2)


def main():
    parser = argparse.ArgumentParser(
        description="Stage 1 of the Hirshfeld-I (iterative) charge-partitioning workflow: "
                     "writes a combined/ folder (the full system, forced to a single-point "
                     "SaveRho-true evaluation) plus one isolated-atom-in-vacuum-box folder per "
                     "chemical species -- everything needed before stb-hirshfeldIons (Stage 2) "
                     "can decide each species' ion sign. Nothing needs to be pre-computed.",
        formatter_class=argparse.RawTextHelpFormatter,
        epilog="Usage example:\n"
               "  %(prog)s --structure structure.fdf --calc calc.fdf -p dojo "
               "--output-dir hirshfeld_study\n"
    )
    parser.add_argument("-s", "--structure", default="structure.fdf",
                         help="Path to the combined/production system's own .fdf structure "
                              "file (structure_io.read_fdf). Default: 'structure.fdf'.")
    parser.add_argument("--calc", default="calc.fdf",
                         help="SIESTA input template (.fdf) -- same basis/XC/pseudopotential "
                              "directives used for combined/ and every isolated-atom folder "
                              "(default: 'calc.fdf'). Cell, single-point/MD, MeshCutoff and "
                              "SaveRho are all overridden by this tool's own config_extra.fdf "
                              "regardless of what's in this template; k-grid/Spin/dipole/vdW "
                              "are left untouched for combined/, and forced Gamma-only + "
                              "spin-polarized for every isolated-atom folder.")
    parser.add_argument("--mesh-cutoff", type=float, default=DEFAULT_MESH_CUTOFF_RY, metavar="RY",
                         help=f"Explicit MeshCutoff (Ry) to force in combined/ and every "
                              f"isolated-atom folder. Default: {DEFAULT_MESH_CUTOFF_RY:g} Ry.")
    parser.add_argument("--vacuum", type=float, default=DEFAULT_VACUUM_ANG, metavar="ANG",
                         help=f"Cubic vacuum-box side (Ang) for every isolated atom -- must be "
                              f"large enough that the atom's own density has decayed to ~0 "
                              f"well before the box edge. Default: {DEFAULT_VACUUM_ANG:g} Ang.")
    parser.add_argument("-p", "--pseudo-dir", type=str, default="",
                         help=f"Pseudopotentials source: a bundled bank ({', '.join(BANKS)}) or "
                              "a folder path. Default: reuse the directory --structure lives "
                              "in, which already has every pseudopotential the combined "
                              "calculation needed.")
    parser.add_argument("-O", "--output-dir", default="hirshfeld_study",
                         help="Root directory to write combined/ and neutral/<species>/ into "
                              "(default: hirshfeld_study).")
    parser.add_argument("--save-report", action="store_true",
                         help=f"Also persist the report to {REPORT_FILE}. Off by default.")
    parser.add_argument("--no-intro", dest="intro", action="store_false",
                         help="Do not show the introduction")
    parser.add_argument("-v", "--version", action="version", version=f"stb-hirshfeldPrep {VERSION}")

    args = parser.parse_args()

    if args.intro:
        show_intro([
            "Siesta ToolBox Suite - Hirshfeld-I Prep (Stage 1/3)",
            "Combined system + isolated NEUTRAL atom references, ready to run",
            f"Version {VERSION} | University of Brasilia - 2026",
            "Developed by Dr. Carlos M. O. Bastos"
        ])

    report_path = REPORT_FILE if args.save_report else None
    f_out = open(report_path, "w") if report_path else None

    print_dual(color_text("===== STB-HIRSHFELDPREP REPORT =====", 'magenta'), f_out)
    print_section("[0] RUN METADATA", f_out)
    print_dual(f"Date/time      : {datetime.now():%Y-%m-%d %H:%M:%S}", f_out)
    print_dual(f"Structure      : {args.structure}", f_out)
    print_dual(f"Calc template  : {args.calc}", f_out)
    print_dual(f"Mesh cutoff    : {args.mesh_cutoff:g} Ry", f_out)
    print_dual(f"Vacuum box     : {args.vacuum:g} Ang", f_out)
    print_dual(f"Output dir     : {args.output_dir}", f_out)

    if not os.path.isfile(args.structure):
        print_dual(color_text(f"[ERROR] Structure file '{args.structure}' not found.", 'red'), f_out)
        sys.exit(1)
    try:
        structure = structure_io.read_fdf(args.structure)
    except Exception as e:
        print_dual(color_text(f"[ERROR] Could not read '{args.structure}': {e}", 'red'), f_out)
        sys.exit(1)

    structure_dir = os.path.dirname(os.path.abspath(args.structure)) or "."

    if not os.path.isfile(args.calc):
        print_dual(color_text(f"[ERROR] Calc template '{args.calc}' not found.", 'red'), f_out)
        sys.exit(1)
    with open(args.calc) as f:
        calc_text = f.read()

    pseudo_dir = args.pseudo_dir or structure_dir
    try:
        pseudo_dir = resolve_pseudo_source(pseudo_dir)
    except ValueError as e:
        print_dual(color_text(f"[ERROR] {e}", 'red'), f_out)
        sys.exit(1)

    species_meta = structure_io.species_dict(structure)
    species = structure_io.species_list(structure)
    counts = structure_io.atom_counts(structure)

    print_section("[1] COMBINED STRUCTURE", f_out)
    cell_volume = abs(float(np.linalg.det(structure.lattice)))
    print_dual(f"Formula        : {formula_string(structure)}", f_out)
    print_dual(f"Total atoms    : {len(structure.atoms)}", f_out)
    print_dual(f"Species        : {', '.join(species)}", f_out)
    print_dual(f"Cell volume    : {cell_volume:.4f} Ang^3", f_out)
    print_dual("Lattice vectors (Ang):", f_out)
    for vec in structure.lattice:
        print_dual(f"  {vec[0]:14.8f} {vec[1]:14.8f} {vec[2]:14.8f}", f_out)

    print_section("[2] SPECIES", f_out)
    rows = [([sym, str(species_meta[sym]['Z']), str(counts.get(sym, 0)),
              os.path.join("neutral", sym)], None) for sym in species]
    print_table(["Species", "Z", "Atoms in combined/", "Neutral folder"], rows, f_out)

    print_dual(f"\nPseudopotential source: {pseudo_dir}", f_out)

    os.makedirs(args.output_dir, exist_ok=True)

    print_section("[3] WRITING COMBINED + NEUTRAL-ATOM FOLDERS", f_out)
    combined_out_dir = os.path.join(args.output_dir, "combined")
    write_combined_folder(combined_out_dir, structure, calc_text, pseudo_dir, args.mesh_cutoff)
    print_dual(f"  {color_text('[OK]', 'green')} {combined_out_dir}/ "
               f"(full system, {len(structure.atoms)} atom(s), single-point + SaveRho)", f_out)
    print_dual(f"       Forced: MD.VariableCell false, MD.TypeOfRun CG / MD.Steps 0, "
               f"MeshCutoff {args.mesh_cutoff:g} Ry, SaveRho true, "
               f"Charge.Hirshfeld end, Charge.Voronoi end", f_out)
    print_dual(f"       Untouched (from --calc): k-grid, Spin, dipole correction, vdW", f_out)
    print_dual(f"       structure.fdf, config_extra.fdf, calc.fdf written; "
               f"pseudopotentials copied for: {', '.join(species)}", f_out)

    species_entries = []
    for sym in species:
        z_num = species_meta[sym]['Z']
        neutral_folder = os.path.join("neutral", sym)
        out_dir = os.path.join(args.output_dir, neutral_folder)
        write_species_folder(out_dir, sym, z_num, calc_text, pseudo_dir,
                              args.mesh_cutoff, args.vacuum)
        species_entries.append({"symbol": sym, "z_num": z_num, "neutral_folder": neutral_folder})
        print_dual(f"  {color_text('[OK]', 'green')} {out_dir}/ "
                   f"(isolated {sym}, vacuum box {args.vacuum:g} Ang)", f_out)
        print_dual(f"       Forced: MD.VariableCell false, MD.TypeOfRun CG / MD.Steps 0, "
                   f"Gamma-only k-grid, MeshCutoff {args.mesh_cutoff:g} Ry, SaveRho true, "
                   f"Spin polarized (mandatory -- both via config_extra.fdf AND forced "
                   f"directly into calc.fdf)", f_out)
        print_dual(f"       structure.fdf, config_extra.fdf, calc.fdf written; "
                   f"pseudopotential copied for: {sym}", f_out)

    write_hirshfeld_manifest(
        args.output_dir, os.path.abspath(combined_out_dir),
        os.path.abspath(os.path.join(combined_out_dir, "structure.fdf")),
        args.mesh_cutoff, args.vacuum, species_entries)

    print_section("[4] SUMMARY", f_out)
    print_dual(f"Folders written : {1 + len(species_entries)} "
               f"(combined + {len(species_entries)} neutral-atom folder(s))", f_out)
    print_dual(f"Mesh cutoff     : {args.mesh_cutoff:g} Ry (every folder)", f_out)
    print_dual(f"Vacuum box      : {args.vacuum:g} Ang (every neutral-atom folder)", f_out)
    print_dual(f"Manifest        : {os.path.join(args.output_dir, HIRSHFELD_MANIFEST_FILE)}", f_out)
    print_dual(color_text(
        "Next: run SIESTA in 'combined/' AND every 'neutral/<species>/' folder, then run "
        "stb-hirshfeldIons to decide each species' ion sign and write the ion folders.",
        'cyan'), f_out)
    if report_path:
        print_dual(f"Report          : {report_path}", f_out)

    if f_out:
        f_out.close()

    print("\n" + "-" * 60)
    print(color_text("Hirshfeld-I Prep (Stage 1) complete.\n", 'bold'))


if __name__ == "__main__":
    main()
