#!/usr/bin/env python3

#################################################
#     Siesta Tool Box - Suite                   #
# Developed by Dr. Carlos M. O. Bastos          #
#      bastoscmo.github.io                      #
#################################################

"""Stage 2 of the Hirshfeld-I (iterative) charge-partitioning workflow.
Structurally plays the same role oer_intermediates.py plays for stb-oer
(reads a previous stage's already-finished SIESTA output, then writes
brand-new folders that could not have been written any earlier) -- here,
the neutral-atom '*.RHO' every neutral/<species>/ folder stb-hirshfeldPrep
(Stage 1) wrote.

Follows the original iterative-Hirshfeld formulation (Bultinck et al.,
J. Chem. Phys. 126, 144111 (2007)) literally: at each round, EVERY ATOM
independently interpolates its own reference density between its species'
neutral profile and whichever of that species' CATION or ANION profile
matches THAT ATOM's own charge sign -- so two atoms of the same species
CAN legitimately end up leaning toward opposite ion states (e.g. an edge
carbon reading slightly positive while the bulk of the carbons read
negative). This is why this stage writes BOTH an ions/<species>/cation/
and an ions/<species>/anion/ folder for EVERY species, unconditionally --
3N total isolated-atom SIESTA sub-calcs (N neutral, from Stage 1, + N
cation + N anion, from this stage), not the 2N a "pick one sign per
species from a single vote" shortcut would need. That coarser shortcut
(this tool's own earlier implementation) cannot represent a genuinely
mixed-sign species and silently mis-references every atom on the "wrong"
side of the vote.

This stage still reads back combined/'s own '*.RHO' and runs one plain
pass-0 simple-Hirshfeld pass (reference = neutral profiles only --
directly comparable to stb-nativecharges'/SIESTA's own native Hirshfeld
output for the same combined system) -- purely as an informational
preview of what Stage 3's iteration will see (which atoms/how many lean
positive vs negative per species), since deciding WHICH folders to write
no longer depends on it.
"""

VERSION = "2.0.0"  # writes BOTH cation and anion per species unconditionally
                    # (previously picked one sign per species from a pass-0 vote)

import os
import re
import sys
import glob
import json
import argparse
from datetime import datetime
from collections import defaultdict

import numpy as np

from stb.core import structure_io, kspace, hirshfeld as hf, siesta_log
from stb.core.deps import require_sisl
from stb.core.cli import color_text, show_intro, print_dual, print_section, print_table
from stb.core.pseudopotentials import copy_pseudo, resolve_pseudo_source
from stb.core.rho_io import find_one_rho, read_total

sisl = require_sisl()

CONFIG_EXTRA_FILE = "config_extra.fdf"
HIRSHFELD_MANIFEST_FILE = "hirshfeld_manifest.json"
HIRSHFELD_IONS_MANIFEST_FILE = "hirshfeld_ions_manifest.json"
REPORT_FILE = "hirshfeld_ions_report.txt"
N_RADIAL_BINS = 200

FIXED_CELL_BLOCK = (
    "# Auto-generated by stb-hirshfeldIons -- keeps the (vacuum) cell fixed.\n"
    "MD.VariableCell false\n"
)
SINGLE_POINT_BLOCK = (
    "# Auto-generated by stb-hirshfeldIons -- an isolated-ion reference is a\n"
    "# single-point evaluation, not something SIESTA should be relaxing.\n"
    "MD.TypeOfRun          CG\n"
    "MD.Steps              0\n"
)
SPIN_POLARIZED_BLOCK = (
    "# Auto-generated by stb-hirshfeldIons -- same unconditional spin-polarized\n"
    "# convention as stb-hirshfeldPrep's own neutral-atom folders.\n"
    "Spin                polarized\n"
)
KGRID_GAMMA_BLOCK = (
    "# Auto-generated by stb-hirshfeldIons -- a single ion in a large vacuum\n"
    "# box needs no k-point sampling beyond Gamma.\n"
    "kgrid.MonkhorstPack   [1  1  1]\n"
)
MESH_CUTOFF_BLOCK_TMPL = (
    "# Auto-generated by stb-hirshfeldIons -- same MeshCutoff as this workflow's\n"
    "# other folders.\n"
    "MeshCutoff          {value:g} Ry\n"
)
SAVE_RHO_BLOCK = (
    "# Auto-generated by stb-hirshfeldIons -- SIESTA must write the .RHO file\n"
    "# for stb-hirshfeldAnalysis to read.\n"
    "SaveRho             true\n"
)
# NetCharge (|e|, positive = electron deficit = cation) is the standard
# SIESTA fdf directive for a non-neutral system's total charge -- not used
# ANYWHERE ELSE in this codebase before this workflow, so this exact
# syntax/sign convention has not been cross-checked against a real SIESTA
# run in this environment. Verify against the SIESTA manual (or a real
# run) before trusting a production Hirshfeld-I result; a wrong sign
# convention here would silently swap every species' cation/anion.
NET_CHARGE_BLOCK_TMPL = (
    "# Auto-generated by stb-hirshfeldIons -- one of the two ion references\n"
    "# ({sign_word}) always computed for this species (see module docstring for\n"
    "# why Stage 3 needs both, not just whichever sign a pass-0 vote favors).\n"
    "NetCharge            {value:+.1f}\n"
)

_SPIN_RE = re.compile(r'^[ \t]*Spin\s+\S+.*$', re.IGNORECASE | re.MULTILINE)


def force_spin_polarized(calc_text):
    """Duplicated from hirshfeld_prep.py::force_spin_polarized (same
    self-contained-per-stage duplication convention as her_refs.py/
    oer_intermediates.py's own shared helpers) -- forces 'Spin polarized'
    directly into the literal calc.fdf text, on top of (redundant with)
    SPIN_POLARIZED_BLOCK's own config_extra.fdf override. An isolated ion
    reference is mandatorily spin-polarized, same as Stage 1's neutral
    atoms.
    """
    new_text, count = _SPIN_RE.subn('Spin                polarized', calc_text)
    if count == 0:
        new_text = new_text.rstrip('\n') + '\nSpin                polarized\n'
    return new_text


def _glob_rho(folder):
    """Non-raising existence check: True if `folder` has at least one
    '*.RHO' file -- used for the Stage-1-recap status column, where
    find_one_rho's raise-on-zero-or-many contract is the wrong fit (a
    status label is wanted here, not an exception)."""
    return bool(glob.glob(os.path.join(folder, "*.RHO")))


def load_neutral_profile(neutral_folder, n_bins=N_RADIAL_BINS):
    """Reads neutral/<species>/*.RHO and its own structure.fdf (for the
    isolated atom's exact box/center -- not assumed from the manifest's
    recorded vacuum_box, in case the folder was edited by hand), returns
    (r_array, rho_of_r_array) via core.hirshfeld.radial_density_profile.
    """
    rho_path = find_one_rho(neutral_folder)
    sile = sisl.get_sile(rho_path)
    grid = read_total(sile)
    structure = structure_io.read_fdf(os.path.join(neutral_folder, "structure.fdf"))
    center_frac = structure.atoms[0][1]
    if structure.coord_format == "cartesian":
        center_frac = kspace.to_fractional(center_frac, structure.lattice, True)
    return hf.radial_density_profile(grid.grid, structure.lattice, center_frac, n_bins=n_bins)


def write_ion_folder(out_dir, symbol, z_num, net_charge, calc_text, pseudo_dir,
                      mesh_cutoff, vacuum):
    os.makedirs(out_dir, exist_ok=True)
    structure_io.write_isolated_atom_fdf(
        symbol, z_num, os.path.join(out_dir, "structure.fdf"), vacuum)

    sign_word = "CATION" if net_charge > 0 else "ANION"
    config_extra = (
        FIXED_CELL_BLOCK + SINGLE_POINT_BLOCK + KGRID_GAMMA_BLOCK
        + MESH_CUTOFF_BLOCK_TMPL.format(value=mesh_cutoff) + SAVE_RHO_BLOCK
        + SPIN_POLARIZED_BLOCK
        + NET_CHARGE_BLOCK_TMPL.format(sign_word=sign_word, value=net_charge)
    )
    with open(os.path.join(out_dir, CONFIG_EXTRA_FILE), "w") as f:
        f.write(config_extra)

    with open(os.path.join(out_dir, "calc.fdf"), "w") as f:
        f.write(structure_io.prepend_include(force_spin_polarized(calc_text), CONFIG_EXTRA_FILE))

    copy_pseudo(pseudo_dir, symbol, out_dir)


def main():
    parser = argparse.ArgumentParser(
        description="Stage 2 of the Hirshfeld-I workflow: reads back every neutral atom "
                     "folder stb-hirshfeldPrep wrote (now run through SIESTA) and writes BOTH "
                     "a cation and an anion reference folder for EVERY species -- Stage 3 "
                     "needs both, since individual atoms of the same species can converge "
                     "toward opposite ion states (see module docstring).",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument("-O", "--output-dir", default="hirshfeld_study",
                         help="Same root directory stb-hirshfeldPrep wrote into (default: "
                              "hirshfeld_study) -- reads hirshfeld_manifest.json from here.")
    parser.add_argument("-p", "--pseudo-dir", type=str, default="",
                         help="Pseudopotentials source for the ion folders. Default: reuse "
                              "the combined system's own directory (recorded in the manifest).")
    parser.add_argument("--ref", required=False, default=None,
                         help="Path to a specific SIESTA output file to read each species' "
                              "Z_val (valence charge) and native Hirshfeld/Voronoi cross-check "
                              "from -- same convention as stb-bader's own --ref. Overrides "
                              "auto-detection of combined/'s own '*.out' (which assumes that "
                              "log was left with a .out extension; use --ref if yours wasn't).")
    parser.add_argument("--save-report", action="store_true",
                         help=f"Also persist the report to {REPORT_FILE}. Off by default.")
    parser.add_argument("--no-intro", dest="intro", action="store_false",
                         help="Do not show the introduction")
    parser.add_argument("-v", "--version", action="version", version=f"stb-hirshfeldIons {VERSION}")

    args = parser.parse_args()

    if args.intro:
        show_intro([
            "Siesta ToolBox Suite - Hirshfeld-I Ions (Stage 2/3)",
            "Write BOTH cation and anion references, per species",
            f"Version {VERSION} | University of Brasilia - 2026",
            "Developed by Dr. Carlos M. O. Bastos"
        ])

    report_path = REPORT_FILE if args.save_report else None
    f_out = open(report_path, "w") if report_path else None

    print_dual(color_text("===== STB-HIRSHFELDIONS REPORT =====", 'magenta'), f_out)
    print_section("[0] RUN METADATA", f_out)
    print_dual(f"Date/time      : {datetime.now():%Y-%m-%d %H:%M:%S}", f_out)
    print_dual(f"Study dir      : {args.output_dir}", f_out)

    manifest_path = os.path.join(args.output_dir, HIRSHFELD_MANIFEST_FILE)
    if not os.path.isfile(manifest_path):
        print_dual(color_text(
            f"[ERROR] '{manifest_path}' not found -- run stb-hirshfeldPrep first.", 'red'), f_out)
        sys.exit(1)
    with open(manifest_path) as f:
        manifest = json.load(f)

    try:
        structure = structure_io.read_fdf(manifest["combined_structure"])
    except Exception as e:
        print_dual(color_text(
            f"[ERROR] Could not read the combined structure "
            f"'{manifest['combined_structure']}': {e}", 'red'), f_out)
        sys.exit(1)

    symbols = [sym for sym, _ in structure.atoms]
    positions = np.array([pos for _, pos in structure.atoms])
    frac_positions = kspace.to_fractional(positions, structure.lattice,
                                           structure.coord_format == "cartesian")
    counts = structure_io.atom_counts(structure)

    # Z_val (VALENCE charge -- what a pseudopotential DFT density actually
    # integrates to) is NOT the same as Z (the atomic number used to pick
    # the pseudopotential in %block ChemicalSpeciesLabel): using the latter
    # in charge = Z_val - population silently produces nonsense (e.g. Te
    # would read a "charge" of +46 e instead of a plausible +0.2 e). Same
    # detected-from-.out-with-tabulated-fallback resolution as stb-bader's
    # own valence_source; --ref (same flag/behavior as stb-bader's own)
    # takes priority over auto-detecting combined/'s own '*.out' -- a
    # caller whose SIESTA log wasn't left with a .out extension needs this
    # to get a real detected Z_val instead of silently falling all the way
    # back to the hardcoded table.
    combined_out = args.ref or siesta_log.find_out_file(manifest["combined_dir"], None)
    detected_valence = siesta_log.get_zval_from_output(None, override_path=combined_out) \
        if combined_out else None
    valence_source = {**siesta_log.FALLBACK_VALENCE, **(detected_valence or {})}
    unknown_syms = sorted({sym for sym in symbols if sym not in valence_source})
    if unknown_syms:
        print_dual(color_text(
            f"[ERROR] No valence Z_val (detected or fallback) for species: "
            f"{', '.join(unknown_syms)}.", 'red'), f_out)
        sys.exit(1)
    z_vals = [valence_source[sym] for sym in symbols]

    # --- [1] STAGE 1 RECAP -- everything stb-hirshfeldPrep wrote, so this
    # report is self-contained even without Stage 1's own (possibly long
    # gone) console output/report file at hand. ---
    print_section("[1] STAGE 1 RECAP", f_out)
    cell_volume = abs(float(np.linalg.det(structure.lattice)))
    formula = ''.join(f"{sym}{counts[sym]}" for sym in structure.species if counts.get(sym))
    print_dual(f"Combined structure : {manifest['combined_structure']}", f_out)
    print_dual(f"Formula            : {formula}", f_out)
    print_dual(f"Total atoms        : {len(structure.atoms)}", f_out)
    print_dual(f"Cell volume        : {cell_volume:.4f} Ang^3", f_out)
    print_dual(f"Mesh cutoff        : {manifest['mesh_cutoff']:g} Ry", f_out)
    print_dual(f"Vacuum box         : {manifest['vacuum_box']:g} Ang", f_out)

    combined_out_present = bool(_glob_rho(manifest["combined_dir"]))
    print_dual(f"combined/ .RHO     : "
               f"{color_text('found', 'green') if combined_out_present else color_text('MISSING', 'red')} "
               f"({manifest['combined_dir']})", f_out)

    print_dual("\nSpecies written by Stage 1:", f_out)
    species_rows = []
    for entry in manifest["species"]:
        sym = entry["symbol"]
        neutral_folder = os.path.join(args.output_dir, entry["neutral_folder"])
        rho_status = "found" if _glob_rho(neutral_folder) else "MISSING"
        z_val_source = "detected (SIESTA log)" if sym in (detected_valence or {}) else "hardcoded fallback"
        species_rows.append(([sym, str(entry["z_num"]), f"{valence_source[sym]:g}", z_val_source,
                              str(counts.get(sym, 0)), entry["neutral_folder"], rho_status],
                             None if rho_status == "found" else 'yellow'))
    print_table(["Species", "Z", "Z_val", "Z_val source", "Atoms in combined/",
                "Neutral folder", "Neutral .RHO"], species_rows, f_out)

    # --- [2] NATIVE CHARGES CROSS-CHECK -- if combined/ has already been
    # run with SIESTA's native Charge.Hirshfeld/Voronoi end (forced
    # unconditionally by stb-hirshfeldPrep), surface those numbers right
    # here so the eventual Hirshfeld-I result has an immediate, same-run
    # cross-check to compare against (same values stb-nativecharges would
    # report for this folder). Purely informational -- absent is fine,
    # this run may be the first time SIESTA is executed in combined/. ---
    print_section("[2] NATIVE CHARGES CROSS-CHECK (combined/)", f_out)
    hirshfeld_native = voronoi_native = None
    if not combined_out:
        print_dual("No .out log found yet in combined/ -- run SIESTA there first for a "
                   "native Hirshfeld/Voronoi cross-check.", f_out)
    else:
        hirshfeld_native = siesta_log.get_hirshfeld_charges(combined_out)
        voronoi_native = siesta_log.get_voronoi_charges(combined_out)
        if not hirshfeld_native and not voronoi_native:
            print_dual(f"'{combined_out}' has no native Hirshfeld/Voronoi Populations block yet "
                       "(SCF may still be running, or the run predates this workflow forcing "
                       "Charge.Hirshfeld/Voronoi end).", f_out)
        else:
            headers = ["Idx", "Elem", "Hirshfeld(e-)", "Voronoi(e-)"]
            rows = []
            for i, sym in enumerate(symbols):
                h = next((r['charge'] for r in (hirshfeld_native or []) if r['id'] == i + 1), None)
                v = next((r['charge'] for r in (voronoi_native or []) if r['id'] == i + 1), None)
                rows.append(([str(i + 1), sym,
                              f"{h:+.4f}" if h is not None else "N/A",
                              f"{v:+.4f}" if v is not None else "N/A"], None))
            print_table(headers, rows, f_out)

    try:
        combined_rho_path = find_one_rho(manifest["combined_dir"])
    except ValueError as e:
        print_dual(color_text(
            f"[ERROR] {e} -- has SIESTA been run in 'combined/' yet?", 'red'), f_out)
        sys.exit(1)
    try:
        combined_sile = sisl.get_sile(combined_rho_path)
        rho_real = read_total(combined_sile).grid
    except Exception as e:
        print_dual(color_text(
            f"[ERROR] Could not read the combined '.RHO' '{combined_rho_path}': {e}", 'red'), f_out)
        sys.exit(1)

    print_section("[3] NEUTRAL PROFILES", f_out)
    neutral_profiles = {}
    for entry in manifest["species"]:
        sym = entry["symbol"]
        neutral_folder = os.path.join(args.output_dir, entry["neutral_folder"])
        try:
            neutral_profiles[sym] = load_neutral_profile(neutral_folder)
            print_dual(f"  {sym}: read from '{neutral_folder}'", f_out)
        except Exception as e:
            print_dual(color_text(
                f"[ERROR] Could not build a neutral profile for species '{sym}' from "
                f"'{neutral_folder}': {e} -- has SIESTA been run there yet?", 'red'), f_out)
            sys.exit(1)

    species_profiles = {i: neutral_profiles[symbols[i]] for i in range(len(symbols))}
    charges, populations = hf.compute_hirshfeld_charges(
        rho_real, structure.lattice, frac_positions, z_vals, species_profiles,
        progress_label="Pass-0 Hirshfeld charges")

    print_section("[4] PASS-0 (SIMPLE HIRSHFELD) CHARGES -- PREVIEW ONLY", f_out)
    print_dual("Purely informational: shows what Stage 3's iteration will start from and "
               "which atoms/species already lean positive vs negative. Does NOT decide which "
               "ion folders get written below -- both cation and anion are always written for "
               "every species (see module docstring).", f_out)
    headers = ["Idx", "Elem", "Z_val", "Population(e-)", "Charge(e-)"]
    if hirshfeld_native:
        headers.append("Native Hirshfeld(e-)")
    rows = []
    for i in range(len(symbols)):
        cells = [str(i + 1), symbols[i], str(z_vals[i]), f"{populations[i]:.4f}",
                 f"{charges[i]:+.4f}"]
        if hirshfeld_native:
            h = next((r['charge'] for r in hirshfeld_native if r['id'] == i + 1), None)
            cells.append(f"{h:+.4f}" if h is not None else "N/A")
        rows.append((cells, None))
    print_table(headers, rows, f_out)

    by_species_idx = defaultdict(list)
    for i, sym in enumerate(symbols):
        by_species_idx[sym].append(i)

    print_dual("\nPer-species summary (N+ / N- = how many atoms of this species already lean "
               "cation-like / anion-like at pass-0 -- both > 0 means Stage 3 will genuinely "
               "use both ion states for this species):", f_out)
    species_summary_rows = []
    for sym in sorted(by_species_idx):
        values = [charges[i] for i in by_species_idx[sym]]
        n_pos = sum(1 for c in values if c >= 0)
        n_neg = sum(1 for c in values if c < 0)
        mean = float(np.mean(values))
        std = float(np.std(values))
        species_summary_rows.append(([sym, str(len(values)), str(n_pos), str(n_neg),
                                      f"{mean:+.4f}", f"{std:.4f}"],
                                     'cyan' if n_pos > 0 and n_neg > 0 else None))
    print_table(["Elem", "N", "N+", "N-", "Mean(e-)", "Std(e-)"], species_summary_rows, f_out)

    # --- [5] WRITING ION REFERENCES -- both cation AND anion, per species,
    # unconditionally (see module docstring for why). ---
    print_section("[5] WRITING ION REFERENCES (cation + anion, every species)", f_out)
    os.makedirs(args.output_dir, exist_ok=True)
    pseudo_dir = args.pseudo_dir or manifest["combined_dir"]
    try:
        pseudo_dir = resolve_pseudo_source(pseudo_dir)
    except ValueError as e:
        print_dual(color_text(f"[ERROR] {e}", 'red'), f_out)
        sys.exit(1)

    calc_source = None
    for entry in manifest["species"]:
        neutral_folder = os.path.join(args.output_dir, entry["neutral_folder"])
        calc_path = os.path.join(neutral_folder, "calc.fdf")
        if os.path.isfile(calc_path):
            with open(calc_path) as f:
                calc_source = f.read()
            break
    if calc_source is None:
        print_dual(color_text(
            "[ERROR] Could not find any neutral/<species>/calc.fdf to reuse as the ion "
            "folders' own template.", 'red'), f_out)
        sys.exit(1)

    species_entries = []
    for entry in manifest["species"]:
        sym = entry["symbol"]
        cation_folder = os.path.join("ions", sym, "cation")
        anion_folder = os.path.join("ions", sym, "anion")
        write_ion_folder(os.path.join(args.output_dir, cation_folder), sym, entry["z_num"],
                          +1.0, calc_source, pseudo_dir, manifest["mesh_cutoff"],
                          manifest["vacuum_box"])
        write_ion_folder(os.path.join(args.output_dir, anion_folder), sym, entry["z_num"],
                          -1.0, calc_source, pseudo_dir, manifest["mesh_cutoff"],
                          manifest["vacuum_box"])
        species_entries.append({
            "symbol": sym, "cation_folder": cation_folder, "anion_folder": anion_folder,
            "pass0_charges": [float(charges[i]) for i in by_species_idx[sym]],
        })
        print_dual(f"  {color_text('[OK]', 'green')} {sym}: "
                   f"{cation_folder}/ (NetCharge +1.0), {anion_folder}/ (NetCharge -1.0)", f_out)

    ions_manifest = {
        "schema": "hirshfeld_ions_manifest_v2",
        "hirshfeld_manifest": os.path.abspath(manifest_path),
        "species": species_entries,
    }
    with open(os.path.join(args.output_dir, HIRSHFELD_IONS_MANIFEST_FILE), "w") as f:
        json.dump(ions_manifest, f, indent=2)

    print_section("[6] SUMMARY", f_out)
    print_dual(f"Atoms analyzed (pass-0)    : {len(symbols)}", f_out)
    print_dual(f"Species                    : {len(species_entries)}", f_out)
    print_dual(f"Ion folders written        : {2 * len(species_entries)} "
               f"({len(species_entries)} cation + {len(species_entries)} anion)", f_out)
    print_dual(f"Manifest                   : "
               f"{os.path.join(args.output_dir, HIRSHFELD_IONS_MANIFEST_FILE)}", f_out)
    print_dual(color_text(
        "Next: run SIESTA in every ions/<species>/cation/ AND ions/<species>/anion/ folder, "
        "then run stb-hirshfeldAnalysis for the converged Hirshfeld-I charges.", 'cyan'), f_out)
    if report_path:
        print_dual(f"Report                     : {report_path}", f_out)

    if f_out:
        f_out.close()

    print("\n" + "-" * 60)
    print(color_text("Hirshfeld-I Ions (Stage 2) complete.\n", 'bold'))


if __name__ == "__main__":
    main()
