#!/usr/bin/env python

#################################################
#     Siesta Tool Box - Suite                   #
# Developed by Dr. Carlos M. O. Bastos          #
#      bastoscmo.github.io                      #
#################################################

VERSION = "1.10.0"

import os
import re
import sys
import glob
import shutil
import subprocess
import argparse
from time import sleep
from datetime import datetime
try:
    import phonopy
except ImportError:
    print("\n[ERROR] Phonopy is not installed. Please install it using: pip install phonopy")
    sys.exit(1)

# Cores ANSI para terminal
from stb.core.cli import COLORS, color_text, show_intro

_LABEL_RE = re.compile(r'^\s*SystemLabel\s+(\S+)', re.IGNORECASE | re.MULTILINE)

REPORT_FILE = "phonon_properties.txt"
# Same palette as elastic_analysis.py's PLOT_COLORS (first 3 entries), kept
# here as its own short list since phonons only ever plots these 3 series.
PLOT_COLORS = ['#2255cc', '#cc5522', '#22aa55']


def detect_system_label(phonon_dir):
    """Auto-detect SystemLabel from the calc.fdf/structure.fdf copied into the
    first disp-* folder, same regex-based approach as
    hubbardu.get_system_label/wantibexos.get_system_label. Returns None (not
    "siesta") when nothing is found, so callers can tell "not detected" apart
    from a genuine label of "siesta".
    """
    disp_dirs = sorted(glob.glob(os.path.join(phonon_dir, "disp-*")))
    if not disp_dirs:
        return None
    for fdf_path in glob.glob(os.path.join(disp_dirs[0], "*.fdf")):
        try:
            with open(fdf_path) as f:
                match = _LABEL_RE.search(f.read())
        except OSError:
            continue
        if match:
            return match.group(1)
    return None


def print_dual(text, file_handle=None):
    """Prints to stdout with color, writes to file without color."""
    print(text)
    if file_handle:
        clean_text = re.sub(r'\x1b\[[0-9;]*m', '', text)
        file_handle.write(clean_text + "\n")


def write_thermal_plots(plot_dir, temperatures, free_energy, entropy, heat_capacity, f_out):
    """One <property>.dat + <property>.gplot per thermal-property curve
    (raw data, no fit -- there's nothing to fit here) plus a combined
    multiplot overview .dat/.gplot pair. Same per-series + combined
    convention as elastic_analysis.py's write_energy_plots/write_stress_plots,
    reusing the temperatures/free_energy/entropy/heat_capacity arrays
    run_thermal_properties already computed -- no recomputation.
    """
    os.makedirs(plot_dir, exist_ok=True)
    properties = [
        ("free_energy", "Free energy (kJ/mol)", free_energy, PLOT_COLORS[0]),
        ("entropy", "Entropy (J/K/mol)", entropy, PLOT_COLORS[1]),
        ("heat_capacity", "Heat capacity (J/K/mol)", heat_capacity, PLOT_COLORS[2]),
    ]
    written = []
    for name, ylabel, values, color in properties:
        dat_path = os.path.join(plot_dir, f"{name}.dat")
        with open(dat_path, "w") as f:
            f.write(f"# stb-phononsPos -- {ylabel} vs temperature\n")
            f.write(f"# columns: 1=T(K) 2={ylabel}\n")
            for t, v in zip(temperatures, values):
                f.write(f"{t:10.2f} {v:18.6f}\n")

        gplot_path = os.path.join(plot_dir, f"{name}.gplot")
        with open(gplot_path, "w") as f:
            f.writelines([
                '# --- STB Plot Configuration ---\n',
                '# Generated by stb-phononsPos\n',
                'set terminal pdfcairo enhanced color font "Arial,14" size 7,5\n',
                f'set output "{name}.pdf"\n\n',
                f'set title "{ylabel} vs Temperature"\n',
                'set xlabel "Temperature (K)"\n',
                f'set ylabel "{ylabel}"\n',
                'set grid\n',
                (f'plot "{name}.dat" using 1:2 with lines lw 2 '
                 f'lc rgb "{color}" title "{ylabel}"\n'),
            ])

        print_dual(f"{color_text('[Saved]', 'cyan')} {dat_path}, {gplot_path} "
                    f"(cd {plot_dir} && gnuplot {os.path.basename(gplot_path)})", f_out)
        written.append((name, dat_path, gplot_path))

    combined_dat = os.path.join(plot_dir, "thermal_properties_overview.dat")
    with open(combined_dat, "w") as f:
        f.write("# T(K)       FreeEnergy(kJ/mol)  Entropy(J/K/mol)  HeatCapacity(J/K/mol)\n")
        for i in range(len(temperatures)):
            f.write(f"{temperatures[i]:10.2f} {free_energy[i]:18.6f} "
                     f"{entropy[i]:18.6f} {heat_capacity[i]:18.6f}\n")

    combined_gplot = os.path.join(plot_dir, "thermal_properties_overview.gplot")
    with open(combined_gplot, "w") as f:
        f.writelines([
            '# --- STB Plot Configuration ---\n',
            '# Generated by stb-phononsPos\n',
            'set terminal pdfcairo enhanced color font "Arial,14" size 8,10\n',
            'set output "thermal_properties_overview.pdf"\n\n',
            'set multiplot layout 3,1 title "Thermal Properties"\n',
            'set xlabel "Temperature (K)"\n',
            'set grid\n\n',
            'set ylabel "Free energy (kJ/mol)"\n',
            f'plot "thermal_properties_overview.dat" using 1:2 with lines lw 2 '
            f'lc rgb "{PLOT_COLORS[0]}" title "Free energy"\n\n',
            'set ylabel "Entropy (J/K/mol)"\n',
            f'plot "thermal_properties_overview.dat" using 1:3 with lines lw 2 '
            f'lc rgb "{PLOT_COLORS[1]}" title "Entropy"\n\n',
            'set ylabel "Heat capacity (J/K/mol)"\n',
            f'plot "thermal_properties_overview.dat" using 1:4 with lines lw 2 '
            f'lc rgb "{PLOT_COLORS[2]}" title "Heat capacity"\n\n',
            'unset multiplot\n',
        ])

    print_dual(f"{color_text('[Saved]', 'cyan')} {combined_dat}, {combined_gplot} "
                f"(cd {plot_dir} && gnuplot {os.path.basename(combined_gplot)})", f_out)
    written.append(("overview", combined_dat, combined_gplot))
    return written


def main():
    parser = argparse.ArgumentParser(
        description="Post-processing for SIESTA phonon calculations using Phonopy.",
        epilog="Example usage:\n"
               "  phonons_post -dir phonon_runs -l siesta -m 20 20 20\n"
               "  phonons_post --tmin 0 --tmax 800 --tstep 5",
        formatter_class=argparse.RawTextHelpFormatter
    )

    parser.add_argument("-dir", "--directory", type=str, default="phonon_runs",
                        help="Directory containing the displacement folders (default: phonon_runs)")
    parser.add_argument("-l", "--label", type=str, default=None,
                        help="SystemLabel used in calc.fdf (default: auto-detected from "
                             "the copied calc.fdf/structure.fdf, falling back to 'siesta')")
    parser.add_argument("-m", "--mesh", type=int, nargs=3, default=[20, 20, 20],
                        help="Q-point mesh for thermal properties (default: 20 20 20)")
    parser.add_argument("--tmin", type=float, default=0.0, help="Minimum temperature in K (default: 0)")
    parser.add_argument("--tmax", type=float, default=1000.0, help="Maximum temperature in K (default: 1000)")
    parser.add_argument("--tstep", type=float, default=10.0, help="Temperature step in K (default: 10)")
    parser.add_argument("--plot-dir", type=str, default="phonon_plots",
                        help="Directory (inside the phonon directory) for gnuplot .dat/.gplot "
                             "output (default: phonon_plots)")
    parser.add_argument("-v", "--version", action="version", version=f"stb-phononsPos {VERSION}")
    parser.add_argument("--no-intro", dest="intro", action="store_false", help="Do not show the introduction")

    args = parser.parse_args()

    if args.intro:
        show_intro([
            "Siesta ToolBox Suite",
            "A comprehensive toolkit for SIESTA DFT simulations",
            f"Version {VERSION} | University of Brasilia - 2026",
            "Developed by Dr. Carlos M. O. Bastos"
        ])

    print("\n" + color_text("PHONON POST-PROCESSING:", 'bold'))
    print("-" * 60)

    phonon_dir = args.directory

    # 1. Validação do Diretório
    print(f"\n[INFO] Validating phonon directory '{phonon_dir}' ...")
    if not os.path.exists(phonon_dir):
        print(color_text(f"[ERROR] Directory '{phonon_dir}' not found.", 'red'))
        sys.exit(1)

    yaml_file = os.path.join(phonon_dir, "phonopy_disp.yaml")
    if not os.path.exists(yaml_file):
        print(color_text(f"[ERROR] '{yaml_file}' not found. Did you run the displacement generator?", 'red'))
        sys.exit(1)

    if args.label is not None:
        system_label = args.label
        label_source = "manual (-l/--label)"
    else:
        system_label = detect_system_label(phonon_dir) or "siesta"
        label_source = "auto-detected from calc.fdf"
        print(f"[INFO] Auto-detected SystemLabel '{system_label}' from calc.fdf "
              "(pass -l/--label to override).")

    # Everything below is wrapped in the report file -- opened as a plain
    # `with` so it's flushed/closed correctly even on an early sys.exit(1)
    # (e.g. missing .FA files, failed FORCE_SETS), leaving a partial report
    # that shows how far processing got.
    report_path = os.path.join(phonon_dir, REPORT_FILE)
    with open(report_path, "w") as f_out:
        print_dual(f"{color_text('===== PHONON PROPERTIES REPORT =====', 'magenta')}", f_out)

        print_dual(f"\n{color_text('[0] RUN METADATA', 'magenta')}", f_out)
        print_dual("-" * 60, f_out)
        print_dual(f"Date/time         : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", f_out)
        print_dual(f"Phonon directory  : {phonon_dir}", f_out)
        print_dual(f"SystemLabel       : {system_label} ({label_source})", f_out)
        print_dual(f"Q-point mesh      : {args.mesh[0]} x {args.mesh[1]} x {args.mesh[2]}", f_out)
        print_dual(f"Temperature range : {args.tmin} K to {args.tmax} K (step {args.tstep} K)", f_out)

        # 2. Extração de Forças (Criando FORCE_SETS)
        print_dual(f"\n{color_text('[1] FORCE EXTRACTION', 'magenta')}", f_out)
        print_dual("-" * 60, f_out)
        fa_files_abs = sorted(glob.glob(os.path.join(phonon_dir, "disp-*", f"{system_label}.FA")))

        if not fa_files_abs:
            print_dual(color_text(f"[ERROR] No {system_label}.FA files found in {phonon_dir}/disp-*", 'red'), f_out)
            print_dual(color_text("Make sure SIESTA calculations finished successfully.", 'yellow'), f_out)
            sys.exit(1)

        # Pegamos os caminhos relativos ao phonon_dir para rodar o comando lá dentro
        fa_files_rel = [os.path.relpath(f, phonon_dir) for f in fa_files_abs]
        print_dual(f"Force files found : {len(fa_files_rel)} (label '{system_label}')", f_out)

        # phonopy >=4 moved the FORCE_SETS-creation flags ("-f"/"--siesta")
        # out of the main `phonopy` CLI into a separate `phonopy-init`
        # command; older installs (<4) only have `phonopy`. Prefer the new
        # command when present, fall back otherwise.
        force_sets_bin = "phonopy-init" if shutil.which("phonopy-init") else "phonopy"
        cmd = [force_sets_bin, "--siesta", "-f"] + fa_files_rel

        try:
            # Roda o comando de extração de forças DENTRO da pasta phonon_runs
            subprocess.check_call(cmd, cwd=phonon_dir, stdout=subprocess.DEVNULL)
            print_dual(color_text("FORCE_SETS       : generated successfully", 'green'), f_out)
        except subprocess.CalledProcessError as e:
            print_dual(color_text(f"[ERROR] Failed to generate FORCE_SETS. Phonopy error: {e}", 'red'), f_out)
            sys.exit(1)

        # 3. Propriedades Térmicas usando a API Python do Phonopy
        print(f"\n[INFO] Initializing Phonopy API and loading FORCE_SETS ...")
        original_dir = os.getcwd()
        try:
            # Como o yaml e o FORCE_SETS estão na mesma pasta, precisamos avisar o phonopy ou mudar o dir de execução
            os.chdir(phonon_dir)
            phonon = phonopy.load("phonopy_disp.yaml")
        except Exception as e:
            print_dual(color_text(f"[ERROR] Could not load phonopy data: {e}", 'red'), f_out)
            os.chdir(original_dir)
            sys.exit(1)

        print(f"[INFO] Running thermal properties calculation ...")
        print(f"       -> Q-Mesh: {args.mesh}")
        print(f"       -> Temperature Range: {args.tmin} K to {args.tmax} K (step: {args.tstep} K)")

        phonon.run_mesh(args.mesh)
        min_freq = phonon.mesh.frequencies.min()

        print_dual(f"\n{color_text('[2] DYNAMICAL STABILITY', 'magenta')}", f_out)
        print_dual("-" * 60, f_out)
        print_dual(f"Minimum mesh frequency : {min_freq:.4f} THz", f_out)
        if min_freq < 0:
            print_dual(color_text(
                "[WARNING] Negative (imaginary) phonon frequencies found -- the "
                "structure/supercell is dynamically unstable at some q-point (soft mode, "
                "unrelaxed geometry, or a numerical-quality issue). Phonopy silently drops "
                "these modes from the thermal-property sums below (cutoff_frequency=0), so "
                "the resulting free energy/entropy/heat capacity are not physically "
                "meaningful as-is.", 'red'), f_out)
        else:
            print_dual(color_text("No imaginary modes found on the sampled mesh.", 'green'), f_out)

        phonon.run_thermal_properties(t_min=args.tmin, t_max=args.tmax, t_step=args.tstep)

        # 4. Salvando Gráficos e Dados
        print("[INFO] Exporting results ...")

        tp_plot = phonon.plot_thermal_properties()
        plot_filename = "thermal_properties.png"
        tp_plot.savefig(plot_filename, dpi=300)
        print(color_text(f" -> Saved plot as '{os.path.join(phonon_dir, plot_filename)}'", 'cyan'))

        tp = phonon.thermal_properties
        temperatures = tp.temperatures
        free_energy = tp.free_energy
        entropy = tp.entropy
        heat_capacity = tp.heat_capacity

        dat_filename = "thermal_properties.dat"
        with open(dat_filename, "w") as f:
            f.write("# T(K)       FreeEnergy(kJ/mol)  Entropy(J/K/mol)  HeatCapacity(J/K/mol)\n")
            for i in range(len(temperatures)):
                f.write(f"{temperatures[i]:10.2f} {free_energy[i]:18.6f} {entropy[i]:18.6f} {heat_capacity[i]:18.6f}\n")

        print(color_text(f" -> Saved raw data as '{os.path.join(phonon_dir, dat_filename)}'", 'cyan'))

        print_dual(f"\n{color_text('[3] THERMAL PROPERTIES SUMMARY', 'magenta')}", f_out)
        print_dual("-" * 60, f_out)
        print_dual(f"Zero-point energy (F @ {temperatures[0]:.1f} K) : {free_energy[0]:.6f} kJ/mol", f_out)
        print_dual(f"At T = {temperatures[-1]:.1f} K:", f_out)
        print_dual(f"  Free energy    : {free_energy[-1]:.6f} kJ/mol", f_out)
        print_dual(f"  Entropy        : {entropy[-1]:.6f} J/K/mol", f_out)
        print_dual(f"  Heat capacity  : {heat_capacity[-1]:.6f} J/K/mol", f_out)

        plots_written = write_thermal_plots(args.plot_dir, temperatures, free_energy,
                                             entropy, heat_capacity, f_out)

        # Retorna ao diretório original
        os.chdir(original_dir)

        print_dual(f"\n{color_text('[4] SUMMARY & FILES', 'magenta')}", f_out)
        print_dual("-" * 60, f_out)
        stability_verdict = ("UNSTABLE (imaginary modes present)" if min_freq < 0
                              else "stable on the sampled mesh")
        print_dual(f"Dynamical stability : {stability_verdict}", f_out)
        print_dual(f"Report              : {report_path}", f_out)
        print_dual(f"Files               : {os.path.join(phonon_dir, plot_filename)}, "
                    f"{os.path.join(phonon_dir, dat_filename)}, "
                    f"{os.path.join(phonon_dir, args.plot_dir)}/ "
                    f"({len(plots_written)} .dat/.gplot pairs)", f_out)

    print("\n" + "-" * 60)
    print(color_text("Post-processing complete! Results are in your phonon directory.\n", 'bold'))

if __name__ == "__main__":
    main()
