#!/usr/bin/env python

#################################################
#     Siesta Tool Box - Suite                   #
# Developed by Dr. Carlos M. O. Bastos          #
#      bastoscmo.github.io                      #
#################################################

VERSION = "1.0.0"

import os
import re
import sys
import argparse
import numpy as np
from datetime import datetime
from pymatgen.io.ase import AseAtomsAdaptor
from phonopy.api_qha import PhonopyQHA
from stb.core import structure_io, mace_relax, mace_phonons
from stb.core.cli import COLORS, color_text, show_intro
from stb.core.deps import require_mace

REPORT_FILE = "phonon_qha_properties.txt"
PLOT_COLORS = ['#2255cc', '#cc5522', '#22aa55']


def print_dual(text, file_handle=None):
    """Prints to stdout with color, writes to file without color. Same
    helper as phonons_pos.py -- duplicated per tool, not factored into
    core/ (presentational, not computational logic; same precedent as
    print_dual/print_symmetry_table elsewhere in this workflow)."""
    print(text)
    if file_handle:
        clean_text = re.sub(r'\x1b\[[0-9;]*m', '', text)
        file_handle.write(clean_text + "\n")


def write_xy_plot(plot_dir, name, title, xlabel, ylabel, x, y, color, f_out):
    """Generic single-curve .dat+.gplot writer -- shared by the several
    "one quantity vs temperature" QHA outputs below (thermal expansion,
    V(T), B(T), G(T), Cp(T)), which all have the same 2-column shape.
    Same STB gnuplot-folder convention as the rest of this workflow
    (phonons_pos.py's write_dos_plot/write_thermal_displacement_plot).
    """
    os.makedirs(plot_dir, exist_ok=True)
    dat_path = os.path.join(plot_dir, f"{name}.dat")
    with open(dat_path, "w") as f:
        f.write(f"# stb-phononsQHA -- {title}\n")
        f.write(f"# columns: 1={xlabel} 2={ylabel}\n")
        for xv, yv in zip(x, y):
            f.write(f"{xv:14.6f} {yv:18.8e}\n")

    gplot_path = os.path.join(plot_dir, f"{name}.gplot")
    with open(gplot_path, "w") as f:
        f.writelines([
            '# --- STB Plot Configuration ---\n',
            '# Generated by stb-phononsQHA\n',
            'set terminal pdfcairo enhanced color font "Arial,14" size 7,5\n',
            f'set output "{name}.pdf"\n\n',
            f'set title "{title}"\n',
            f'set xlabel "{xlabel}"\n',
            f'set ylabel "{ylabel}"\n',
            'set grid\n',
            (f'plot "{name}.dat" using 1:2 with lines lw 2 '
             f'lc rgb "{color}" title "{title}"\n'),
        ])

    print_dual(f"{color_text('[Saved]', 'cyan')} {dat_path}, {gplot_path} "
                f"(cd {plot_dir} && gnuplot {os.path.basename(gplot_path)})", f_out)
    return (name, dat_path, gplot_path)


def main():
    parser = argparse.ArgumentParser(
        description="Quasi-harmonic approximation (thermal expansion, bulk modulus vs. "
                     "T, Gibbs free energy vs. T) using the MACE-MP-0 foundation potential "
                     "only -- no SIESTA. Runs the full stb-phononsML pipeline at several "
                     "isotropically-scaled volumes and fits an equation of state. Same "
                     "heuristic-preview caveat as stb-phononsML/stb-mlrelax: not a DFT "
                     "replacement.",
        epilog="Example usage:\n"
               "  stb-phononsQHA -s structure.fdf -dim 2 2 2\n"
               "  stb-phononsQHA -s structure.fdf --strain-min -5 --strain-max 5 --n-points 7\n"
               "\n"
               "Look at a specific volume's bands/DOS/etc. afterwards exactly like any other "
               "phonon_runs directory:\n"
               "  stb-phononsPos -dir phonon_qha_runs/vol_02 --bands --dos\n"
               "\n"
               "Note: only the volume is scanned (cell shape/angles fixed, scaled "
               "isotropically) -- the standard QHA approximation for a small range around "
               "equilibrium (a few percent), not a per-volume cell-shape relaxation. Less "
               "appropriate for strongly anisotropic materials over a wide volume range.\n",
        formatter_class=argparse.RawTextHelpFormatter
    )

    parser.add_argument("-s", "--structure", type=str, default="structure.fdf",
                        help="Input structure file containing the unit cell (default: structure.fdf)")
    parser.add_argument("-dim", type=int, nargs=3, default=[2, 2, 2],
                        help="Supercell dimensions, same for every volume (default: 2 2 2)")
    parser.add_argument("-d", "--distance", type=float, default=0.01,
                        help="Displacement distance in Angstroms (default: 0.01)")
    parser.add_argument("--strain-min", type=float, default=-3.0,
                        help="Minimum volume deviation from equilibrium, in %% (default: -3.0)")
    parser.add_argument("--strain-max", type=float, default=3.0,
                        help="Maximum volume deviation from equilibrium, in %% (default: 3.0)")
    parser.add_argument("--n-points", type=int, default=5,
                        help="Number of volumes to sample between --strain-min and "
                             "--strain-max, evenly spaced (default: 5)")
    parser.add_argument("-m", "--mesh", type=int, nargs=3, default=[20, 20, 20],
                        help="Q-point mesh for thermal properties, used at every volume "
                             "(default: 20 20 20)")
    parser.add_argument("--tmin", type=float, default=0.0, help="Minimum temperature in K (default: 0)")
    parser.add_argument("--tmax", type=float, default=1000.0, help="Maximum temperature in K (default: 1000)")
    parser.add_argument("--tstep", type=float, default=10.0, help="Temperature step in K (default: 10)")
    parser.add_argument("--eos", choices=["vinet", "murnaghan", "birch_murnaghan"], default="vinet",
                        help="Equation of state fitted to energy vs. volume (default: vinet)")
    parser.add_argument("--model", choices=["small", "medium", "large"], default="small",
                        help="MACE-MP-0 model size: speed/accuracy tradeoff (default: small).")
    parser.add_argument("--device", choices=["cpu", "cuda"], default="cpu",
                        help="Device to run the model on (default: cpu).")
    parser.add_argument("--no-relax", dest="relax", action="store_false",
                        help="Skip the per-volume MACE pre-relax (positions only, cell fixed "
                             "at that volume). On by default, same reasoning as stb-phononsML.")
    parser.add_argument("--fmax", type=float, default=0.05,
                        help="Force convergence threshold for the per-volume pre-relax, "
                             "eV/Ang (default: 0.05).")
    parser.add_argument("--plot-dir", type=str, default="phonon_plots",
                        help="Directory (inside the output directory) for gnuplot .dat/.gplot "
                             "output (default: phonon_plots)")
    parser.add_argument("-o", "--output-dir", type=str, default="phonon_qha_runs",
                        help="Output directory: one vol_NN/ subfolder per volume (each a "
                             "full stb-phononsML-style phonopy_disp.yaml, individually "
                             "explorable with stb-phononsPos) plus the QHA report/plots "
                             "(default: phonon_qha_runs).")
    parser.add_argument("-v", "--version", action="version", version=f"stb-phononsQHA {VERSION}")
    parser.add_argument("--no-intro", dest="intro", action="store_false",
                        help="Do not show the introduction")

    args = parser.parse_args()

    require_mace()

    if args.intro:
        show_intro([
            "Siesta ToolBox Suite",
            "A comprehensive toolkit for SIESTA DFT simulations",
            f"Version {VERSION} | University of Brasilia - 2026",
            "Developed by Dr. Carlos M. O. Bastos"
        ])

    print("\n" + color_text("QUASI-HARMONIC APPROXIMATION (VIA MACE-MP-0 -- NO SIESTA NEEDED):", 'bold'))
    print(color_text("Heuristic preview, not a DFT replacement -- same caveat as stb-mlrelax/stb-phononsML.", 'yellow'))
    print("-" * 60)

    # 1. Validação e leitura da estrutura
    print("\n[INFO] Validating input files ...")
    if not os.path.exists(args.structure):
        print(color_text(f"[ERROR] Structure file '{args.structure}' not found in the current directory.", 'red'))
        sys.exit(1)

    print(f"[INFO] Reading unit cell from '{args.structure}' ...")
    try:
        structure = structure_io.read_fdf(args.structure)
    except Exception as e:
        print(color_text(f"[ERROR] Failed to read {args.structure}. Make sure it's properly formatted.\nDetails: {e}", 'red'))
        sys.exit(1)

    pmg = structure_io.to_pymatgen(structure)
    atoms0 = AseAtomsAdaptor.get_atoms(pmg)
    v0_input = atoms0.get_volume()
    print(f"[INFO] Elements found in unit cell: {', '.join(sorted(set(atoms0.get_chemical_symbols())))}")
    print(f"[INFO] Input cell volume: {v0_input:.4f} Ang^3")

    if args.n_points < 4:
        print(color_text("[ERROR] --n-points must be at least 4 -- vinet/murnaghan/"
                          "birch_murnaghan all fit 4 parameters (E0, V0, B0, B0'), so need "
                          "at least 4 volumes.", 'red'))
        sys.exit(1)

    output_root = args.output_dir
    if os.path.isdir(output_root) and os.listdir(output_root):
        print(color_text(f"\n[CRITICAL ERROR] '{output_root}' already exists and is not empty.", 'red'))
        print(color_text(
            f"Remove or move aside '{output_root}' and rerun, to avoid silently mixing "
            "data from a different run.", 'yellow'))
        sys.exit(1)
    os.makedirs(output_root, exist_ok=True)

    print(f"\n[INFO] Loading MACE-MP-0 ({args.model}) on {args.device} ...")
    calc = mace_relax.get_calculator(model=args.model, device=args.device)

    strains_pct = np.linspace(args.strain_min, args.strain_max, args.n_points)
    # PhonopyQHA's t_max must sit a few grid points short of the actual end
    # of the temperature array (it needs neighbors for finite-difference
    # derivatives) -- pad the per-volume thermal-properties grid past the
    # user's requested --tmax so args.tmax itself is always safely interior.
    t_max_grid = args.tmax + 3 * args.tstep

    report_path = os.path.join(output_root, REPORT_FILE)
    with open(report_path, "w") as f_out:
        print_dual(f"{color_text('===== QHA REPORT (MACE-MP-0) =====', 'magenta')}", f_out)

        print_dual(f"\n{color_text('[0] RUN METADATA', 'magenta')}", f_out)
        print_dual("-" * 60, f_out)
        print_dual(f"Date/time         : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", f_out)
        print_dual(f"Structure         : {args.structure}", f_out)
        print_dual(f"Supercell dim     : {args.dim[0]} x {args.dim[1]} x {args.dim[2]}", f_out)
        print_dual(f"Volume range      : {args.strain_min}% to {args.strain_max}% "
                    f"({args.n_points} points, V0={v0_input:.4f} Ang^3)", f_out)
        print_dual(f"Q-point mesh      : {args.mesh[0]} x {args.mesh[1]} x {args.mesh[2]}", f_out)
        print_dual(f"Temperature range : {args.tmin} K to {args.tmax} K (step {args.tstep} K)", f_out)
        print_dual(f"Equation of state : {args.eos}", f_out)
        print_dual(f"MACE-MP-0 model   : {args.model} ({args.device})", f_out)

        print_dual(f"\n{color_text('[1] VOLUME SCAN', 'magenta')}", f_out)
        print_dual("-" * 60, f_out)
        print_dual(f"{'Strain%':>8} {'Volume(Ang^3)':>14} {'Energy(eV)':>14} "
                    f"{'N_disp':>7} {'MinFreq(THz)':>13}", f_out)

        volumes = []
        energies = []
        free_energy_list = []
        entropy_list = []
        cv_list = []
        temperatures_ref = None
        any_unstable = False

        for i, strain_pct in enumerate(strains_pct):
            factor = (1.0 + strain_pct / 100.0) ** (1.0 / 3.0)
            atoms_i = atoms0.copy()
            atoms_i.set_cell(np.array(atoms0.get_cell()) * factor, scale_atoms=True)

            def _progress(n_done, n_total, _i=i):
                report_every = max(1, n_total // 5)
                if n_done % report_every == 0 or n_done == n_total:
                    print(f"  ... volume {_i + 1}/{len(strains_pct)}: {n_done}/{n_total} forces")

            phonon, relaxed_atoms, relax_info = mace_phonons.generate_ml_displacements(
                atoms_i, args.dim, args.distance, calc, relax=args.relax, fmax=args.fmax)
            mace_phonons.compute_force_constants(phonon, calc, progress_callback=_progress)

            energy_i = relaxed_atoms.get_potential_energy()
            volume_i = relaxed_atoms.get_volume()

            phonon.run_mesh(args.mesh)
            min_freq_i = phonon.mesh.frequencies.min()
            phonon.run_thermal_properties(t_min=args.tmin, t_max=t_max_grid, t_step=args.tstep)
            tp = phonon.thermal_properties
            if temperatures_ref is None:
                temperatures_ref = tp.temperatures

            vol_dir = os.path.join(output_root, f"vol_{i:02d}")
            os.makedirs(vol_dir, exist_ok=True)
            phonon.save(os.path.join(vol_dir, "phonopy_disp.yaml"), settings={'force_constants': True})

            volumes.append(volume_i)
            energies.append(energy_i)
            free_energy_list.append(tp.free_energy)
            entropy_list.append(tp.entropy)
            cv_list.append(tp.heat_capacity)

            n_disp = len(phonon.dataset['first_atoms'])
            freq_flag = color_text(f"{min_freq_i:13.4f}", 'red' if min_freq_i < 0 else 'green')
            if min_freq_i < 0:
                any_unstable = True
            print_dual(f"{strain_pct:8.2f} {volume_i:14.4f} {energy_i:14.6f} "
                        f"{n_disp:7d} {freq_flag}", f_out)

        if any_unstable:
            print_dual(color_text(
                "[WARNING] At least one volume has an imaginary (negative) frequency -- QHA "
                "assumes every sampled point is dynamically stable. Thermal properties at "
                "that volume (and results derived across the fit) may not be physically "
                "meaningful.", 'red'), f_out)

        # PhonopyQHA wants free_energy/cv/entropy shaped (temperatures, volumes)
        free_energy = np.array(free_energy_list).T
        entropy = np.array(entropy_list).T
        cv = np.array(cv_list).T

        qha = PhonopyQHA(volumes=volumes, electronic_energies=energies,
                          temperatures=temperatures_ref, free_energy=free_energy,
                          cv=cv, entropy=entropy, eos=args.eos, t_max=args.tmax)

        print_dual(f"\n{color_text('[2] EQUILIBRIUM FIT (T=0, static)', 'magenta')}", f_out)
        print_dual("-" * 60, f_out)
        e0, b0, b0p, v0_fit = qha.get_bulk_modulus_parameters()
        print_dual(f"E0 (min. energy)  : {e0:.6f} eV", f_out)
        print_dual(f"V0 (eq. volume)   : {v0_fit:.6f} Ang^3", f_out)
        print_dual(f"B0 (bulk modulus) : {b0:.4f} GPa", f_out)
        print_dual(f"B0' (pressure derivative): {b0p:.4f}", f_out)

        print_dual(f"\n{color_text('[3] THERMAL EXPANSION SUMMARY', 'magenta')}", f_out)
        print_dual("-" * 60, f_out)
        temps_qha = qha.thermal_expansion  # same T grid as temperatures_ref, truncated at t_max
        n_t = len(temps_qha)
        t_grid_trunc = temperatures_ref[:n_t]
        ref_idx = int(np.argmin(np.abs(t_grid_trunc - 300.0)))
        last_idx = n_t - 1
        for label, idx in (("T ~ 300 K", ref_idx), (f"T = {t_grid_trunc[last_idx]:.0f} K", last_idx)):
            print_dual(f"At {label}:", f_out)
            print_dual(f"  Volume            : {qha.volume_temperature[idx]:.4f} Ang^3", f_out)
            print_dual(f"  Thermal expansion : {qha.thermal_expansion[idx]:.6e} 1/K", f_out)
            print_dual(f"  Bulk modulus      : {qha.bulk_modulus_temperature[idx]:.4f} GPa", f_out)
            print_dual(f"  Gibbs free energy : {qha.gibbs_temperature[idx]:.6f} eV", f_out)

        plot_dir = os.path.join(output_root, args.plot_dir)
        plots_written = []
        plots_written.append(write_xy_plot(
            plot_dir, "eos_fit", "Energy vs. Volume (EOS points)", "Volume (Ang^3)",
            "Energy (eV)", volumes, energies, PLOT_COLORS[0], f_out))
        plots_written.append(write_xy_plot(
            plot_dir, "thermal_expansion", "Thermal Expansion Coefficient", "Temperature (K)",
            "alpha (1/K)", t_grid_trunc, qha.thermal_expansion, PLOT_COLORS[1], f_out))
        plots_written.append(write_xy_plot(
            plot_dir, "volume_temperature", "Equilibrium Volume vs. Temperature", "Temperature (K)",
            "Volume (Ang^3)", t_grid_trunc, qha.volume_temperature, PLOT_COLORS[2], f_out))
        plots_written.append(write_xy_plot(
            plot_dir, "bulk_modulus_temperature", "Bulk Modulus vs. Temperature", "Temperature (K)",
            "B (GPa)", t_grid_trunc, qha.bulk_modulus_temperature, PLOT_COLORS[0], f_out))
        plots_written.append(write_xy_plot(
            plot_dir, "gibbs_temperature", "Gibbs Free Energy vs. Temperature", "Temperature (K)",
            "G (eV)", t_grid_trunc, qha.gibbs_temperature, PLOT_COLORS[1], f_out))

        print_dual(f"\n{color_text('[4] SUMMARY & FILES', 'magenta')}", f_out)
        print_dual("-" * 60, f_out)
        print_dual(f"Report : {report_path}", f_out)
        print_dual(f"Per-volume phonon_runs-style directories: "
                    f"{output_root}/vol_00 .. vol_{args.n_points - 1:02d} "
                    "(explorable with stb-phononsPos)", f_out)
        print_dual(f"Plots  : {plot_dir}/ ({len(plots_written)} .dat/.gplot pairs)", f_out)

    print("\n" + "-" * 60)
    print(color_text("QHA complete (MACE-MP-0, no SIESTA)!\n", 'bold'))


if __name__ == "__main__":
    main()
