"""Shared real-space-grid export helpers: gnuplot 2D-slice/3D-cloud/1D-profile
data files + matching .gplot scripts, plus a quick integrated-quantity sanity
check. Extracted from density.py once stb-wfdensity became a second consumer
(writing a |psi|^2 grid through the exact same slice/3D/profile + pm3d-gnuplot
code path density.py already uses for .RHO grids).
"""

import sys
import time

import numpy as np

from stb.core.cli import color_text

# A cut plane whose two in-plane lattice vectors deviate from 90 degrees by more than
# this is flagged -- gnuplot's `pm3d map` interpolation assumes a roughly rectangular
# grid in the two plotted axes, and a skewed cell (e.g. hexagonal, common for 2D
# materials) can render visibly distorted even though the data file's own coordinates
# are correct.
NON_ORTHOGONAL_WARN_DEG = 1.0


def check_planar_orthogonality(lattice, axis_idx):
    """Returns the angle (degrees) between the two in-plane lattice vectors
    of the cut plane perpendicular to `axis_idx` -- 90 for a rectangular
    cut, something else for a skewed one (e.g. hexagonal cells).
    """
    in_plane = [i for i in range(3) if i != axis_idx]
    v1, v2 = lattice[in_plane[0]], lattice[in_plane[1]]
    cos_angle = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
    return float(np.degrees(np.arccos(np.clip(cos_angle, -1.0, 1.0))))


def write_gnuplot_script(data_filename, output_filename, mode, quantity_label,
                         is_signed, axis_idx=2, pos_val=0.0, plane_angle_deg=90.0,
                         cb_range=None, contour=False, generator_name="plotdensity.py",
                         units="e/Ang^3"):
    """
    Generates a .gplot script using the specific templates provided.
    - 3D: Based on '3dplot.gplot'
    - Slice: Based on 'plot.gplot'
    - Profile: a plain 2D line plot of the planar average

    cb_range, if given, is a (cb_min, cb_max) tuple written as an explicit
    'set cbrange' -- for a signed quantity (spin density, --rho2 difference)
    this should be symmetric around zero so the diverging palette's white
    midpoint actually lands on zero (gnuplot's autorange centers white at
    (data_min+data_max)/2, not necessarily 0, for asymmetric data).

    `generator_name` is the "# Generated by ..." comment written into the
    script -- defaults to this module's original hardcoded caller
    (density.py) for backward compatibility; a different caller (e.g.
    stackingfaultAnalysis's 'slice'-mode gamma-surface reuse) should pass
    its own name.

    `units` is the parenthesized unit suffix appended to the y/cb axis
    label -- defaults to this module's original hardcoded "e/Ang^3"
    (charge/spin density) for backward compatibility; a caller plotting a
    different quantity (e.g. an energy landscape) should pass its own,
    e.g. units="eV".
    """
    gplot_name = output_filename.rsplit('.', 1)[0] + ".gplot"
    pdf_name = output_filename.rsplit('.', 1)[0] + ".pdf"

    axis_labels = ['X', 'Y', 'Z']
    fixed_axis = axis_labels[axis_idx]

    fileout = []
    fileout.append('# --- STB Plot Configuration ---\n')
    fileout.append(f'# Generated by {generator_name}\n')
    if mode != 'profile' and abs(plane_angle_deg - 90.0) > NON_ORTHOGONAL_WARN_DEG:
        fileout.append(
            f'# NOTE: the cut plane is skewed ({plane_angle_deg:.1f} deg between its two\n'
            '# in-plane lattice vectors, not 90) -- pm3d map assumes a roughly rectangular\n'
            '# grid in the two plotted axes, so this may render visibly distorted even\n'
            "# though the data file's own X/Y/Z coordinates are correct. Consider plotting\n"
            '# the data file directly in a tool that triangulates irregular points (e.g.\n'
            '# matplotlib tricontourf, VESTA) if this looks wrong.\n'
        )

    # --- TEMPLATE: PROFILE (planar-averaged 1D line) ---
    if mode == 'profile':
        fileout.append('set terminal pdfcairo enhanced color font "Arial,14" size 7,5\n')
        fileout.append(f'set output "{pdf_name}"\n')
        fileout.append('\n')

        fileout.append(f'set title "Planar-averaged {quantity_label} along {fixed_axis}"\n')
        fileout.append(f'set xlabel "{fixed_axis} (Angstrom)"\n')
        fileout.append(f'set ylabel "{quantity_label} ({units})"\n')
        fileout.append('set grid\n')
        if is_signed:
            fileout.append('set arrow from graph 0,first 0 to graph 1,first 0 nohead lc rgb "gray" dt 2\n')
        fileout.append(f'plot "{data_filename}" using 1:2 with lines lw 2 lc rgb "#cc5522" title "{quantity_label}"\n')

    # --- TEMPLATE: SLICE (Based on plot.gplot) ---
    elif mode == 'slice':
        # Output setup
        fileout.append(f'set terminal pdfcairo enhanced color font "Arial,14" size 6,5\n')
        fileout.append(f'set output "{pdf_name}"\n')
        fileout.append('\n')

        # Logic to choose columns for 2D Map (X vs Y, X vs Z, Y vs Z)
        if axis_idx == 2:   # Fixed Z -> Plot X(1) vs Y(2)
            cols = "1:2:4"
            xl, yl = "X (Angstrom)", "Y (Angstrom)"
        elif axis_idx == 1: # Fixed Y -> Plot X(1) vs Z(3)
            cols = "1:3:4"
            xl, yl = "X (Angstrom)", "Z (Angstrom)"
        elif axis_idx == 0: # Fixed X -> Plot Y(2) vs Z(3)
            cols = "2:3:4"
            xl, yl = "Y (Angstrom)", "Z (Angstrom)"

        fileout.append(f'set title "{quantity_label} Slice ({fixed_axis}={pos_val:.2f} A)"\n')
        fileout.append(f'set xlabel "{xl}"\n')
        fileout.append(f'set ylabel "{yl}"\n')
        fileout.append(f'set cblabel "{quantity_label} ({units})"\n')

        # Style from plot.gplot
        fileout.append('set size ratio -1\n')
        fileout.append('set tics out nomirror\n')
        fileout.append('set pm3d map\n')
        fileout.append('set pm3d interpolate 10,10  # Smoothing\n')

        if is_signed:
            fileout.append('# Palette: Blue -> White -> Red (diverging, for a signed quantity)\n')
            fileout.append('set palette defined (0 "#000099", 1 "#2255cc", 2 "#ffffff", 3 "#cc5522", 4 "#990000")\n')
        else:
            fileout.append('# Palette: White -> Yellow -> Red (sequential, for a non-negative quantity)\n')
            fileout.append('set palette defined (0 "#ffffff", 1 "#ffeda0", 2 "#feb24c", 3 "#f03b20", 4 "#bd0026")\n')

        if cb_range is not None:
            fileout.append(f'set cbrange [{cb_range[0]:.6g}:{cb_range[1]:.6g}]\n')

        if contour:
            fileout.append('# Contour overlay\n')
            fileout.append('set contour base\n')
            fileout.append('set cntrparam levels 10\n')
            fileout.append('unset clabel\n')

        fileout.append(f'splot "{data_filename}" using {cols} with pm3d\n')

    # --- TEMPLATE: 3D (Based on 3dplot.gplot) ---
    else:
        # Output setup (PDF as requested)
        fileout.append(f'set terminal pdfcairo enhanced color font "Arial,12" size 8,6\n')
        fileout.append(f'set output "{pdf_name}"\n')
        fileout.append('\n')

        fileout.append(f'set title "3D {quantity_label} (Point Cloud)"\n')
        fileout.append('set xlabel "X (Angstrom)"\n')
        fileout.append('set ylabel "Y (Angstrom)"\n')
        fileout.append('set zlabel "Z (Angstrom)"\n')

        # Styles from 3dplot.gplot
        fileout.append('set view 60, 120, 1, 1\n')
        fileout.append('set size ratio -1\n')
        fileout.append('set ticslevel 0\n')

        # Depthorder and Fill
        fileout.append('set pm3d depthorder\n')
        fileout.append('set style fill solid 1.0 noborder\n')

        # Palette: Vibrant Spectrum
        fileout.append('set palette defined (0 "#2c7bb6", 1 "#00a6ca", 2 "#00ccbc", 3 "#90eb9d", 4 "#ffff8c", 5 "#f9d057", 6 "#f29e2e", 7 "#e76818", 8 "#d7191c")\n')

        if cb_range is not None:
            fileout.append(f'set cbrange [{cb_range[0]:.6g}:{cb_range[1]:.6g}]\n')

        # Note: 'pm3d' requires grid structure. 'points' works for volume clouds.
        # We use 'points' here to visualize the density cloud.
        fileout.append(f'splot "{data_filename}" using 1:2:3:4 with points palette pt 7 ps 0.4 title "{quantity_label}"\n')

    with open(gplot_name, 'w') as f:
        f.writelines(fileout)

    print(f"[INFO] Gnuplot script saved to '{color_text(gplot_name, 'green')}'")
    print(f"[INFO] To plot: {color_text(f'gnuplot {gplot_name}', 'cyan')}")

def integrated_charge(grid_data, lattice):
    """Sum of grid values times the voxel volume -- the total integrated
    quantity over the cell: electron count for a total charge density,
    net moment for a spin density, net transferred charge for a --rho2
    difference. A quick sanity check against the expected valence electron
    count, independent of any plotting/slicing choice.
    """
    cell_volume = abs(np.linalg.det(lattice))
    voxel_volume = cell_volume / grid_data.size
    return float(grid_data.sum() * voxel_volume)


def write_profile_data_file(grid_data, lattice, axis, output_file):
    """Writes the planar average of grid_data over the two axes perpendicular
    to `axis`, as a function of position along `axis` -- a 1D density/spin
    profile useful for slabs, interfaces, and superlattices. Returns the
    (min, max) of the profile values.
    """
    print(f"[INFO] Mode: Planar-Averaged Profile")
    avg_axes = tuple(a for a in (0, 1, 2) if a != axis)
    profile = grid_data.mean(axis=avg_axes)
    n = profile.shape[0]
    axis_len = np.linalg.norm(lattice[axis])
    positions = (np.arange(n) / n) * axis_len

    with open(output_file, 'w') as f:
        f.write(f"# Generated by STB. Format: Position(Ang) Planar_Averaged_Value\n")
        for pos, val in zip(positions, profile):
            f.write(f"{pos:.6f} {val:.6e}\n")

    return float(profile.min()), float(profile.max())


def write_data_file(grid_data, lattice, origin, output_file, mode='3d', slice_idx=0, axis=2,
                    iso_min=None):
    """
    Writes grid data. For 'slice' mode, ensures block format for PM3D.
    Returns the (min, max) of the values actually written, so the caller can
    build a matching colorbar range.
    """
    nx, ny, nz = grid_data.shape
    start_time = time.time()

    # --- 3D MODE ---
    if mode == '3d':
        print(f"[INFO] Mode: Full 3D Volume Export")
        print(f"[INFO] Processing {nx*ny*nz} grid points...")

        # Use vectorized operations for speed
        ix, iy, iz = np.meshgrid(range(nx), range(ny), range(nz), indexing='ij')

        # Coordinates
        frac_coords = np.vstack([ix.flatten()/nx, iy.flatten()/ny, iz.flatten()/nz]).T
        values_flat = grid_data.flatten()

        if iso_min is not None:
            n_before = len(values_flat)
            mask = np.abs(values_flat) >= iso_min
            frac_coords = frac_coords[mask]
            values_flat = values_flat[mask]
            n_after = len(values_flat)
            pct = (100.0 * n_after / n_before) if n_before else 0.0
            print(f"[INFO] --iso-min {iso_min}: kept {n_after}/{n_before} points ({pct:.1f}%)")
            if n_after == 0:
                print(color_text(
                    "[ERROR] No points survived --iso-min -- the threshold is higher than "
                    "every |value| in this grid.", 'red'))
                sys.exit(1)

        real_coords = origin + np.dot(frac_coords, lattice)
        data_to_save = np.column_stack([real_coords, values_flat])

        # Simple export for point cloud
        header_txt = "X Y Z Charge_Density"
        np.savetxt(output_file, data_to_save, fmt='%.6f %.6f %.6f %.6e', header=header_txt)

        vmin, vmax = float(values_flat.min()), float(values_flat.max())

    # --- 2D MAP MODE (Slice) ---
    elif mode == 'slice':
        axis_names = ['X', 'Y', 'Z']
        print(f"[INFO] Mode: 2D Map (Slice)")
        print(f"[INFO] Mapping plane perpendicular to {axis_names[axis]} axis at Index {slice_idx}")

        # Slice plane values, taken directly (cheap) to build a matching colorbar range
        if axis == 2:
            slice_arr = grid_data[:, :, slice_idx]
        elif axis == 1:
            slice_arr = grid_data[:, slice_idx, :]
        else:
            slice_arr = grid_data[slice_idx, :, :]
        vmin, vmax = float(slice_arr.min()), float(slice_arr.max())

        with open(output_file, 'w') as f:
            f.write(f"# Generated by STB. Format: X Y Z Charge_Density\n")

            # Select iteration ranges based on which axis is fixed
            if axis == 2:   # Cut along Z (XY Plane)
                u_range, v_range = range(nx), range(ny)
                i_fixed = slice_idx
            elif axis == 1: # Cut along Y (XZ Plane)
                u_range, v_range = range(nx), range(nz)
                i_fixed = slice_idx
            elif axis == 0: # Cut along X (YZ Plane)
                u_range, v_range = range(ny), range(nz)
                i_fixed = slice_idx

            # Nested loop to create PM3D blocks (Blank line separation)
            for i in u_range:
                for j in v_range:
                    if axis == 2: ix, iy, iz = i, j, i_fixed
                    elif axis == 1: ix, iy, iz = i, i_fixed, j
                    elif axis == 0: ix, iy, iz = i_fixed, i, j

                    frac_coords = np.array([ix/nx, iy/ny, iz/nz])
                    real_pos = origin + np.dot(frac_coords, lattice)
                    val = grid_data[ix, iy, iz]

                    f.write(f"{real_pos[0]:.6f} {real_pos[1]:.6f} {real_pos[2]:.6f} {val:.6e}\n")

                f.write("\n") # Blank line for PM3D structure

    elapsed = time.time() - start_time
    print(f"[INFO] Write completed in {elapsed:.2f} seconds.")
    return vmin, vmax
