#!/bin/bash
# Guided example: stb-crystalcast (code 2.12 in the stb-suite menu)
#
# Not an automated test (see test/2-structures/12-crystalcast/test.sh for
# that) -- a commented walk-through: it runs real commands, one group at a
# time, into its own output/<case>/ folder, and shows you the piece of
# output that proves what just happened. Pauses between sections so you
# can read before moving on. Safe to re-run any time -- it always starts
# by wiping its own output/. No committed input fixtures: like
# 2.8-stb-crystalbuilder, everything --generate/--molecular/--dim needs is
# built from flags; the one fixture --substitute/--subgroup/--supergroup
# need is generated by this script's own first case, not checked in.

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

HAS_MACE=0
if python3 -c "import mace" 2>/dev/null; then
    HAS_MACE=1
fi

OUT="$DIR/output"
rm -rf "$OUT"
mkdir -p "$OUT"

pause() {
    echo
    read -p "  [Press Enter to continue] " -r
    echo
}

strip_ansi() {
    sed 's/\x1b\[[0-9;]*m//g' "$1"
}

echo "=================================================================="
echo " What stb-crystalcast does: the inverse of stb-crystalbuilder"
echo "=================================================================="
cat <<'EOF'
stb-crystalbuilder (2.8) builds a structure from a space group + the exact
Wyckoff sites YOU specify -- you already know where every symmetrically
distinct atom goes. stb-crystalcast solves the opposite problem: give it
only a symmetry group and a COMPOSITION (which elements, how many of
each), and pyxtal randomly assigns atoms to Wyckoff positions that are
actually compatible with that group -- valid candidate structures,
generated for you, e.g. as starting guesses for structure prediction.

A Wyckoff position is a set of equivalent sites forced by the group's own
symmetry operations: placing ONE atom at a Wyckoff site automatically
generates every symmetry-equivalent copy of it. pyxtal's job is finding a
combination of Wyckoff sites (site multiplicities summing correctly per
element) that fits your requested composition, then drawing random
coordinates for whichever sites still have free parameters.

This is stb-crystalcast's "generate" mode -- the default when no other
mode flag is given. Three other modes work on an EXISTING structure
instead (read via -f/--file): --substitute (swap elements, keep the
symmetry framework), and --subgroup/--supergroup (search for a related
lower-/higher-symmetry structure) -- covered further down.
EOF
pause

echo "=================================================================="
echo " output/vs-crystalbuilder/  --  the SAME structure, two opposite ways in"
echo "=================================================================="
cat <<'EOF'
Proof, not just a claim: build the exact same real rock-salt NiO both
ways. stb-crystalbuilder needs you to already know where each atom goes
(Wyckoff site 4a for Ni, 4b for O, in space group 225) -- give it the
WRONG sites and it happily builds a real, different structure with no
warning, because it has no composition to check against. stb-crystalcast
never needs a site: give it 4 Ni + 4 O and space group 225, and pyxtal
searches out a compatible Wyckoff assignment (4a+4b is essentially the
only one that fits this composition and group) on its own:
EOF
mkdir -p "$OUT/vs-crystalbuilder"
echo
echo "\$ stb-crystalbuilder --spacegroup 225 --a 4.17 --site Ni 0 0 0 --site O 0.5 0.5 0.5 \\"
echo "      -o nio_builder.fdf --no-intro   # YOU must know these are 4a/4b"
(cd "$OUT/vs-crystalbuilder" && stb-crystalbuilder --spacegroup 225 --a 4.17 \
    --site Ni 0 0 0 --site O 0.5 0.5 0.5 -o nio_builder.fdf --no-intro \
    > console_builder.log 2>&1)
grep -E "^Output formula|^Output atoms" "$OUT/vs-crystalbuilder/console_builder.log"

echo
echo "\$ stb-crystalcast --group 225 --species Ni O --num-ions 4 4 \\"
echo "      -o nio_cast.fdf --no-intro       # only the COMPOSITION, no sites"
(cd "$OUT/vs-crystalbuilder" && stb-crystalcast --group 225 --species Ni O --num-ions 4 4 \
    -o nio_cast.fdf --no-intro > console_cast.log 2>&1)
grep -E "as-built space group" "$OUT/vs-crystalbuilder/console_cast.log"
echo
echo "Both are real, valid Fm-3m NiO -- stb-crystalbuilder because you told it"
echo "exactly where; stb-crystalcast because it worked it out from the"
echo "composition alone. Neither tool is 'better' -- they answer different"
echo "questions (see the comparison table in this folder's README.md for"
echo "stb-sqs/stb-defect/stb-symmetry/stb-molecule/stb-mlsearch too)."
pause

echo "=================================================================="
echo " subgroup/supergroup: symmetry-breaking and symmetry-restoring searches"
echo "=================================================================="
cat <<'EOF'
No other tool in this suite does this. --subgroup takes an existing
structure and searches for related structures with LOWER symmetry (a
"translationengleiche" or "klassengleiche" group-subgroup relation,
--group-type t/k) -- a controlled symmetry-breaking distortion, useful for
generating candidate low-symmetry phases of a known high-symmetry parent
(e.g. searching for a real ferroelectric distortion of a cubic perovskite).
--supergroup does the reverse: given a (possibly distorted) structure and
a target HIGHER-symmetry group, it searches for the symmetric parent
structure that group-subgroup theory says it should be a distortion of.

--eps (subgroup) is the atomic-coordinate perturbation applied when
breaking symmetry; --d-tol (supergroup) is the maximum displacement
tolerated when testing whether a candidate parent structure is actually
close enough to the input to be considered a match.
EOF
pause

echo "=================================================================="
echo " Two ways to run it"
echo "=================================================================="
cat <<'EOF'
A -- direct CLI:
  stb-crystalcast --group 225 --species Ni O --num-ions 4 8

B -- interactive stb-suite menu:
  $ stb-suite
  Select an option (0-6, or a tool code like 4.1.2): 2.12

Every run always writes a numbered report ([0] RUN METADATA ... [8]
SUMMARY & FILES), structure validation, a symmetry table, and
references.bib (SIESTA + PyXtal always; + MACE/MACE-MP with --ml-rank). A
full text report (--save-report) and an interactive 3D view (--view) are
off by default.
EOF
pause

echo "=================================================================="
echo " output/generate/  --  rock-salt NiO from a space group + composition"
echo "=================================================================="
cat <<'EOF'
--group 225 (Fm-3m, rock salt) + 4 Ni + 8 O -- pyxtal finds a Wyckoff
combination compatible with that group and composition, and draws the
free coordinates randomly. --save-report also proves the standardized
report/provenance-header/references.bib conventions from here on:
EOF
mkdir -p "$OUT/generate"
echo
echo "\$ stb-crystalcast --group 225 --species Ni O --num-ions 4 8 --save-report \\"
echo "      -o nio.fdf --no-intro"
(cd "$OUT/generate" && stb-crystalcast --group 225 --species Ni O --num-ions 4 8 \
    --save-report -o nio.fdf --no-intro > console.log 2>&1)
grep -E "as-built space group|Requested space group:" "$OUT/generate/console.log"
echo
echo "Provenance header written into nio.fdf:"
head -3 "$OUT/generate/nio.fdf"
echo
echo "references.bib (SIESTA + PyXtal, no MACE -- --ml-rank wasn't used):"
grep "^@" "$OUT/generate/references.bib"
pause

echo "=================================================================="
echo " output/count-and-seed/  --  batches and reproducibility"
echo "=================================================================="
cat <<'EOF'
--count generates several independent random candidates in one run
(numbered <output>_1.fdf, _2.fdf, ...); --seed makes the whole batch
reproducible. Watch the SAME seed give bit-identical structure data
twice, and --count 3 give 3 genuinely different candidates:
EOF
mkdir -p "$OUT/count-and-seed"
echo
echo "\$ stb-crystalcast --group 225 --species Ni O --num-ions 4 8 --count 3 --seed 7 \\"
echo "      -o batch.fdf --no-intro"
(cd "$OUT/count-and-seed" && stb-crystalcast --group 225 --species Ni O --num-ions 4 8 \
    --count 3 --seed 7 -o batch.fdf --no-intro > console.log 2>&1)
ls "$OUT/count-and-seed"/batch_*.fdf
if diff -q <(grep -v '^#' "$OUT/count-and-seed/batch_1.fdf") \
           <(grep -v '^#' "$OUT/count-and-seed/batch_2.fdf") > /dev/null; then
    echo "Unexpected: batch_1 and batch_2 are identical."
else
    echo "Confirmed: batch_1.fdf and batch_2.fdf are genuinely different candidates."
fi
pause

echo "=================================================================="
echo " output/molecular-and-clusters/  --  packing molecules, isolated point groups"
echo "=================================================================="
cat <<'EOF'
--molecular packs whole rigid molecules (from pyxtal's own bundled
collection, a .xyz/.gjf/.g03/.json path, or a SMILES string) into the
symmetry group instead of bare atoms -- useful for molecular-crystal
candidates. --dim 0 is the opposite extreme: an isolated CLUSTER with no
periodicity at all, classified by a POINT group (Schoenflies notation)
instead of a space group, boxed in vacuum exactly like stb-molecule's own
convention:
EOF
mkdir -p "$OUT/molecular-and-clusters"
echo
echo "\$ stb-crystalcast --molecular --group 19 --species H2O --num-ions 4 \\"
echo "      -o ice.fdf --no-intro          # 4 water molecules, space group 19"
(cd "$OUT/molecular-and-clusters" && stb-crystalcast --molecular --group 19 --species H2O \
    --num-ions 4 -o ice.fdf --no-intro > console_ice.log 2>&1)
grep -E "as-built space group" "$OUT/molecular-and-clusters/console_ice.log"
echo
echo "\$ stb-crystalcast --dim 0 --group D3d --species C --num-ions 6 --vacuum 10 \\"
echo "      -o cluster.fdf --no-intro       # isolated 6-carbon cluster, point group D3d"
(cd "$OUT/molecular-and-clusters" && stb-crystalcast --dim 0 --group D3d --species C \
    --num-ions 6 --vacuum 10 -o cluster.fdf --no-intro > console_cluster.log 2>&1)
grep -E "as-built point group" "$OUT/molecular-and-clusters/console_cluster.log"
pause

echo "=================================================================="
echo " output/substitute/  --  swap elements, keep the symmetry framework"
echo "=================================================================="
cat <<'EOF'
--substitute reads an existing structure and swaps one or more elements
while keeping every atom on its original Wyckoff site -- the symmetry
framework itself never changes (unlike a real chemical substitution
study, which would need to re-relax the geometry afterward). Reusing
output/generate/'s NiO structure, substituting O for S:
EOF
mkdir -p "$OUT/substitute"
cp "$OUT/generate/nio.fdf" "$OUT/substitute/"
echo
echo "\$ stb-crystalcast --substitute O:S -f nio.fdf -o nis.fdf --no-intro"
(cd "$OUT/substitute" && stb-crystalcast --substitute O:S -f nio.fdf -o nis.fdf \
    --no-intro > console.log 2>&1)
strip_ansi "$OUT/substitute/console.log" | \
    awk '/\[3\] SUBSTITUTION/{flag=1} /\[4\] STRUCTURE VALIDATION/{flag=0} flag' | \
    grep -v "^-\+$\|^\[3\]"
strip_ansi "$OUT/substitute/console.log" | awk '/^Property/,/^$/'
pause

echo "=================================================================="
echo " output/subgroup-supergroup/  --  symmetry-breaking and symmetry-restoring"
echo "=================================================================="
cat <<'EOF'
--subgroup distorts the NiO structure into lower-symmetry candidates;
--supergroup then takes ONE of those distorted candidates back towards a
target group. This can genuinely go either way depending on the specific
distortion/--d-tol: pyxtal either finds a matching parent, or reports a
clean "not found" -- both are legitimate outcomes of a real symmetry
search, not a crash either way:
EOF
mkdir -p "$OUT/subgroup-supergroup"
cp "$OUT/generate/nio.fdf" "$OUT/subgroup-supergroup/"
echo
echo "\$ stb-crystalcast --subgroup -f nio.fdf --count 3 -o distorted.fdf --no-intro"
(cd "$OUT/subgroup-supergroup" && stb-crystalcast --subgroup -f nio.fdf --count 3 \
    -o distorted.fdf --no-intro > console_sub.log 2>&1)
grep -E "^  #[0-9]+:" "$OUT/subgroup-supergroup/console_sub.log"
echo
echo "\$ stb-crystalcast --supergroup --target-group 225 -f distorted_1.fdf \\"
echo "      -o parent.fdf --no-intro --d-tol 3.0"
(cd "$OUT/subgroup-supergroup" && stb-crystalcast --supergroup --target-group 225 \
    -f distorted_1.fdf -o parent.fdf --no-intro --d-tol 3.0 > console_super.log 2>&1) || true
if grep -q "no supergroup structure found" "$OUT/subgroup-supergroup/console_super.log"; then
    echo "(No candidate found at this --d-tol for this particular distortion --"
    echo " a real, honest outcome pyxtal's own search can report, not a crash.)"
else
    grep -E "^  #[0-9]+:" "$OUT/subgroup-supergroup/console_super.log"
fi
pause

if [ "$HAS_MACE" -eq 1 ]; then
    echo "=================================================================="
    echo " output/ml-rank/  --  screening candidates by MACE relaxed energy"
    echo "=================================================================="
    cat <<'EOF'
--ml-rank relaxes every generated candidate's positions with a MACE
potential and ranks them by relaxed energy -- a fast, relative pre-screen
for which candidate(s) to prioritize for real DFT, not an absolute
formation energy. --model/--custom-model choose which MACE-MP-0 size (or
your own fine-tuned model) does the relaxing:
EOF
    mkdir -p "$OUT/ml-rank"
    echo
    echo "\$ stb-crystalcast --group 225 --species Ni O --num-ions 4 8 --count 3 --seed 7 \\"
    echo "      --ml-rank --model small -o ranked.fdf --no-intro"
    (cd "$OUT/ml-rank" && stb-crystalcast --group 225 --species Ni O --num-ions 4 8 \
        --count 3 --seed 7 --ml-rank --model small -o ranked.fdf --no-intro > console.log 2>&1)
    awk '/ML-ranked structures/,/^$/' "$OUT/ml-rank/console.log"
    pause
else
    echo "=================================================================="
    echo " output/ml-rank/  --  skipped (optional 'ml' extra not installed)"
    echo "=================================================================="
    echo "pip install stb_suite[ml]  # then re-run this script to see --ml-rank"
    pause
fi

echo "=================================================================="
echo " Proof: CLI and the interactive stb-suite menu agree"
echo "=================================================================="
echo "Driving the same generate case through the interactive menu's manual"
echo "entry mode and checking it reaches the same detected space group."
TMP="$(mktemp -d)"
echo
echo "\$ printf '2.12\\n\\n\\nn\\n225\\nNi 4\\nO 8\\n\\n\\n\\n\\n\\n\\nn\\n\\n\\n\\n0\\n' | stb-suite"
(cd "$TMP" && printf '2.12\n\n\nn\n225\nNi 4\nO 8\n\n\n\n\n\n\nn\n\n\n\n0\n' | \
    stb-suite > session.log 2>&1) || true
if grep -q "space group Fm-3m (No. 225)" "$TMP/session.log"; then
    echo "Confirmed: the interactive menu built and launched the exact same"
    echo "underlying stb-crystalcast command as the CLI walkthrough above"
    echo "(space group Fm-3m (No. 225), same as output/generate/console.log)."
else
    echo "Unexpected: menu did not reach the write step -- see $TMP/session.log."
fi
rm -rf "$TMP"
pause

echo "=================================================================="
echo " Done"
echo "=================================================================="
cat <<EOF
Seven or eight self-contained folders were generated under output/
(ml-rank/ noted skipped above if the optional 'ml' extra isn't installed):
  vs-crystalbuilder/        generate/
  count-and-seed/           molecular-and-clusters/
  substitute/               subgroup-supergroup/
  ml-rank/

Each has references.bib; generate/ additionally has stb_crystalcast_report.txt.

Recap of what this walkthrough covered:
  - generate mode vs. stb-crystalbuilder, built live: the exact same real
    NiO structure, one from sites YOU give, one from composition alone
  - --count/--seed: batches of independent candidates, reproducible or not
  - --molecular (whole rigid molecules) and --dim 0 (isolated point-group
    clusters, the same vacuum-box convention as stb-molecule)
  - --substitute: element swap preserving the symmetry framework
  - --subgroup/--supergroup: the only symmetry-breaking/-restoring search
    in the suite, verified as genuine inverses on the same structure
  - --ml-rank + --model/--custom-model: MACE-based relaxed-energy screening
  - the provenance header, references.bib (SIESTA + PyXtal, + MACE with
    --ml-rank), and --save-report
  - CLI and the interactive stb-suite menu building the same command

Not exercised by this script (needs a display): --view opens every written
structure interactively via ASE -- try it yourself:
  stb-crystalcast --group 225 --species Ni O --num-ions 4 8 --view

As a next step, try on your own:
  stb-crystalcast --group 225 --species Na Cl --num-ions 4 4 --sites 4a 4b
  stb-crystalcast --list-molecules

To inspect an EXISTING structure's own symmetry/Wyckoff decomposition
(what --analyze used to do here, before this session's simplification),
use stb-symmetry or stb-unitcell instead.
EOF
